### ISSUE TITLE
Update ProfileInfo

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#1011]
### Desc:
- only open profile info via DirectChat 

### DoD:
- [ ] copy button beside matirxId
- [ ] show email/phone of this profile via `/lookup/match`
- [ ] list media
- [ ] list link

**Comment by QuangHoang1210** [comment]
- Profile image --> Looking blur -> Should make origin image quality + user can click to view profile image in full screen
- Should redesign the way to displaying MatrixID + user account (feeling confuse)
- UX: Share media -> User only click exactly on Play icon in video then he can watch that video. Should improve -> Anywhere in video range will be clickable to play video
