### ISSUE TITLE
Sign-Up process(Registration)

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#1022]
### Story:
- https://www.notion.so/linagora/As-a-user-I-want-to-sign-up-by-SMS-web-and-mobile-c7a5bcbb64e549e89faf5b2460455c14

### Design:
- https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?type=design&node-id=17873-22903&mode=dev

### Desc:
- web-base register site
- work with `Octopush`
- combine `register` then return `accessToken` for app: Twake Chat and Twake Mail

### DoD:
- [ ] [Mobile] After register, user no need to re-input username/password for login

**Comment by hoangdat** [comment]
Hi @guimard and @rezk2ll , user story for registration is validated and ready to move forward.

**Comment by rezk2ll** [comment]
thanks @hoangdat

**Comment by hoangdat** [comment]
PR: 
- Sign up: https://github.com/linagora/twake-on-matrix/pull/1316
- Sign in:
