### ISSUE TITLE
User credentials still keep login when user already remove & reinstall Twake application - that make user cannot signin with other account

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1036]
OS: IOS / Android / Website
Device: Laptop
Twake version:  2.4.0

### **Noted:** 
This issue also happen in case user remove the Twake app and reinstall again

### **Precondition:** 
User not login yet or user log out an account

### **Step:** 
1, User access Twake app
2, User input home sever
3, User input correct credentials
4, User click Login
5, User close the Confirmation Website
6, User click again on Continue at Home Sever screen

### **Actual:** 
System navigate user to Confirmation Website which already logged in with Account Credentials at step 3
-> That make user cannot login with another account

### **Expected:** 
System should navigate user to Login screen where user can retry login with other Account credentials

https://github.com/linagora/twake-on-matrix/assets/124866146/6c3a0f53-0de0-4d23-89b3-d604e8444175

**Comment by QuangHoang1210** [comment]
@hoangdat

**Comment by hoangdat** [comment]
can not reproduce it
