### ISSUE TITLE
If the user name is long then it is not displayed fully when user mentioned in the chat

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1037]
OS: IOS / Android / Website
Device: Laptop
Twake version:  2.4.0

### **Precondition:** 
User name is long

### **Step:** 
1, User mentioned as @+username 
2, User click send

### **Actual:** 
The name of user is not displayed fully

### **Expected:** 
Name of user should be displayed fully

https://github.com/linagora/twake-on-matrix/assets/124866146/6dc75779-06f6-4a7f-9112-86103178f714

**Comment by nqhhdev** [comment]
We are updating display tag name on this ticket #893
