### ISSUE TITLE
[Media list] Feeling laggy when scroll in media list and the thumbnail of images/videos are not revert to correct ratio

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1039]
OS: IOS / Android / Website
Device: Laptop
Twake version:  2.4.0

### **Precondition:** 
Existed image / videos in media list of chat

### **Step:** 
1, User click on media list
2, User scroll down/up

### **Actual:** 
- Feeling laggy when scroll to view media list
- The thumbnail of images/ videos is not convert to correct ratio that make user feeling it's broken

### **Expected:** 
- Scroll smoothly
- Thumbnail of images/videos is converted to correct small ratio which make good sense

https://github.com/linagora/twake-on-matrix/assets/124866146/bdce8a61-65e9-4e6a-821f-0cc828be35fc

**Comment by nqhhdev** [comment]
#1040
