### ISSUE TITLE
Investigating notification in background of Element app

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#1041]
### Desc:
- https://github.com/vector-im/element-x-ios/blob/develop/ElementX/Sources/Application/AppCoordinator.swift

### DoD:
- [ ] Debug flow of Notification of Element
- [ ] Background Request iOS, mechanism, limitation
- [ ] How to run Background task in iOS

**Comment by hoangdat** [comment]
### Background Task
- [ ] docs
- [ ] mechanism 
- [ ] example

**Comment by hoangdat** [comment]
### Element Background task
- [ ] what is inside `startSync()`
- [ ] ....

**Comment by hoangdat** [comment]
duplicated #363

**Comment by shepilov** [comment]
@hoangdat is it still relevant?
