### ISSUE TITLE
When you enter a message, and you want to make a separation with new line it doesn't work as expected

### ISSUE THREAD

**Issue by shepilov** [linagora/twake-on-matrix#1052]
First one:
You have already entered a text and you want to make a separation in the middle of your text, the new line will appear only at the end of the message despite the cursor being in the middle 

Another one: 
Sometimes it doesn't work also for the end of the text, I experienced this a couple of times when the text was long and with the link

**Comment by hoangdat** [comment]
Hi @QuangHoang1210 please help me verify it.

**Comment by QuangHoang1210** [comment]
Known issues -- Can reproduce on 2.4.0

https://github.com/linagora/twake-on-matrix/issues/638

@hoangdat hoang
@shepilov shep
