### ISSUE TITLE
For the web app messages don't appear in the chronological order in the right order 

### ISSUE THREAD

**Issue by shepilov** [linagora/twake-on-matrix#1053]
I was writing messages in the group chat:
<img width="777" alt="image" src="https://github.com/linagora/twake-on-matrix/assets/14924963/dd5032e1-b416-4642-a5df-e8b157e4b6c6">

1. I didn't receive any notification for the message from Montassar either on the web or on mobile
2. The message appeared only after I wrote a new message in the chat, and probably after some time
3. Page refresh didn't change the situation
4. For Montassar messages look like 
<img width="394" alt="image" src="https://github.com/linagora/twake-on-matrix/assets/14924963/a4d0d96f-873a-4442-b9e0-9cc8c2239b4e">

**Comment by hoangdat** [comment]
hi @MontaGhanmy , what is your device? iOS or Android?, can you show me the version of App? 
```
Settings -> About 
```

**Comment by hoangdat** [comment]
Hi @shepilov , you use the `Safari`?

**Comment by MontaGhanmy** [comment]
> hi @MontaGhanmy , what is your device? iOS or Android?, can you show me the version of App?
> 
> ```
> Settings -> About 
> ```

Hi @hoangdat , I'm on iOS. I don't have the "About" option. I think based on Testflight, I'm on version 2.4.0.

**Comment by shepilov** [comment]
At first you need to keep the app in the browser but don't open it enough time, so it stops receiving updates

And then, try to send message without refreshing the page, and then refresh the page

And you will receive all updates after your just send message, no matter that updates were sent earlier

And if you are at the same time will be texting from mobile phone in the same chat, we will have random message order depending on reieveing message timestamp but not timestamp when message was sent

**Comment by hoangdat** [comment]
- trigger `/sync` whenever app is in focus
