### ISSUE TITLE
I cannot find the existed user name in create new chat / new group chat

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1056]
OS: IOS / Android / Website
Device: Laptop / Mobile
Twake version:  2.4.0

### **Precondition:** 
I already in the same chat conversation with that user

### **Sample test data:** 
User 1: nqnguyen
User 2: qatest1

### **Step:** 
1, User1 chat with user 2 already
2, User1 click to create new chat / new group chat
3, User1 search 'qatest' on the searching input field

### **Actual:** 
There is no 'qatest1' in the searching result

### **Expected:** 
It should have qatest1 in the searching result.

### **Noted** 
1, UC1: Create new direct chat
**Precondition** Already chat with each other in the direct chat room
If user 1 search name of user 2 in new direct chat flow -> user 1 can see user 2 in the searching result -> If user 1 click on user 2 name then system redirect user 1 to the current direct chat room

2, UC2: Create new group chat
**Precondition** Already chat with each other in the direct chat room
If user 1 search name of user 2 in new group chat -> user 1 can see user 2 in the searching result and can select it in order to create the group chat with him

https://github.com/linagora/twake-on-matrix/assets/124866146/cbdb4f62-7706-44c5-9988-189c967dab0a

**Comment by hoangdat** [comment]
maybe it related to `qatest1` issue, please verify it again
