### ISSUE TITLE
[Improvement] The best matching record need to prioritize to the top of searching result list

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1057]
OS: IOS / Android / Website
Device: Laptop / Mobile
Twake version:  2.4.0

### **Sample test data:** 
User account: qatest2:linagora.com

### **Step:** 
1, Click on new chat / new group chat
2, Input 'qatest2' in the search field

### **Actual:** 
System display all record which include 'qatest' and '2' but the best result as 'qatest2:linagora.com' is not sorted to the top of list

### **Expected:** 
System should priotized the best matching result to the top of the searching result

https://github.com/linagora/twake-on-matrix/assets/124866146/fb8530af-d40e-4641-9f42-4e339bafa296

**Comment by hoangdat** [comment]
Also search for matrixId: https://ci.linagora.com/publicgroup/oss/twake/tom-server/-/issues/92

**Comment by hoangdat** [comment]
fixed
