### ISSUE TITLE
Scale layout for Responsive Web app

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1065]
### 1, Macbook air M1
Serial number: C02K63NDQ6LR
Screen resolution: 2560x1600 pixels

**Chat list 1**
horizontally = 473px

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/6f0d96a4-bb7b-43d5-9fd8-3e8f5da4a552)

**Chat list 2**
vertically= 697px

<img width="1440" alt="Screenshot 2023-11-24 at 12 57 10" src="https://github.com/linagora/twake-on-matrix/assets/124866146/dca76df5-411e-43e3-a48c-13d485baa1f9">

**Chat room 1**
vertically = 697px

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/7c1d4adb-eff4-4dae-bbff-1042d011125c)

**Chat room 2**
horizontally = 1425px

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/d66e700e-3a30-4964-876a-067079a0d088)

**Twake screen 1**
vertically = 814px

<img width="1437" alt="Screenshot 2023-11-24 at 12 59 05" src="https://github.com/linagora/twake-on-matrix/assets/124866146/7d6e83f0-d8cf-4382-960f-dc5e34f9b8f7">

**Twake screen 2**
horizontally = 1439px

<img width="1440" alt="Screenshot 2023-11-24 at 12 49 02" src="https://github.com/linagora/twake-on-matrix/assets/124866146/0bf3b137-1a0e-45b9-8622-50eaac933900">

### 2, Asus B1400CI5

Serial number: C02K63NDQ6LR
Screen resolution: 1920x1080 pixels

**Chat list 1** 
vertically = 587px

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/56949019-82e8-48de-95e8-8245d47c8b4e)

**Chat list 2**
horizontally = 473px

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/843eb9db-5c1b-40c6-a0de-95d6627a7158)

**Chat room 1**
vertically = 587px

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/ab5489ec-f5e6-458a-ab35-ca2ddb111bad)

**Chat room 2**
horizontally = 1264px

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/669cde66-ad41-4d2c-a605-720361529ee0)

**Twake screen 1**
vertically = 603px

![image](https://github.com/linagora/twake-on-matrix/assets/124866146/c9aca8ad-af99-4f0a-baa3-63f45f397fcd)

**Twake screen 2**
horizontally = 1279px

![image](https://github.com/linagora/twake-on-matrix/assets/124866146/c4c2f7bf-d09d-4fff-b8b7-7b0237d5a6b5)

**Comment by nqhhdev** [comment]
### Decs
- Try to use lib: https://pub.dev/packages/flutter_screenutil
- How to configure when using lib for web, desktop, mobile
- How to apply it for padding, icon size, width, and height of widget.
- Apply it for all screens in style file.
### DoD
- [ ] Configure for all platforms
- [ ] Update body layout in AdaptiveScafoldRoute
- [ ] Update chat screen
- [ ] Update chat details and chat info
- [ ] Update settings
- [ ] Update Contacts
- [ ] Update forward
- [ ] Update share

**Comment by hoangdat** [comment]
Example: https://github.com/linagora/twake-on-matrix/pull/945

**Comment by shepilov** [comment]
@hoangdat @nqhhdev do you have a description or even a design in figma of the layout for the application? what will be the result of this task?

**Comment by hoangdat** [comment]
this is our investigate on the mechanism of Flutter rendering in different resolution screen.
Final decision: keep the original solution of Flutter.
