### ISSUE TITLE
Convert UID to Matrix ID

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#108]
### Desc:
- server name is defined in wellknown
- some API `lookup`, `lookup\match` only return `uid`
- we need to convert from `uid` to `matrix id` somewhere

### DoD:
- convert successfully

**Comment by sherlockvn** [comment]
should we use mxID from MatrixSDK or using this conversion ?

**Comment by hoangdat** [comment]
`address` field in response of `lookup/match`
