### ISSUE TITLE
[UI] [Only Web] Elements in Adding Member Dialog is broken

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1119]
OS: WEB only
Device: Laptop
Twake version:  2.4.8

### *Precondition: 
- User A,B,C in group chat

### **Step:** 
1, User click on Group infor
2, User click on Add Member

### **Actual:** 
Elements on Add member is brokent

### **Expected:** 
It's not broken

**WEB**

https://github.com/linagora/twake-on-matrix/assets/124866146/8d8bac2d-9f20-44f6-9905-c445df22c9f4

**Comment by hoangdat** [comment]
https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?type=design&node-id=12875-153651&mode=design&t=wAvu9D6LHSvRyIx0-4
