### ISSUE TITLE
[PREVIEW WEB - PART II] Send multiple images with caption in web

### ISSUE THREAD

**Issue by sherlockvn** [linagora/twake-on-matrix#1121]
### Desc:
- Use drop file to test, no need to wait for previous ticket, The images and the caption text need to send in order.
- max: 6
### Dod: 
- [ ] Change the interactor  `SendMediaOnWebWithCaptionInteractor` to support send multiple images with caption
- [ ] When the user click send button, the interactor should be executed then the dialog should immediately close and let the Chat screen handle any errors (done)
### To send multiple images with caption in order:
 - [ ] need to store placeholder of each image first, then send `fakeImageEvent` for each image, after that send `fakeMessageEvent`. Finally, use `sendFileEvent` to send each image in order, the last is `sendMessageEvent`. The implementation can be reference from 2 other interactors `SendImagesInteractor`.

**Comment by shepilov** [comment]
@sherlockvn is it already finished?
I see that caption works for multiple images but I don't see connection with this tech description
