### ISSUE TITLE
[Profile Info] Profile image looking blur -> Should improve image quality and user can click to view profile image in full screen

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1124]
OS: WEB / Android / IOS
Device: Laptop / Mobile
Twake version:  2.4.8

### *Precondition: 
- User A upload a profile image

### **Reproduce Step:** 
1, User A chat with User B
2, User B click to view Profile Info in Direct Chat with user A

### **Actual:** 
Profile image is looking blur and it's not clickable to view

### **Expected:** 
- Profile image is looking good quality
- User can click to view profile image

https://github.com/linagora/twake-on-matrix/assets/124866146/9bff3287-b49a-4c91-b618-0c1f5cff42b6

**Comment by hoangdat** [comment]
@tprudentova

**Comment by QuangHoang1210** [comment]
Passed on IOS 2.5.0
- for now - avatar is clearly but not able click to preview

![IMG_0424](https://github.com/linagora/twake-on-matrix/assets/124866146/4e95954a-a04f-4105-b1b0-b1a23d6ba844)

**Comment by tprudentova** [comment]
@hoangdat is this a feature that we can't preview the profile image?
