### ISSUE TITLE
[Profile Info] Improve design for MatrixID + UserID displaying

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1125]
OS: WEB / Android / IOS
Device: Laptop / Mobile
Twake version:  2.4.8

### *Precondition: 
- User A and User B in direct chat

### **Reproduce Step:** 
1, User A click to view profile info of user B

### **Actual:** 
MatrixID and User ID section is feeling confuse to user.

### **Expected:** 
Need to redesign it.

### **Suggesstion:** 
- MatrixID and User ID will place in one border
- There is existed Small Label for each of them

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/9f1457fb-501a-44ab-80c7-fb25373cb865)

**Comment by hoangdat** [comment]
- [ ] put matrix id to the box too
