### ISSUE TITLE
Preview + Send multiple files in web in `Sendfiledialog`

### ISSUE THREAD

**Issue by sherlockvn** [linagora/twake-on-matrix#1127]
### Desc:
- Build the preview files in `SendFileDialog` widget
-  you should test with `DROP` multiple files, `ADD` multiple files
- `SendFileDialog` with a list of files will appear when at least one of the files are not an image or video.
- The files will be sent in order
- The maximum file is 6, When over 6, don't open `SendFileDialog`, but notify user with a snackbar "The maximum files when sending is 6"
- Files is sent in bytes

How to send multiple files:
- Currently it only support send one file in `SendFileOnWebInteractor`,we need to change it to support multiple files
- Firstly, create each transactionID for each file using `client.generateUniqueTransactionId()`
- Secondly, use `sendFakeImageEvent` with each transactionID and file information(size, name, extension) for each file in order
- Next, create a transactionID called messageID for caption, use `sendFakeMessage` with messageID created and the caption
- Then, send files using `sendFileOnWebEvent` in order with each transactionID for each files, finally, send caption using `sendMessageContent` with messageID
- Reference: `SendMediaOnWebWithCaptionInteractor` interactor

### Design:
[design link](https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?type=design&node-id=16871-7506&mode=dev)
[icon link](https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?type=design&node-id=6497-117123&mode=dev)

![Image](https://github.com/linagora/twake-on-matrix/assets/43041967/59ba5fbf-8da6-47f9-bd37-0a876ccae389)

### DOD:
- [x] build files, image, audio and video list tile item
- [x] Show the size, extension, and name of the file.
- [x] Display list of files using `ListView`(When click to each file in ListView, it's will not open the file)
- [x] when preview multiple files, the max height is 320pixel, the width is 318pixel even if the name of file is short, the maximum line is 2 if name is too long, if more than 2 line, end with ...
- [x] Reuse the old `SendFileDialog` as much as possible (change the header text to send x files, change PageView to ListView)
- [x] Handle add new files but if total files more than maximum files, warn the user - but no need to keep the current scroll of the list
- [x] Refactor interactor `SendFileOnWebInteractor` to support send multiples files in order

**Comment by QuangHoang1210** [comment]
Passed

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/7356a52e-e115-4496-9ef4-cd5cd133ff8a)
