### ISSUE TITLE
[Profile Info] Copy to Clipboard toast message is displayed twice on Android only

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1128]
OS: Android only
Device: Mobile
Twake version:  2.4.8

### *Precondition: 
- User A and User B in direct chat

### **Reproduce Step:** 
1, User A click to view User B profile Info
2, User A click copy icon beside MatrixID or UserID

### **Actual:** 
Copy clipboard is displayed twice

### **Expected:** 
It should only display one

https://github.com/linagora/twake-on-matrix/assets/124866146/027e7e0f-c773-4d47-a262-b53bc1cff66c

**Comment by QuangHoang1210** [comment]
Reopened -> Still happen on 2.4.10 ANDROID only

https://github.com/linagora/twake-on-matrix/assets/124866146/333dbef7-e0f2-442a-b74b-c39371ff80d7

**Comment by imGok** [comment]
@nqhhdev @sherlockvn hi, can you check it please ? I don't have the bug on simulator and don't have android real device

https://github.com/linagora/twake-on-matrix/assets/48354990/8bb2b6dc-cf15-46a8-bdfc-ebab312cb00a

**Comment by shepilov** [comment]
@QuangHoang1210 could you retest it please?
