### ISSUE TITLE
[Profile Info] The elements in sharing media list is overlapping on WEB only

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1131]
OS: WEB only
Device: Laptop
Twake version:  2.4.8

### *Precondition: 
- User A and User B in direct chat
- User A send User B some videos /images

### **Reproduce Step:** 
1, User A click to view User B profile Info
2, User A click share media

### **Actual:** 
- Profile info tab is looking smaller than figma design
- Share media list elements are overlapping

### **Expected:** 
It should be correct as design

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/5a320e37-d91b-4ed6-b50d-ab53799273c9)

**Comment by imGok** [comment]
can't reproduce the bug can you give me more details please ?

![Image](https://github.com/linagora/twake-on-matrix/assets/48354990/35dc6f04-11f9-4c3a-a5e6-1e70912dbd1d)

**Comment by QuangHoang1210** [comment]
@imGok im
 please follow up the reproduce step.
Sending sequence:
1, User send 1st image
2, User send a video
3, User send 2nd image

**Comment by QuangHoang1210** [comment]
Fixed 2.4.10



![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/9a3f83c2-4754-4d29-92ed-69df042895df)
