### ISSUE TITLE
[Bug][Mobile] Wrong navigation when opening an image

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1138]
1. Go do direct chat
2. Open shared media 
3. Open a picture 
4. Go back 
5. You appear in chat list instead of direct chat
Expectation -> I only go 1 step back and appear in the direct chat

https://github.com/linagora/twake-on-matrix/assets/97684890/44a65181-3f3f-407a-831a-dd7823b9efd1

**Comment by sherlockvn** [comment]
https://github.com/linagora/twake-on-matrix/pull/1327
