### ISSUE TITLE
[Bug] Clicking X while uploading an image selects the message

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1148]
1. Go to chat, select Attach image 
2. Choose an image, click Send 
3. Click X while the image is still uploading 
4. The message is selected, upload isn't canceled
Expectation -> Clicking X cancels the upload

https://github.com/linagora/twake-on-matrix/assets/97684890/2e7637bb-d46a-4e35-b212-c5ecf9f99f2c

**Comment by imGok** [comment]
cancel image uploading feature is not implemented yet

**Comment by sherlockvn** [comment]
### Dod:
- [ ] Cancel uploading file if have any
- [ ] Remove FileSending event from local database
