### ISSUE TITLE
[Bug] Cannot search by email on chat list screen

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1152]
1. Open tab with chat list
2. Start entering some existing email to the search bar
3. Search isn't performed 
Expectation -> I can search by email 
NB: Search by email works fine in Contacts tab

https://github.com/linagora/twake-on-matrix/assets/97684890/bd84f822-97d5-49a2-bc15-925e5973fc2e

**Comment by QuangHoang1210** [comment]
Working well on both mobile (IOS.Android) + web 2.4.15

https://github.com/linagora/twake-on-matrix/assets/124866146/cc5bb122-b158-4a7a-a712-d687b7934472

**Comment by tprudentova** [comment]
Please check the search bar in the Chats tab. Still can reproduce

https://github.com/linagora/twake-on-matrix/assets/97684890/6be2f029-a5e4-4637-b4c6-0b5bd182af25
