### ISSUE TITLE
[Bug] Sharing image by Twake Chat doesn't always work

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1155]
1. Go to your device's gallery 
2. Open an image, select Share by Twake Chat 
3. Sometimes (not always) the "sharing screen" doesn't open

https://github.com/linagora/twake-on-matrix/assets/97684890/3610e2fb-e4b5-414e-b386-31f624aa952e

**Comment by sherlockvn** [comment]
Please add more information about this case:
- Which device do you use ?
- Which app do you use to share image ?
- Is Twake app is in background ?
