### ISSUE TITLE
[Improvement] Remove Emote settings

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1160]
Right now this button leads to a non-existent page 
<img width="364" alt="Screenshot 2023-12-18 at 10 28 06" src="https://github.com/linagora/twake-on-matrix/assets/97684890/4e9ad5a6-036f-4db9-826a-e2fc71b7fa96">
<img width="363" alt="Screenshot 2023-12-18 at 10 28 11" src="https://github.com/linagora/twake-on-matrix/assets/97684890/0c8aff45-eb64-44ab-a531-8d92655faabf">

**Comment by tprudentova** [comment]
Same for button Chat folders in settings

**Comment by hoangdat** [comment]
duplicated with #1440
