### ISSUE TITLE
Can not use Ctrl+V or Right Click -> Paste in Firefox

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#1161]
`super_clipboard` package now allow to listen pasteEvent which are cmd+V or paste in default browser context menu (these are only ways to read data in the clipboard). 
- [ ] add cmd+V listener and default browser context menu
- [ ] remove the custom context menu in composer and custom cmd+V in input bar
- [ ] find a way to enable default context menu in Composer in web
- [ ] Find a way to copy text/image in message

https://github.com/superlistapp/super_native_extensions/issues/258

**Comment by sherlockvn** [comment]
Right now, we disable default context menu in web, because of we have a custom menu in chat list when right click using mouse.

**Comment by sherlockvn** [comment]
Propose: remove the right click in chat list item and use the ... when hover to chat list item, then enable default contextMenu. In other screen, like pinned messages screen, we can enable again, and disable when dispose

**Comment by sherlockvn** [comment]
Not care about the context menu for now, implemented the Cmd/ctrl + C, V first
