### ISSUE TITLE
[Bug] Status of a message in DM isn't updated correctly 

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1165]
See the screenshot - the message has already been replied to, but the status is still as if it was unread 

<img width="379" alt="Screenshot 2023-12-19 at 13 29 36" src="https://github.com/linagora/twake-on-matrix/assets/97684890/2e0014a2-2445-478f-b74d-94b30f6e343b">
<img width="1280" alt="Screenshot 2023-12-19 at 13 26 32" src="https://github.com/linagora/twake-on-matrix/assets/97684890/a2dfe563-02d0-4034-9e59-4d8fe68ef6d5">

**Comment by hoangdat** [comment]
Set read marker:
- [ ] `onChanged` composer 
- [ ] during `getTimeline` ??? 
- [ ] after 5s from open chat screen
