### ISSUE TITLE
The name in user profile details will be cut off and we need to re-design profile details dialog both Website + Mobile

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1168]
OS: WEB / IOS / ANDROID
Device: LAPTOP / MOBILE
Twake version:  2.4.8

### **Precondition:** 
- Sender is A
- Receiver is B
- A set long profile name

### **Reproduce Step:** 
1, A sent a message to B
2, B mentioned A in chat '@A'
3, B click on A tag highlight name to view A profile

### **Actual:** 
- Profile dialog will be displayed
- Name is cut off both WEB+MOBILE view
- Dialog design is not good on WEBSITE view

### **Expected:** 
- Should prevent user to set long name
- Name is not cut off
- Redesign profile dialog

**WEB**

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/a5db52d2-6515-4612-850b-e56642573323)

**ANDROID**

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/3b27c7bb-9adf-4241-899f-c9f049980773)

**IOS**

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/ec09f6db-2363-4429-9a31-602a64214c6e)

**Comment by hoangdat** [comment]
- [ ] show full long name
- [ ] click tag name:
  - if in direct chat -> open profile info
  - if in group chat -> open direct chat
