### ISSUE TITLE
[PREVIEW WEB] support files with video, image when click to `+` in composer

### ISSUE THREAD

**Issue by sherlockvn** [linagora/twake-on-matrix#1170]
### Desc:
- When click to + button in web, if user chooses more than 1 file, show a list of files, if it contains image or video, show it as a file also
- Assume that `SendFileDialog` have support preview multiple files in web, now if files chosen is images and videos, show the `SendFileDialog` with list of files also
- The `SendFileOnWebInteractor` have support send multiple files, we can reuse it

### Dod:
- [ ] Update the condition when add files which are images and videos

**Comment by hoangdat** [comment]
- [ ] video icon -> thumbnail in preview list
- [ ] image icon -> thumbnail in preview list
