### ISSUE TITLE
[Bug] Cannot move in message composer with arrows

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1177]
When in message composer, it is impossible to use keyboard arrows UP and DOWN to move through text. 

NB: Arrows LEFT and RIGHT work fine

https://github.com/linagora/twake-on-matrix/assets/97684890/eeb8ee57-183e-4458-afd7-0336af4e4de0

**Comment by hoangdat** [comment]
IMO, it is not a MUST for M0. Not a big deal for user to use the app without it. Move it to M1 @shepilov
