### ISSUE TITLE
[WEB+ANDROID] Missing tag highlight once user send a message which included tag name and url

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1183]
OS: WEB / IOS / ANDROID
Device: LAPTOP / MOBILE
Twake version:  2.4.8

### **Precondition:** 
- Sender is A
- Receiver is B

### **Reproduce Step:** 
1, A mentioned B '@B' and input an url in composer
2, A sent it to B

### **Actual:** 
- Both A and B cannot see the highlight tag name which be mentioned

### **Expected:** 
- Both A and B will see the highlight tag name which be mentioned

**WEB**

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/2bb135d2-6e1f-4fe4-ac2d-483b7eabd90b)

**ANDROID**

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/12bf1f29-9257-4101-bee2-93040f28a03c)

**Comment by hoangdat** [comment]
not work with the case `Tag + link (which have url preview)`
