### ISSUE TITLE
[Android] [UX] User hard to understand how can download the file which have extension that cannot preview

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1184]
OS: ANDROID
Device: Mobile
Twake version:  2.4.8

### **Reproduce Step:** 
1, User A click to view a chat
2, User A send an file that cannot open to preview <example: .json >
3, User A tap to open the file

### **Actual:** 
- System required user to select one application in suggestion list to open the file
- User can select File application to open and save the file but feeling not good UX

### **Expected:** 
- Should have download button or something else to indicate user can download that file

https://github.com/linagora/twake-on-matrix/assets/124866146/dda30c77-5745-44af-aa9b-81d48f41ae21

**Comment by hoangdat** [comment]
please compare with other app, especially Telegram

**Comment by tprudentova** [comment]
> @tprudentova do we have a design for longtap menu or something similar and "material"?

@shepilov found it for web 
https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?type=design&node-id=12772%3A62740&mode=design&t=cD8nUMVGLd251ZvK-1
