### ISSUE TITLE
[IOS] [ANDROID] [WEB] Cannot download video

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1185]
OS: ANDROID / IOS / WEB
Device: Mobile / MOBILE
Twake version:  2.4.8

### **Reproduce Step:** 
1, User A click to view a chat
2, User A send video to user B
3, User A / B click to view video

### **Actual:** 
- Loading video successfully
- Video can play
- But missing download / share icon in video previewer

### **Expected:** 
- Have download / share icon same with image previewer

**IOS**

https://github.com/linagora/twake-on-matrix/assets/124866146/6422f99b-24d8-4828-a696-59ac11ec736e

**ANDROID**

https://github.com/linagora/twake-on-matrix/assets/124866146/2fc63dad-c131-4793-8858-806b7ce7b2ee

**Comment by hoangdat** [comment]
please compare with other app, Whatapps and Telegram
