### ISSUE TITLE
[Question] No permission when do specific login at 2 browser

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#1186]
OS: WEB
Device: LAPTOP
Twake version:  2.4.8

### **Reproduce Step:** 
1, User A access beta.twake.app at browser 1
2, User B access beta.twake.app at browser 2
3, User A input home sever and go to login page
4, User B input home sever and go to login page
5, User A input correctly username/password 
6, User B input correctly username/password
7, User A click login
8, User B click login

### **Actual:** 
- Cannot login at one browser
- Other browser can login but displayed weird notification "NO PERMISSION"

### **Expected:** 
- Can login same account in different browser at the same time smoothly

**Comment by hoangdat** [comment]
@QuangHoang1210 please verify again, I think your test is not isolated.

**Comment by QuangHoang1210** [comment]
### Retest again on 2.4.15

**1, Login in same type of browser but incognito tab** **-> PASSED**

https://github.com/linagora/twake-on-matrix/assets/124866146/e4bc690e-8c69-4b9e-a31f-efa206bb70c2
