### ISSUE TITLE
[SIGNUP] OTP is 500 internal sever error - user cannot signup successfully

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1194]
OS: Android / IOS / WEB
Device: Mobile / laptop
Twake version:  

### **Reproduce Step:** 
1, User access to: register site
2, User input all correct field
3, User input phone number without nation code +84 (example: 0975110096) 
4, User try to verify phone number

### **Actual:** 
- OTP API getting 500 error
- Cannot finish signup flow

### **Expected:** 
- Can get OTP and finish sign up flow

**MOBILE**

https://github.com/linagora/twake-on-matrix/assets/124866146/93e29544-6a1a-43f2-a4a7-1c74597a83ba

**WEB**

https://github.com/linagora/twake-on-matrix/assets/124866146/28dee664-b1f9-4ffd-83e8-669061a9fe1a

**Additional**:

https://github.com/linagora/twake-on-matrix/assets/124866146/47ae09a7-ae54-49a5-b8f5-567ffb0ea359

**Comment by QuangHoang1210** [comment]
Checking sms otp with other region

<img width="1512" alt="Screenshot 2024-01-29 at 1 41 43 AM" src="https://github.com/linagora/twake-on-matrix/assets/124866146/2e1716df-06c8-4851-9654-867e34beed59">

**Comment by hoangdat** [comment]
resolved in other project
