### ISSUE TITLE
[SIGNUP] Signup Header of modal is wrong font size

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1205]
OS: WEB 
Browser: - Chrome
Device: Laptop
Twake version:  register

### **Reproduce Step:** 
1, User access to: register
2, Click on Signup tab

### **Actual:** 
- font size: 30px

### **Expected:** 
- font size: 28px

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/80b86ed8-eb00-4047-b44c-367720e12f90)

**Comment by guimard** [comment]
Please stop using real addresses in public bug reports
