### ISSUE TITLE
[SIGNUP] Signup button background is wrong color

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1210]
OS: WEB only 
Browser: - Chrome
Device: Laptop

### **Reproduce Step:** 
1, User access to: Twake Registration

### **Actual:** 
- Signup button background is wrong color: #1C1B1F1F

### **Expected:** 
- Should be: #1C1B1F 12%

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/29d45ef5-b7dc-49a4-8982-4cab1f2a87ea)

**Figma**

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/01da240f-8611-418a-a4d5-830952c1dae3)

**Comment by rezk2ll** [comment]
already the case rgba(28, 27, 31, 0.12)
