### ISSUE TITLE
[WEB/Android/IOS] User name is not displaying immediately when user already changed it in profile

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1267]
OS: Android/ IOS/WEB
Device: Mobile / LAPTOP
Twake version:  2.4.10

### **Precondition:** 
User A login on both mobile and website on laptop at the same time

### **Reproduce Step:** 
1, User A have profile name: Nhat Quang Nguyen
2, User A create group chat with user B,C,D on mobile
3, User A chat in group chat on Mobile
4, User A changed profile name to "Nhat Quang Nguyen BỤI ĐỜI CHỢ LỚN"

### **Actual:** 
- User B,C,D still see old name of user A 
- It only be updated when user A send a new chat

### **Expected:** 
Should updated profile name immediately once user changed

https://github.com/linagora/twake-on-matrix/assets/124866146/c5f99bf8-a93b-4be0-bfa3-8f5574dd32d1

**Comment by hoangdat** [comment]
please verify it

**Comment by QuangHoang1210** [comment]
**For Group Chat:**
1- Name in Group chat message <sender name/ receiver name> is updated -> PASSED
2- Name in Chat list is updated -> PASSED

**For Direct Chat:** -> Ticket: https://github.com/linagora/twake-on-matrix/issues/1428
1- Name in Direct chat message <sender name/ receiver name> is updated -> FAILED
2- Name in Chat list is updated -> FAILED
