### ISSUE TITLE
[Feedback] Caption for image and files doesn't work, you can't just enter anything in the text input

### ISSUE THREAD

**Issue by shepilov** [linagora/twake-on-matrix#1274]
Safari, Chrome
Macos

For image and files, nomatter you want to upload

![Image](https://github.com/linagora/twake-on-matrix/assets/14924963/b7cd6240-685b-4857-a975-ecddf8e2a84a)

**Comment by QuangHoang1210** [comment]
Retest -> 
Happen only on Safari MAC OS:
-- User cannot input anything in Enter a caption field

https://github.com/linagora/twake-on-matrix/assets/124866146/909ed403-b7c3-46e2-8413-5282b406235d

-- Working well on Chrome on MAC OS and window 

https://github.com/linagora/twake-on-matrix/assets/124866146/513e529c-dd09-4aa7-b26c-fe1d85e0e7aa

@hoangdat  @nqhhdev @sherlockvn
