### ISSUE TITLE
[FIREFOX ONLY] Using keyboard to move cursor along side with composer - but don't have moving animation on Firefox only

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#1275]
Cursor not moving only on firefox

**Firefox -> failed <Cannot see animation of moving cursor**

https://github.com/linagora/twake-on-matrix/assets/124866146/de898c33-87ce-4aca-9ab4-bfd323a0fa62

**Comment by QuangHoang1210** [comment]
**Safari -> passed**

https://github.com/linagora/twake-on-matrix/assets/124866146/30e10ca0-16d1-4ea9-ab2e-b95213bbfa7f


**Firefox -> failed <Cannot see animation of moving cursor**

https://github.com/linagora/twake-on-matrix/assets/124866146/de898c33-87ce-4aca-9ab4-bfd323a0fa62


**Chrome -> passed**

https://github.com/linagora/twake-on-matrix/assets/124866146/0690be63-e1d8-425a-b72a-1415186a1854
