### ISSUE TITLE
[UX] [Improvement] Should remove the button which not useful in Edit Group Information

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1279]
OS: WEB ONLY
Device:  LAPTOP
Browser: Chrome / Safari
Twake version:  2.4.10

### **Precondition:** 
- User A , B , C in group chat
- Group chat don't have avatar image

### **Reproduce Step:** 
1, User click on group information
2, User click on edit button
3, User click on group image

### **Actual:** 
There is options dropdown list but included Remove Image option

### **Expected:** 
Should remove the Option Remove Image here cause there is no image yet

**WEB**

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/275bc288-3974-4c19-aa0a-141ed43eb41a)

**IOS**

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/68eb9c7b-4e2c-4e58-bd7c-58974e885c8c)

**ANDROID**

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/7edf9a65-1e56-432c-9a9d-dc5ea714a825)

**Comment by QuangHoang1210** [comment]
IOS - FAILED

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/443d2291-5d55-4689-87af-61d028411415)

ANDROID - FAILED

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/08627620-1d99-4fc6-9070-623b1271431f)

WEBPC - FAILED

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/104bfad3-5ccb-4454-b769-b3274b4fe121)

**Comment by nqhhdev** [comment]
I fixed it on #1436 

Pls wait for new release version and test it again
