### ISSUE TITLE
[UX] The edit group information will be disappeared when user Restore Down / Maximize the window browser

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1281]
OS: WEB ONLY
Device:  LAPTOP
Browser: Chrome / Safari / Firefox
Twake version:  2.4.10

### **Precondition:** 
- User A , B , C in group chat
- The window browser is already Maximize

### **Reproduce Step:** 
1, User click on group information
2, User click on edit button
3, User write long content in description
4, User Restore Down the window 

### **Actual:** 
The content at step 3 is disappeared

### **Expected:** 
Should be keep the edit mode and content is save temporary.
-- Because in some case user will compare with other template document to write Description / Group Name input field. So if they do Restore Down or Maximize the browser window again then they lost all what they did

**Noted**: Please take care in both case:
- [ ]  Maximize -> Restore Down browser window
- [ ] Restore Down browser window -> Maximize

https://github.com/linagora/twake-on-matrix/assets/124866146/c54c908b-e19a-415c-bcfd-0b39647cbcbb

**Comment by shepilov** [comment]
looks like working
