### ISSUE TITLE
[Improvement] Make the Send button inactive when the composer is empty

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1295]
Would be nice to make this button inactive (grey) until user types something in the composer
<img width="649" alt="Screenshot 2024-01-08 at 13 26 48" src="https://github.com/linagora/twake-on-matrix/assets/97684890/3b80bd49-836a-4bfe-a14d-b80f657a2bd4">

**Comment by hoangdat** [comment]
<img width="666" alt="image" src="https://github.com/linagora/twake-on-matrix/assets/6462404/444a57bc-36e9-47e9-87d5-9f2079645fc9">
