### ISSUE TITLE
[Bug] Message in chat is only marked as read when I use the jump button

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1296]
Expectation: the message is marked as unread when I open the chat

https://github.com/linagora/twake-on-matrix/assets/97684890/19f83204-6ac3-4721-9878-3c53fed80fa4

**Comment by hoangdat** [comment]
- [ ] 10s from the time Chat is display

**Comment by hoangdat** [comment]
changed the way to apply it, will release in >= v2.4.16. but maybe have some side effect if you have 100 unread messages.
