### ISSUE TITLE
[Design review] Make the width of composer match the width of message bubbles

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1297]
<img width="701" alt="Screenshot 2024-01-08 at 13 37 48" src="https://github.com/linagora/twake-on-matrix/assets/97684890/427e020f-bf33-473b-aeeb-41826eb5fcb6">

**Comment by hoangdat** [comment]
- [ ] padding top for composer
- [ ] reduce gap between quote and input field of composer
- [ ] adjust horizontal padding for bubble list

**Comment by QuangHoang1210** [comment]
Passed 2.4.15 <firefox/safari/chrome>
