### ISSUE TITLE
[Bug] Clicking the Pencil button gives error 404

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1299]
When you're in a "Not in a chat" screen and click the Pencil icon, a 404 error is displayed. 
<img width="772" alt="Screenshot 2024-01-08 at 13 55 40" src="https://github.com/linagora/twake-on-matrix/assets/97684890/1cbd5aee-587b-4383-84c2-b147d4536edb">

Expectation: maybe the same action as clicking on the Create button? This one
<img width="1280" alt="Screenshot 2024-01-08 at 13 55 54" src="https://github.com/linagora/twake-on-matrix/assets/97684890/be72f1ef-3782-4fc5-a4c4-521ff70a5022">

**Comment by hoangdat** [comment]
@QuangHoang1210
