### ISSUE TITLE
[Composer] Image picker in composer

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#130]
### Desc:
- User Story:
```
As a user, I want to send image to recipients
And I want to pick a image in my gallery directly in composer
```

- Dependencies: https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?type=design&node-id=8262-146951&t=mKW1uJImrpInpZV4-4

- Design: https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?type=design&node-id=8262-146804&t=dPpxFvBuTF3ErODf-4

![Image](https://user-images.githubusercontent.com/6462404/243286653-d48e589b-e782-417a-b38c-2745d7bff73f.png)

### DoD:
- [ ] Bottom sheet gallery picker (no Gallery, Document, Location, Contact button)
- [x] Lazy load all user gallery
- [x] Multiple selection

**Comment by QuangHoang1210** [comment]
Passed
