### ISSUE TITLE
[Design review] Add Bio field to the user profile page

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1300]
<img width="452" alt="Screenshot 2024-01-08 at 14 23 50" src="https://github.com/linagora/twake-on-matrix/assets/97684890/2ff1c529-acf0-459e-a5a9-fb972bac64e3">

**Comment by hoangdat** [comment]
what information you want to add? @tprudentova

**Comment by tprudentova** [comment]
<img width="624" alt="Screenshot 2024-01-10 at 11 32 57" src="https://github.com/linagora/twake-on-matrix/assets/97684890/73e5bae9-f6ae-4a85-bfd4-e8048cb72a75">

I think it's about this thingie in the design files here 

https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?type=design&node-id=10521%3A156199&mode=design&t=4PZEUdWNRJgEkwPO-1
