### ISSUE TITLE
[Bug] Display "No results found" message in search

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1302]
1. Click Create direct message 
2. In search bar enter an inexistent request
3. No "No results found" message is displayed, just empty fields 

<img width="611" alt="Screenshot 2024-01-08 at 14 30 35" src="https://github.com/linagora/twake-on-matrix/assets/97684890/77583264-b146-4fdc-8dd0-4aad3bab58ae">

**Comment by hoangdat** [comment]
### DoD:
- [ ] search in create chat (direct + group)
- [ ] global search

**Comment by hoangdat** [comment]
design: https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?type=design&node-id=15916-14472&mode=design&t=ggiHkPOmMGdjZ2kg-4

**Comment by tprudentova** [comment]
<img width="483" alt="Screenshot 2024-01-24 at 14 16 41" src="https://github.com/linagora/twake-on-matrix/assets/97684890/7b3140c4-259a-48a5-8edf-03aad02ffe22">

Still no message

**Comment by QuangHoang1210** [comment]
**No searching result in new group chat -> Passed**

https://github.com/linagora/twake-on-matrix/assets/124866146/d5857f1b-8472-42f9-b49c-5fb2bf8e9810


**No searching result in New direct chat -> Failed**

https://github.com/linagora/twake-on-matrix/assets/124866146/2a3d57af-8498-4072-b2a5-0a298b9d7031


both mobile + web

**Comment by nqhhdev** [comment]
> **No searching result in new group chat -> Passed**
> 
>  Screen.Recording.2024-01-29.at.12.20.14.AM.mov 
> **No searching result in New direct chat -> Failed**
> 
>  Screen.Recording.2024-01-29.at.12.20.29.AM.mov 
> both mobile + web

Improve for no search result in direct/group in this ticket 

- https://github.com/linagora/twake-on-matrix/issues/1411
