### ISSUE TITLE
[Bug] Unread messages block isn't displayed correctly

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1303]
<img width="748" alt="Screenshot 2024-01-08 at 14 41 34" src="https://github.com/linagora/twake-on-matrix/assets/97684890/bc9e055a-a96e-450a-bd79-448f6b0e05cf">

**Comment by hoangdat** [comment]
Not get your point, please compare with Telegram

**Comment by shepilov** [comment]
@tprudentova this line is always there in Telegram also, what is the expected behavior for you?

**Comment by tprudentova** [comment]
> @tprudentova this line is always there in Telegram also, what is the expected behavior for you?

It's about the "Unread messages block". My own messages cannot be displayed in the "Unread messages" block, I think
