### ISSUE TITLE
[Bug] Old user profile displayed when I click on the user name in member list

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1305]
1. Go to a group chat 
2. Clcik on chat info 
3. Click on some user in member list 
4. Old profile screen is displayed 
Expectation -> New pretty user profile screen is displayed

https://github.com/linagora/twake-on-matrix/assets/97684890/62b7214d-055d-48a8-b872-91cdc9b1e1cc

**Comment by hoangdat** [comment]
Because, this profile also include the action for user in a group chat: ban, kick, ....
Will create ticker on design board for changing the UI.

**Comment by hoangdat** [comment]
@tprudentova please update the US + Design

**Comment by hoangdat** [comment]
fixed in new version v2.5.3
