### ISSUE TITLE
[Routing] Some routing issues in Twake Chat

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1306]
1.	 Open a chat -> Switch tab to Contacts -> Select a contact -> Click Back -> Empty page opens 
Expectation: I go back to the chat that was opened (previous step for main section of the screen)

https://github.com/linagora/twake-on-matrix/assets/97684890/30a76f0f-20cf-412d-ac5b-853d37c99a42

2.	Open Settings tab -> Profile info -> Switch tab to Contacts -≥ Select a contact -> Click Back -> Empty page opens 
Expectation: I go back to profile info (previous step for main section of the screen)

https://github.com/linagora/twake-on-matrix/assets/97684890/ec1e884b-39cf-4068-8823-2f6cbc12fcb4

3.	Button Back exists for empty direct chats but doesn’t exist for direct chats with message history. We probably should unify it in some way

https://github.com/linagora/twake-on-matrix/assets/97684890/92832104-5745-475f-9b52-cce03b0439f0

4. Not a routing issue, but a beauty issue connected with routing :D We should have the "Back" button on the same level on these screens, so that user can click on them one by one without the need to move cursor

https://github.com/linagora/twake-on-matrix/assets/97684890/025baaa6-41cf-4621-9038-df5d8e9201f0

**Comment by hoangdat** [comment]
1 + 2 + 3. Remove back button in Draft Chat
4. header height of `New group Chat` is wrong
