### ISSUE TITLE
[Composer] Send ONE image without caption

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#131]
### Desc:

- `As a user, I want to send ONE image to recipients`

- Design: 
### DoD:
- [x] each image in each message bubble
- [ ] image is sent without caption

![Image](https://github.com/linagora/twake-on-matrix/assets/6462404/601def62-975a-4671-bd46-a1c3cb62745b)

**Comment by sherlockvn** [comment]
After a lot of debugs, let recap what i have debug: 
- To be able to send an image message, first call `sendFileEvent()` method

**Comment by QuangHoang1210** [comment]
Passed
