### ISSUE TITLE
[Bug] Wrong events

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1312]
The events on the picture are "X created chat" and then "X joined the chat". If someone created a chat, they can't join it as well, it should be either of these events

<img width="444" alt="Screenshot 2024-01-09 at 10 04 36" src="https://github.com/linagora/twake-on-matrix/assets/97684890/3a8a171c-54f0-427f-bd46-7d305568b2f7">

**Comment by QuangHoang1210** [comment]
Passed all platform

![IMG_0075](https://github.com/linagora/twake-on-matrix/assets/124866146/da795f7e-6f2d-4e4e-be10-ad9bdbfbb7e8)
