### ISSUE TITLE
[Improvement] Improve fonts on mobile

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1313]
Unify size of fonts and make bullets a bit smaller

<img width="446" alt="Screenshot 2024-01-09 at 10 05 13" src="https://github.com/linagora/twake-on-matrix/assets/97684890/2ecb0b57-a8c9-4ae9-b595-e9dd24313f4d">

### DoD:
- [ ] make sure all kind of bubbles have `Inter` font
- [ ] make sure all event in message have `Inter` font

**Comment by QuangHoang1210** [comment]
Missing bubble

![IMG_0075](https://github.com/linagora/twake-on-matrix/assets/124866146/f03f6e00-6ce4-4238-904b-cf57e9cffc49)
