### ISSUE TITLE
[Improvement] Change date format from dd/mm/yyyy to dd/mm/yy

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1314]
<img width="448" alt="Screenshot 2024-01-09 at 10 06 27" src="https://github.com/linagora/twake-on-matrix/assets/97684890/3c31a1aa-83f2-49ac-8aa0-9532af197cea">

**Comment by QuangHoang1210** [comment]
Retest on 2.4.15 -> failed

Actual: mm/dd/yy
Expected: dd/mm/yy

![photo_2024-01-28 23 48 27](https://github.com/linagora/twake-on-matrix/assets/124866146/28e90de7-a93f-44b3-8b89-3e5be53fdd71)

![photo_2024-01-28 23 48 25](https://github.com/linagora/twake-on-matrix/assets/124866146/8073b527-99cd-40f8-912a-e1d41852c4e1)

**Comment by QuangHoang1210** [comment]
Actual: mm/dd/yy
Exơected: mm/dd/yy

<img width="335" alt="Screenshot 2024-02-16 at 7 40 27 AM" src="https://github.com/linagora/twake-on-matrix/assets/124866146/79b82278-4fd2-4c20-b514-6753207e4940">

@nqhhdev @hoangdat @sherlockvn
