### ISSUE TITLE
reduce size of bullet in message bubble

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#1328]
### Desc

![Image](https://github.com/linagora/twake-on-matrix/assets/6462404/5a7986bc-698f-4174-b423-f62ff8b75e14)

### DoD:
- [ ] same as 

![Image](https://github.com/linagora/twake-on-matrix/assets/6462404/02981c8a-e414-4851-930c-9a371e15602b)

![Image](https://github.com/linagora/twake-on-matrix/assets/6462404/0ecdb14b-c945-449f-baf1-02acaa3eee20)

**Comment by QuangHoang1210** [comment]
Passed

<img width="1312" alt="Screenshot 2024-02-16 at 7 32 54 AM" src="https://github.com/linagora/twake-on-matrix/assets/124866146/83d95de8-9396-4537-8acf-28f7bd34ffc5">
