### ISSUE TITLE
[Bug] Empty greeting pop-up

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1332]
1. Open Contacts tab 
2. Open a chat with someone you've never chatted before 
3. The greeting pop-up sometimes looks like this. If you click on it, it becomes normal  

![06BD2566-603D-4AA5-8531-10BEB7C03E36_L0_001_1704969297 215709_o_IMG_0483](https://github.com/linagora/twake-on-matrix/assets/97684890/f22cdb59-0a7e-4df4-b58d-708b799c23e0)
![433DD07A-B496-4824-9322-3E722AA911AC_L0_001_1704969314 663777_o_IMG_0484](https://github.com/linagora/twake-on-matrix/assets/97684890/c356dfbd-a564-45fa-b6b0-d8d7fbbdeb58)

**Comment by tprudentova** [comment]
Browser: Opera

**Comment by imGok** [comment]
Hi @tprudentova can you provide more informations please ? I can't see any bug


Video made with Opera too 

https://github.com/linagora/twake-on-matrix/assets/48354990/6918d662-1a9a-4706-ac75-b319776d66da
