### ISSUE TITLE
[Bug] Cannot mark chat as read

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1333]
Sometimes it's impossible to mark chat with unread messages as read 

https://github.com/linagora/twake-on-matrix/assets/97684890/9de0bd1c-3c7d-443a-ab80-b6dd4d211418

**Comment by tprudentova** [comment]
OS: Android

**Comment by sherlockvn** [comment]
The unread messages now is mark read after 5s in chat


https://github.com/linagora/twake-on-matrix/assets/43041967/bd76f98a-77c7-4c61-a307-0d1eb9c1c8c0

**Comment by tprudentova** [comment]
@sherlockvn If I have unread messages inside a chat, I still cannot manually mark it as read through action menu

https://github.com/linagora/twake-on-matrix/assets/97684890/a80fb84a-6ff3-4427-b07b-104e51deb662

User case: I have many unread messages inside a chat, I don't want to open it and read them, but I don't like seeing the unread counter next to the chat. See how it works in telegram, for instance 

https://github.com/linagora/twake-on-matrix/assets/97684890/3eadc0a7-7773-4e10-a51e-7a68a84d4173
