### ISSUE TITLE
[bug] Reply to a message does not set the cursor under the textbox

### ISSUE THREAD

**Issue by simonelbaz** [linagora/twake-on-matrix#1349]
The cursor is not set autopmatically in the message zone.
I need to click on it to enable message writing.

Thanks

![2024-01-16_11-01-1705401500](https://github.com/linagora/twake-on-matrix/assets/1821095/015bd917-1172-499d-92c7-6858258b089e)

**Comment by hoangdat** [comment]
thanks @simonelbaz , moved to the sprint :)

**Comment by QuangHoang1210** [comment]
Scenarios:
1- User reply one message -> Cursor already set in textbox automatically -> PASSED

https://github.com/linagora/twake-on-matrix/assets/124866146/4ee7a50a-fc4b-43ec-825a-833ca2559f81


2- User reply one message -> User click to reply another message -> Cursor not set in textbox automatically -> FAILED <only FIREFOX>
*Noted: Passed on safari and chrome


https://github.com/linagora/twake-on-matrix/assets/124866146/d3a640c9-bc9d-4ac3-a5c2-ea1187692d18



**Compare with Telegram:**

https://github.com/linagora/twake-on-matrix/assets/124866146/3cfec82e-59d0-4870-a1dc-27afb0055e70

--> CLOSED this ticket cause existed related one

@hoangdat  @nqhhdev  @sherlockvn
