### ISSUE TITLE
Forward a single text message to Contacts which do not have chat before

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#135]
### Desc:
- Pick a message: long press -> forward option
- Forward Destination picker will be showed with the list of all contacts from Twake
- Can search contacts 

### DoD:
- [ ] analyze we can do it or not

if YES,

- [ ] - [ ] Long press on a text message -> forward option
- [ ] forward message to a contact (which does not have the existed chat before)

**Comment by QuangHoang1210** [comment]
### 1, Happy case:
Passed in happy case (User A already have chat conversation with User B, C , D , E ,F in Chat list screen) --> Foward message successfully and system redirect user to its chat conversation screen


### 2, Edge case:
**Precondition:** User A having friend as user B but user A have not yet chat with user B before

**Reproduce Step:**
1, User A select a message or multiple message
2, User A tap on Foward button
3, User A select user B as Quang Huy Nguyen who not chat before but in friend list.
4, User A tap on Send button

**Actual:**
Nothing happen, cannot foward message.

**Expected:**
Message should be fowarded successfully and system redirect user A to chat conversation screen with user B

**Additional information:** Focus on 00:13 secs in video bellow

https://github.com/linagora/twake-on-matrix/assets/124866146/79c6a2ac-018c-4c84-96d8-d51a8fc66077

**Comment by hoangdat** [comment]
compare to competitor?

**Comment by hoangdat** [comment]
Not support in short term
