### ISSUE TITLE
[New ticket] Say hello in draft chat

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#1351]

**Comment by QuangHoang1210** [comment]
**Android** -> PASSED

https://github.com/linagora/twake-on-matrix/assets/124866146/6b112b66-d726-4b8c-ab5e-80d2af116f71

**IOS** -> PASSED

https://github.com/linagora/twake-on-matrix/assets/124866146/3263fd4b-0773-4c1e-93e1-479ca7135c55

**WEB PC (firefox, chrome, safari)** -> PASSED

https://github.com/linagora/twake-on-matrix/assets/124866146/34e2d51d-6163-4e14-9195-61810eb7e72d
