### ISSUE TITLE
[CHAT] Improve suggestions in composer

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#1354]
### Desc:

- GIVEN user typing something in the composer
- WHEN user uses `@` to show a suggestion
- AND user uses arrows up/down on keyboard

https://github.com/linagora/twake-on-matrix/assets/99852347/1fbd8181-b27c-4a6c-b9e3-79d4eb353e74

### DoD
- [ ] Users can always use up/down arrows after showing suggestions.

**Comment by QuangHoang1210** [comment]
Passed all safari/firefox/chrome - on v 2.4.17


https://github.com/linagora/twake-on-matrix/assets/124866146/d1598fc1-253f-4d54-9db9-a5b1df2d7f97
