### ISSUE TITLE
Rework onboarding page

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#1355]
![Image](https://github.com/linagora/twake-on-matrix/assets/6462404/4a8a9846-afb0-4acf-9385-f16a035857fc)

**Comment by QuangHoang1210** [comment]
Question: 

Didn't see Create Twake ID and Sign In button on v2.4.17



![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/e0eb66b8-458d-4a2d-ab70-9e97c0c034a0)
