### ISSUE TITLE
[Web] Select mode is turn on when copy text of message

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#1358]

**Comment by QuangHoang1210** [comment]
Cannot copy by click copy text icon after select a message

https://github.com/linagora/twake-on-matrix/assets/124866146/ae441f1c-7196-4c42-a6f2-94f58adad297

**Comment by QuangHoang1210** [comment]
close as following related issue on https://github.com/linagora/twake-on-matrix/issues/1467
