### ISSUE TITLE
Change photo when create group

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#136]
### Desc:

![Image](https://github.com/linagora/twake-on-matrix/assets/6462404/10dc73a0-5c78-45f7-b768-97a747a6f005)

### DoD:
- [x] file size limitation
- [x] Can change the photo when create group

**Comment by hoangdat** [comment]
### Desc:

we will do step-by-step:
1. Upload the image to get the URL
```
client.uploadContent(file.bytes, filename: file.name)
```
2. Handle the error or limitation of uploading image
3. when user click to create group, `progress` in the `create button`
4. Execute create group with `matrixClient.createGroupChat()` add the `StateEvent` to `initialState`
```
      final addAvatarStateEvent = StateEvent(
        type: EventTypes.RoomAvatar,
        content: {
          'url': uploadResp.toString(),
        },
        stateKey: ''
      );
```
5. Wait for the response
6. next steps ....

### DoD:

**Comment by QuangHoang1210** [comment]
passed the AC but it got lagger a bit to load the group avatar
