### ISSUE TITLE
[Mobile] Support actions for item in Pinned list

### ISSUE THREAD

**Issue by sherlockvn** [linagora/twake-on-matrix#1369]
### Desc:
- Pinned list on mobile needs to be updated according to the new design. 
### Design:
https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?type=design&node-id=17075-16792&mode=design&t=YwQGfJmED6AooSGg-4
### DoD:
- [ ] When long press a message in pinned list, show a bottom sheet action (unpin, jump, copy, select)
- [ ] Change the UI when selects multiple pinned messages (no need to have delete for now, unpin and cancel is enough)
- [ ] retest with web and responsive

**Comment by QuangHoang1210** [comment]
only passed for pin/unpin single message now

**Comment by hoangdat** [comment]
<img width="896" alt="image" src="https://github.com/linagora/twake-on-matrix/assets/6462404/1c625418-c4ff-40a1-b3e7-f5017484fb8e">
