### ISSUE TITLE
[Error] Text after link in message was lost

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#1374]

**Comment by imGok** [comment]
Can you provide more details please

**Comment by QuangHoang1210** [comment]
Passed 

<img width="1306" alt="Screenshot 2024-02-16 at 7 35 01 AM" src="https://github.com/linagora/twake-on-matrix/assets/124866146/0b971dcd-c844-425c-b237-e0da5f35b9c0">
