### ISSUE TITLE
[Bug] Wrong rooting when creating DM

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1378]
Android, 2.4.15

1. Open the Chats tab (Screen 1)
2. Click Create (Screen 2)
3. Select some contact (Screen 3)
4. Click Back
5. You appear on the screen with the list of chats (screen 1)

Expectation: Clicking Back redirects me to the screen 2 instead of screen 1

https://github.com/linagora/twake-on-matrix/assets/97684890/9fc13c23-124c-48c9-8af5-f43086788b97

**Comment by QuangHoang1210** [comment]
Android -> PASSED

https://github.com/linagora/twake-on-matrix/assets/124866146/00ca7a64-5f56-4871-bf67-6c12a4c85d01

IOS -> PASSED

https://github.com/linagora/twake-on-matrix/assets/124866146/14ca3987-ecd0-45aa-b90f-914f543f1cad
