### ISSUE TITLE
[Bug] Message history isn't updated on desktop if you haven't reloaded the page for a while

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1380]
Here's the way it looks on desktop/mobile 

https://github.com/linagora/twake-on-matrix/assets/97684890/2c079e94-6b5c-4e18-ad4b-ce8d4d9ac950

![Screenshot_2024-01-22-13-03-04-463_app twake android chat](https://github.com/linagora/twake-on-matrix/assets/97684890/2fc18526-cf20-40fb-b1f0-f8bbaa36be89)

**Comment by sherlockvn** [comment]
- This bug is hard to reproduce:
- Here is what can i have tried:
1. Turn off the wifi
2. send a message to the client
3. wait for 5-10 minutes
4. turn on the wifi again
5. after 30 seconds, i received the new message

**Comment by sherlockvn** [comment]
Can you have steps to reproduce it ?

**Comment by sherlockvn** [comment]
I don't happen to me. Do you remember which version do you tested?

**Comment by tprudentova** [comment]
> I don't happen to me. Do you remember which version do you tested?

Happened just yesterday, so it's an ongoing problem :( It's 2.4.17 for Web, Safari, MacOS

**Comment by sherlockvn** [comment]
> > I don't happen to me. Do you remember which version do you tested?
> 
> Happened just yesterday, so it's an ongoing problem :( It's 2.4.17 for Web, Safari, MacOS

Okay. :) i am trying. Do you enable notifications for your browser ?

**Comment by hoangdat** [comment]
`/sync` is not called well even `/send` new message

**Comment by hoangdat** [comment]
console logs:

![Image](https://github.com/linagora/twake-on-matrix/assets/6462404/c75e7f3c-72b8-4a07-affd-efff6a9f898d)
