### ISSUE TITLE
[Bug] Captions for files aren't uploaded

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1381]
MacOS, Safari

1. Click +, select a file (pdf in the video) 
2. Add some caption, click Send 
3. The file is sent while the caption is not

https://github.com/linagora/twake-on-matrix/assets/97684890/2d11722d-1d89-4467-82af-4fed2f49501f

**Comment by hoangdat** [comment]
@sherlockvn maybe the file is not upload well, 146Mb is greater than the limitation. Please check and handle the error case

**Comment by hoangdat** [comment]
- [ ] validate file limit before showing dialog: drag n drop + paste image + add file from picker 
- [ ] remove file in dialog
