### ISSUE TITLE
[Bug] Web: Copy message selects it as well

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1389]
MacOS, Safari 

1. Open chat, open context menu of a message 
2. Select Copy message 
3. The message is selected as well

Expectation: The message isn't selected, I only see a toast message 

https://github.com/linagora/twake-on-matrix/assets/97684890/989a91d9-e211-4b4c-a358-d77a3069607c

**Comment by QuangHoang1210** [comment]
Passed -- when user select copy option then not selected chat message


*noted: Copy function is improve in the related ticket https://github.com/linagora/twake-on-matrix/issues/1467
