### ISSUE TITLE
[Bug] Problems with counters

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1399]
Current expected behaviour: all messages in chat are marked as read when the user spends 5 seconds inside chat. Correct? 

It doesn't work right in Web, it's still the behaviour described in issue #1296

Also, would it be very complicated to update the behaviour? Right now most users describe it as extremely inconvenient :( 

## Suggested behaviour ## 

1. A message is considered read as soon as the user sees it on the screen. (See Telegram) 
2. All messages from a notification are considered read if the user jumps to that chat from the aforementioned notification.
3. All messages in chat are considered read if the user sends a message after those unread messages.
4. All messages in chat are considered read if the user marks this chat as "read" from context menu of a chat.
5. All messages in chat are considered read if I use the "Jump to bottom" button.

**Comment by hoangdat** [comment]
>2. All messages in chat are considered read if the user jumps to that chat from a notification.

How many is `all`? Have you tested with 100 unread messages

**Comment by tprudentova** [comment]
> > 2. All messages in chat are considered read if the user jumps to that chat from a notification.
> 
> How many is `all`? Have you tested with 100 unread messages

Changed it a bit

**Comment by Te-Z** [comment]
Demo video:
https://github.com/linagora/twake-on-matrix/issues/1822#issue-2324777216

**Comment by Te-Z** [comment]
Separate this ticket in smaller tickets:
- timer
- jump to bottom button (set read marker -> verify if it works properly)
- update notification number as we scroll through timeline

**Comment by Te-Z** [comment]
@KhaledNjim if it works properly please post videos of demo of
- [ ] timer
- [ ] jump to bottom button

**Comment by KhaledNjim** [comment]
> [@KhaledNjim](https://github.com/KhaledNjim) if it works properly please post videos of demo of
> 
> * [ ]  timer
> * [ ]  jump to bottom button

The timer got removed in https://github.com/linagora/twake-on-matrix/pull/1363 so currently messages are marked as read as soon as you enter a chat 

## Test demo for the suggested behaviour

https://github.com/linagora/twake-on-matrix/assets/160496984/bb7b3a9d-c8ad-4c12-95be-3304747e8bc3



https://github.com/linagora/twake-on-matrix/assets/160496984/2d8e42e1-dd8a-460b-a793-3604b30f9b78



https://github.com/linagora/twake-on-matrix/assets/160496984/ac6c0231-4c83-4cb1-a2f1-765f793a18dd



https://github.com/linagora/twake-on-matrix/assets/160496984/f26b29ff-ed5b-4e94-a600-ef30a4f1d899



https://github.com/linagora/twake-on-matrix/assets/160496984/f6208154-a1bf-497f-81a4-45b58910427e

**Comment by Te-Z** [comment]
@tprudentova move this one to QA status as it seems like everything is ok

**Comment by tprudentova** [comment]
@Te-Z it should be working on 2.5.9, right?

**Comment by tprudentova** [comment]
https://github.com/linagora/twake-on-matrix/assets/97684890/b556dc8f-0b30-44c2-8021-cca0d098009e

https://github.com/linagora/twake-on-matrix/assets/97684890/11aafa6d-4076-46df-ba60-c3fe228d4abb

Not working on 2.5.9 :( Can't get rid of counters for some chats (chat.stg.lin-saas.com). If you need it, the login/password is +79166636874/Nonagon_9

**Comment by KhaledNjim** [comment]
> Screen.Recording.2024-07-02.at.11.48.43.mov 
>  video_2024-07-02_11-54-07.mp4 
> Not working on 2.5.9 :( Can't get rid of counters for some chats (chat.stg.lin-saas.com). If you need it, the login/password is +79166636874/Nonagon_9

 For chat.stg.lin-saas.com there is a server related error when trying to set a message as read  however its working on the beta server





![image](https://github.com/linagora/twake-on-matrix/assets/160496984/57de215f-bc6f-427b-bc92-5faa4afeef89)
 

https://github.com/linagora/twake-on-matrix/assets/160496984/612631f9-cf4d-4b40-9aec-c783f8c65d41

**Comment by Te-Z** [comment]
@tprudentova could you try on matrix.linagora.com ?

**Comment by tprudentova** [comment]
@Te-Z It's working well on linagora env
