### ISSUE TITLE
[Bug] Cannot pin messages if I'm not the admin of the chat

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1400]
1. Open a chat where you're NOT an admin 
2. Select a message and try to pin it 
3. No permission 

Expectation: anyone in the chat can pin messages 

https://github.com/linagora/twake-on-matrix/assets/97684890/556a0632-59a9-4003-8b71-1f56ecf174b2

**Comment by shepilov** [comment]
Everyone can pin messages
Everyone can can change avatar
Everyone can rename the group

**Comment by QuangHoang1210** [comment]
Alll platform - v 2.4.22 @sherlockvn 

Everyone can pin messages -> FAILED 
Everyone can can change avatar -> FAILED 
Everyone can rename the group -> FAILED
Everyone can invite people -> PASSED

**Comment by QuangHoang1210** [comment]
Passed with new created group
