### ISSUE TITLE
[UI] [Only Web] Elements in Adding Member Dialog is broken

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1403]
OS: WEB only
Device: Laptop
Twake version:  2.4.15

### *Precondition: 
- User A,B,C in group chat

### **Step:** 
1, User click on Group infor
2, User click on Add Member

### **Actual:** 
Elements on Add member is brokent

### **Expected:** 
It's not broken

**WEB**

https://github.com/linagora/twake-on-matrix/assets/124866146/349bc174-f1a9-477c-b4d2-d79f659d647d

**Comment by nqhhdev** [comment]
Fixed it on new version: 2.4.17

- https://github.com/linagora/twake-on-matrix/pull/1357
