### ISSUE TITLE
[Pinned chat] Improve jumping into correct pinned message

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1404]
OS: WEB + ANDROID
Device: Laptop
Twake version:  2.4.15

### *Precondition: 
- User A,B,C in group chat
- Pinned 8 message

### **Step:** 
1, User click on Pinned message to jump

### **Actual:** 
The last one not jump correctly 

### **Expected:** 
Jump correct message

**IOS**
- Working well

**WEB**

https://github.com/linagora/twake-on-matrix/assets/124866146/35c415ca-e6e9-4e9b-a4b6-5583b17873c8

**ANDROID**

https://github.com/linagora/twake-on-matrix/assets/124866146/32942895-bddf-47a3-9040-007d2c401c0c

**Comment by nqhhdev** [comment]
Verify it on new version 2.4.18

@QuangHoang1210
