### ISSUE TITLE
[Search in chat] [Android only] App freeze when user try to click search in chat and go back

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1406]
OS: ANDROID only
Device: Laptop
Twake version:  2.4.15

### **Step:** 
1, User click chat conversation
2, User click search icon
3, User click back icon

### **Actual:** 
- Freeze app in black screen

### **Expected:** 
- can go back smoothly

https://github.com/linagora/twake-on-matrix/assets/124866146/38844d20-d00e-49ac-bda9-8984a98c49cb

**Comment by nqhhdev** [comment]
Pls test it again on new version 2.4.18
