### ISSUE TITLE
[Improve] Search no result in create direct/group chat

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#1411]
### Dec:

- Given click on new private/group chat
- And click on search icon
- When typing some
- Then no search result

![Image](https://github.com/linagora/twake-on-matrix/assets/99852347/65cb7c7f-d521-410e-88dd-ee3e45abb535)

### DoD:

- [ ] Update display no search result

**Comment by QuangHoang1210** [comment]
**WEB PC (firefox / chrome / safari)** -> PASSED
- Search in Contact tab -> No result -> PASSED
- Search in Contact tab -> Have result -> PASSED

- Search in Chat tab >> Direct Chat -> Have result -> PASSED
- Search in Chat tab >> Direct Chat -> No result -> PASSED

- Search in Chat tab >> Group Chat -> Have result -> PASSED
- Search in Chat tab >> Group Chat -> No result -> PASSED

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/0aeb2343-7600-432e-9930-77de53d5848a)

https://github.com/linagora/twake-on-matrix/assets/124866146/c8a4fe7a-0aaf-4666-8cfc-30c8d79363eb


**Android - FAILED**
- Search in Contact tab -> No result -> PASSED
- Search in Contact tab -> Have result -> PASSED

- Search in Chat tab >> Direct Chat -> Have result -> PASSED
- Search in Chat tab >> Direct Chat -> No result -> **FAILED**

- Search in Chat tab >> Group Chat -> Have result -> PASSED
- Search in Chat tab >> Group Chat -> No result -> **FAILED**

https://github.com/linagora/twake-on-matrix/assets/124866146/eb75f6e0-b71b-49f3-96a4-a612e16e2b3a


**IOS - FAILED**
- Search in Contact tab -> No result -> PASSED
- Search in Contact tab -> Have result -> PASSED

- Search in Chat tab >> Direct Chat -> Have result -> PASSED
- Search in Chat tab >> Direct Chat -> No result -> **FAILED**

- Search in Chat tab >> Group Chat -> Have result -> PASSED
- Search in Chat tab >> Group Chat -> No result -> **FAILED**

https://github.com/linagora/twake-on-matrix/assets/124866146/a3cce682-0aa3-4d3a-b952-db95705d8223

**Comment by nqhhdev** [comment]
I fixed search no result in Group Chat and Direct Chat on iOS/Android 
- #1417 

Pls wait for new release version and test it again
