### ISSUE TITLE
As a user during the login I don't want to have pop-up with SSO, it's not visible in safari

### ISSUE THREAD

**Issue by shepilov** [linagora/twake-on-matrix#1414]
When I click on the login button, let's try to open SSO in the same window to not force user to search how to enable pop-ups

![Image](https://github.com/linagora/twake-on-matrix/assets/14924963/7f3c14e4-1f09-4294-ba8d-6606de8802f4)

**Comment by hoangdat** [comment]
Reproduce current issue

https://github.com/linagora/twake-on-matrix/assets/6462404/99ce7147-8ba7-47b4-825f-c84010a44d86
