### ISSUE TITLE
[Bug] Online statuses aren't translated

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1419]
Online statuses aren't translated, and I don't see lines for them on weblate. If you could add them, that would be great

![photo_2024-01-29_18-15-17](https://github.com/linagora/twake-on-matrix/assets/97684890/5221df08-a145-43fc-a2b9-c0477ab7bbfb)

**Comment by hoangdat** [comment]
done in v2.4.18. please verify
