### ISSUE TITLE
[Bug] Inactive greeting pop-up

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1422]
1. Open a direct chat with someone you never talked to before 
2. Try clicking on the greeting 
3. Nothing happens 

Expectation: Something like "Hello 😃" is sent to the chat

https://github.com/linagora/twake-on-matrix/assets/97684890/39d33f6a-15c8-4350-b313-3216301091f9

**Comment by hoangdat** [comment]
it is duplicated
