### ISSUE TITLE
[Emote setting] User getting 404 page when clicking on Twake Setting >> Chat >> Emote Setting

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#1424]
OS: WEB/ IOS/ ANDROID
Device: Laptop/ Mobile
Twake 2.4.15

### **Reproduce Step:** 
1, User click on Setting
2, User click on Chat
3, User click on Emote Setting

### **Actual:** 
- redirect to 404 not found

### **Expected:** 
- Redirect to Emote Setting page

**Comment by tprudentova** [comment]
Duplicate #1160

**Comment by hoangdat** [comment]
will be done in #1437
