### ISSUE TITLE
[UI] Header position of each tab Contacts, Chats, Settings, to be align to the left margin

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#1425]
OS: WEB/ IOS/ ANDROID
Device: Laptop/ Mobile
Twake 2.4.15

### **Reproduce Step:** 
1, User click on Settings
2, User click on Chats
3, User click on Contacts

### **Actual:** 
- Contacts, Chats, Settings header is not same position

### **Expected:** 
- Align headers to the left margin

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/f09e9f40-5ffd-4087-bf94-3941afab354d)

**Comment by hoangdat** [comment]
- please make the same design for all current screen
- please suggest to change in mobile also (we still need to think about select mode)

@Bobpodvalnyi @tprudentova

**Comment by nqhhdev** [comment]
Any update for new design?

**Comment by Bobpodvalnyi** [comment]
@hoangdat @nqhhdev it's all align in design, just the bug from Devs
