### ISSUE TITLE
[Change name] User name is not displaying correctly in direct chat

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1428]
OS: Android/ IOS/WEB
Device: Mobile / LAPTOP
Twake version:  2.4.10

### **Precondition:** 
- User A , B in the same group chat
- User A and user B already in direct chat before

### **Reproduce Step:** 
1, User A have profile name: Nhat Quang Nguyen Bụi Đời Chợ Cầu Lớn
2, User A create group chat with user B
3, User A chat in group 
4, User A changed profile name to "ĐẸP TRAI MẮT NAI"

### **Actual:** 
**For group chat:**
- New name is applied and displayed on Group Chat message at Chat list. -> PASSED
- New name is displayed on Sender name/ Receiver name at Group chat message -> PASSED

**For Direct chat**
_- But not displayed on Direct Chat message at Chat list. -> FAILED
- Not displayed on Sender name/ Receiver name at Direct chat message._ -> FAILED

### **Expected:** 
- New name should be applied and displayed in direct chat / group chat / chat list / all chat conversation

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/3d1330c7-9609-46f5-967f-66cac42b93b0)

https://github.com/linagora/twake-on-matrix/assets/124866146/c5310a46-f7f5-43be-8258-51eedf47473d

**Comment by nqhhdev** [comment]
I was reproduced for this issue on version 2.4.19. It's works well. Pls re-test and confirm for team

https://github.com/linagora/twake-on-matrix/assets/99852347/6b3c5e5a-9f3e-482e-be7d-e5f68626794a
