### ISSUE TITLE
[BUG] Can't click on Notification switch button in Group Information

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#1439]
OS: WEB/ IOS/ ANDROID
Device: Laptop/ Mobile
Twake 2.4.17

https://github.com/linagora/twake-on-matrix/assets/99852347/d7763fa2-0596-47fc-af28-10bd6066992a

Actual:

- I want to turn off receive notification in group chat. I can't click/press on notification switch button

Expected:
- Can click/press on notification switch button

**Comment by hoangdat** [comment]
Design: https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?type=design&node-id=22030-14240&mode=design&t=6XekLZdstadKw0ME-4
Updated for avatar
