### ISSUE TITLE
[Bug] Mobile: Button Send disappears if I click on the greeting pop-up

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1450]
Android, 2.4.17

1. Go to contacts, find someone you don't have a chat history with 
2. Click on the greeting emoji
3. The composer is pre-filled with text, but the Send button disappears. You need to type something more to send the message 

https://github.com/linagora/twake-on-matrix/assets/97684890/5c911c63-7763-4de4-b707-11c7b1f08ff0

**Comment by nqhhdev** [comment]
Duplicated #1445
