### ISSUE TITLE
[Android / IOS] The list of search chat message result is becoming empty when user trying to scroll down to load more results

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1454]
OS: Android / IOS
Device: Mobile
Twake Chat version:  2.4.17 -- beta.twake.app

### *Reproduce Step:
1, Select Chat tab
2, User click on search bar
3, User input keywords "messsage"
4, User click search icon
5, User try to scroll down to load more message

### **Actual:** 

- Becoming empty -> No result

### **Expected:** 

- Still keep the same list of result , just loading more result if having

https://github.com/linagora/twake-on-matrix/assets/124866146/23ff87de-9dce-4dbe-a28f-d38c55adf45a

**Comment by hoangdat** [comment]
can not reproduce
