### ISSUE TITLE
Emojis settings leads to a 404

### ISSUE THREAD

**Issue by Facyla** [linagora/twake-on-matrix#1459]
Using web client on Ubuntu FF : https://beta.twake.app/web/#/rooms/chat
GO to Settings > Click on Emojis settings => 404 error on https://beta.twake.app/web/#/error

![image](https://github.com/linagora/twake-on-matrix/assets/286492/5c3fd845-fd0c-453e-a548-35295001bfe5)

**Comment by hoangdat** [comment]
removed this settings
