### ISSUE TITLE
Discussion folders settings does not open side panel

### ISSUE THREAD

**Issue by Facyla** [linagora/twake-on-matrix#1460]
Web client on Ubuntu FF. 
When configuring the settings, clicking on the Discussion folders does not select the tab, nor open the side panel. 
[Capture vidéo du 2024-02-14 17-02-17.webm](https://github.com/linagora/twake-on-matrix/assets/286492/571c2829-e413-4720-a725-5bf083d434fe)

**Comment by hoangdat** [comment]
`Discussion folders` is not available

![Image](https://github.com/linagora/twake-on-matrix/assets/6462404/17fb1bc1-c591-4ab9-a93f-26278fae9aaf)
