### ISSUE TITLE
[Firefox] Cannot copy by click copy text icon after select a message

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1467]
OS:  firefox 
Device: WEBPC
TMail version:  2.4.17

### *Reproduce Step:
1, User A and B in a chat conversation
2, A or B select the chat message and click copy

### **Actual:** 
Cannot copy by click copy text icon after select a message

### **Expected:** 
Can copy text in message which been selected

https://github.com/linagora/twake-on-matrix/assets/124866146/ae441f1c-7196-4c42-a6f2-94f58adad297

**Comment by sherlockvn** [comment]
It works well in v2.4.18

**Comment by QuangHoang1210** [comment]
PASSED 2.4.18

UX : Raise in another ticket <select multiple message -> hide copy icon>
