### ISSUE TITLE
[Firefox ony] The cursor is not set under textbox automatically when user change reply message

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1469]
### User reply one message -> User click to reply another message -> Cursor not set in textbox automatically -> FAILED <only FIREFOX>
*Noted: Passed on safari and chrome

OS:  Chrome/ firefox / safari
Device: WEBPC
TMail version:  2.4.17

### *Reproduce Step:
1, User click reply message 1
2, User typing something but not click send
3, User click reply another message

### **Actual:** 
The cursor is disappeared under textbox

### **Expected:** 
The cursor should be automatically set under textbox same on chrome and safari

https://github.com/linagora/twake-on-matrix/assets/124866146/d3a640c9-bc9d-4ac3-a5c2-ea1187692d18

**Compare with Telegram:**

https://github.com/linagora/twake-on-matrix/assets/124866146/3cfec82e-59d0-4870-a1dc-27afb0055e70

**Comment by sherlockvn** [comment]
work for me in all platform in v2.4.18

**Comment by QuangHoang1210** [comment]
Happen in all platform, please try again @sherlockvn

**Comment by QuangHoang1210** [comment]
**Still happen on 2.4.21 WEB PC**

**Chrome <some time happen>**

https://github.com/linagora/twake-on-matrix/assets/124866146/85474270-f60a-4441-9023-f2833dcf247c


**Firefox <100% reproduce>**

https://github.com/linagora/twake-on-matrix/assets/124866146/85562321-6276-49de-9e3a-52e3a9050ad2

@sherlockvn

**Comment by nqhhdev** [comment]
Now I tested it on Firefox with new Twake version (2.5.4) and Flutter version (3.22.0) 

Works well


https://github.com/linagora/twake-on-matrix/assets/99852347/7f951a88-0a11-42b8-bd7e-396cc065f879
