### ISSUE TITLE
[IOS/Android/WEBPC] Some private chat in long time ago is missing chat

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1480]
### When user open a private chat in long time ago then chat chat is missing 

OS:  Android/ IOS
Device: Mobile
TMail version:  2.4.17

### *Reproduce Step:
1, User open a private chat conversation in long time ago

### **Actual:** 
Chat is missing

### **Expected:** 
Should have chat

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/1ce2e950-3425-4a58-bd9b-402ca807e86b)

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/e40c8812-8f07-4cc9-bf71-59e26d5f4b36)

**Comment by nqhhdev** [comment]
### Display empty chat
- When I create a new chat or new group, have many events. How to know exactly chat no message yet?
