### ISSUE TITLE
[IOS/ANDROID] Greeting message is generated but send button is changed to emoji in composer

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1494]
OS:  Android / IOS
Device: Mobile
TMail version:  2.4.17 & 2.4.18

*Precondition: 
- User A and B not yet chat chit before

### *Reproduce Step:
1, User A create new direct chat
2, User A click on user B at search result
3, User A click on Greeting message

### **Actual:** 
- Greeting message is generated but send button is changed to emoji in composer.
- User have to add one more character in composer in order to send message

### **Expected:** 
- Send button is displayed 

https://github.com/linagora/twake-on-matrix/assets/124866146/36d7bf0f-db7f-42b0-ba31-d53214f8250d

**Comment by hoangdat** [comment]
fixed in 2.4.19
