### ISSUE TITLE
[IOS/ ANDROID] Loading forever when fwd a message to group chat/ direct chat which being invited but not accept

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1497]
OS:  Android / IOS
Device: Mobile
TMail version:  2.4.17 & 2.4.18

*Precondition:
- User A is invited to a group chat or direct chat but not accept it

### *Reproduce Step:
1, User A foward a message / file / image / video.. to group chat/ direct chat in precondition

### **Actual:** 
- Loading forever but not crash, user still can go back

### **Expected:** 
- Prevent user can search and see group chat / direct chat in pending invitation
- Should not show the group chat / direct chat which being invited but not yet accept in the FWD suggesstion list

https://github.com/linagora/twake-on-matrix/assets/124866146/567dacfe-0fbd-4578-8503-14a1922b5cbc

**Comment by hoangdat** [comment]
- [ ] filter out chat which is not accepted
