### ISSUE TITLE
[ANDROID/IOS] Don't have download icon for videos

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1499]
OS:  Android / IOS
Device: Mobile
TMail version:  2.4.17 & 2.4.18

### *Precondition:
- User A and B in direct chat
- User A and B in same group chat

### *Reproduce Step:
1, User A send a video direct to B
2, User A send video to group which have A and B
3, User A or B click to preview video

### **Actual:** 
- No download button for both A and B

### **Expected:** 
- Should have download button same image preview

**Comment by sherlockvn** [comment]
wait for #1476 is merged
