### ISSUE TITLE
[Chat] Limit invitations when creating a new group chat

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#150]
OS: ANDROID, IOS
Device: Mobile

*Precondition:

Create a new group invite more members

*Reproduce Step:
1, Open new group chat
2, Invite more members (> 10 members, do not count yourself)
2, Click on Create 

Actual:
Nothing happens and error `M_UNKNOWN: Cannot invite so many users at once`

Expected:

- Check the condition of the number of people who can be invited to the group
- Can create new group with more members

```
flutter: [Matrix] checking for stale group calls in room !GUDfQHrbVsXqztZtNP:tom-dev.xyz
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: M_UNKNOWN: Cannot invite so many users at once
#0      MatrixApi.unexpectedResponse (package:matrix_api_lite/src/matrix_api.dart:52:9)
#1      Api.createRoom (package:matrix_api_lite/src/generated/api.dart:924:37)
<asynchronous suspension>
#2      Client.createGroupChat (package:matrix/src/client.dart:674:20)
<asynchronous suspension>
#3      NewGroupInfoController.moveToGroupChatScreen (package:fluffychat/pages/new_group/new_group_info_controller.dart:18:20)
<asynchronous suspension>
flutter: [Matrix] checking for stale group calls in room !VmQAIgzRqGKYyQMOpn:tom-dev.xyz
flutter: [Matrix] checking for stale group calls in room !cFvpdWGaUlMzRBehJe:tom-dev.xyz
flutter: [Matrix] checking for stale group calls in room !HIcofkRmimJVwERotU:tom-dev.xyz
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: M_UNKNOWN: Cannot invite so many users at once
#0      MatrixApi.unexpectedResponse (package:matrix_api_lite/src/matrix_api.dart:52:9)
#1      Api.createRoom (package:matrix_api_lite/src/generated/api.dart:924:37)
<asynchronous suspension>
#2      Client.createGroupChat (package:matrix/src/client.dart:674:20)
<asynchronous suspension>
#3      NewGroupInfoController.moveToGroupChatScreen (package:fluffychat/pages/new_group/new_group_info_controller.dart:18:20)
<asynchronous suspension>
```

**Comment by hoangdat** [comment]
- [ ] demo for web (no problem in limitation)
- [ ] try to investigate more on mobile app

**Comment by Te-Z** [comment]
couldn't reproduce on web: it works as expected with a groupe of 11 people, includng thee who created the group. But not above

**Comment by sherlockvn** [comment]
Based on what i research:
- it's the default maximum invites when create a group
- But we can increase the maximum invite by config from homeserver


Docs:
- https://github.com/matrix-org/synapse/blob/be65a8ec0195955c15fdb179c9158b187638e39a/synapse/config/ratelimiting.py#L79
- https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#rc_invites

![Image](https://github.com/linagora/twake-on-matrix/assets/43041967/b45da0e5-e1ce-48fb-b95a-240ea92d2b44)

**Comment by hoangdat** [comment]
back-end updated Rate limit in `linagora` env
