### ISSUE TITLE
[ANDROID only] [Direct Chat / Group Chat] Cannot go back at search screen in direct chat <android only> [smt crashed]

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1500]
OS:  Android / IOS
Device: Mobile
TMail version:  2.4.17 & 2.4.18

### *Precondition:
- User A and B in direct chat
- User A and B in same group chat

### *Reproduce Step:
1, User go to direct chat / group chat 
2, User click on search icon
3, User type something
4, User click back icon

### **Actual:** 
- No action
- Sometime crashed the app

### **Expected:** 
- Can back to chat list

**Comment by tprudentova** [comment]
Duplicate #1406
