### ISSUE TITLE
[WEB PC] Duplicate Copy options when user select a message

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1518]
OS:  WEB PC
Device: Firefox / chrome / safari
TMail version:  2.4.19

### *Precondition:
- User A and B in direct chat
- User A and B in same group chat

### *Reproduce Step:
1, User select a message in direct chat / group chat
2, User click on three dot options

### **Actual:** 
- duplicate 2 copy option

### **Expected:** 
- only have 1 copy option

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/68fa7031-9463-4a4b-b97e-6189f6306e57)

**Comment by hoangdat** [comment]
duplicated #1485
