### ISSUE TITLE
[All platform] Pinned list is sync automatically once user change PIN/UNPIN message

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1519]
OS:  All platform
Device: Laptop / Mobile
TMail version:  2.4.19

### *Precondition:
- User A login in Android app
- User B login in IOS app
- User C login in WEB PC
- A,B,C in group chat

### *Reproduce Step:
1, User A and B open group chat conversation
2, User C pin/unpin a message
3, A and B go to pin list to see

### **Actual:** 
- A and B can't see the pinned list is updated

### **Expected:** 
- A and B will see pinned list is updated

https://drive.google.com/file/d/16xm_w8HA7p08hNdTlRHNH7Nt4wTGR7XV/view?usp=sharing

**Comment by hoangdat** [comment]
- @dev team, please make sure `/sync` also have pin events
