### ISSUE TITLE
[Mobile] [Pinned] When user long press a message then missing a bottom sheet action (unpin, jump, copy, select) in pinned list

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1520]
OS:  Android / IOS
Device: Mobile
TMail version:  2.4.19

### *Precondition:
- Existed pinned message

### *Reproduce Step:
1, User go to pinned list
2, User long press a pinned message

### **Actual:** 
- Missing a bottom sheet action "copy"
- Only have X to close and unpin single message

### **Expected:** 

- Should have action mentioned bellow image

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/5f1ee033-0e5d-4ee2-ae50-03dfd973c352)

Bug:

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/d0cb2d4e-0724-43d8-bea4-0d20f9e70111)

**Comment by hoangdat** [comment]
duplicated #1369
