### ISSUE TITLE
Bubble message is have weird empty space after pill was sent

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1521]
OS:  Android / IOS / WEBPC
Device: Mobile / LAPTOP
TMail version:  2.4.19

### *Precondition:
- A, B , C in group chat
- A have long name

### *Reproduce Step:
1, User B mentioned A name and send in group chat

### **Actual:** 
- Bubble message having big empty space

### **Expected:** 

- Improve smaller same as other bubble chat with same size

https://drive.google.com/file/d/11pL9usksot9AK4pIkjWzdczddMGIRqoc/view?usp=sharing

**Comment by hieutbui** [comment]
Handled:
- #1669
