### ISSUE TITLE
[Share media and links] Some video is can't loading and its preview time is not show in thumbnail

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1522]
OS:  Android / IOS / WEBPC
Device: Mobile / LAPTOP
TMail version:  2.4.19

### *Precondition:
- A: qkdo
- B: nqnguyen

### *Reproduce Step:
1, A open B chat conversation
2, A click on profile
3, A click on shared media and links
4, A try to preview video

### **Actual:** 
- Video with not loading thumbnail is can't watch
- Only can watch video with thumnail is loading

### **Expected:** 

- All thumbnail is loading and can preview

**Mobile**

https://drive.google.com/file/d/1UauKfrbVuaFO-OAqlHdKdM7bTO89o-06/view?usp=sharing

**WEBPC**

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/4099c00d-2b34-42f1-b3bd-44aeb6185bf3)

**Comment by nqhhdev** [comment]
### Response 

1. Video has thumbnail


![Image](https://github.com/linagora/twake-on-matrix/assets/99852347/2e6c0d83-6777-4d16-b99b-bb3db1c90475)


2. Video has not thumbnail

![Image](https://github.com/linagora/twake-on-matrix/assets/99852347/36413692-01d1-4a38-ac9c-acf47686f82c)

**Comment by nqhhdev** [comment]
### Image decrypted

1. Has thumbnail

![Image](https://github.com/linagora/twake-on-matrix/assets/99852347/5c4da8c1-bf9a-4d35-b63a-25ad030ccf4e)


2. Has not thumbnail


![Image](https://github.com/linagora/twake-on-matrix/assets/99852347/0e2a420a-d3a4-4193-8427-c751aa044d03)
