### ISSUE TITLE
[Bug] Cannot unmute more than 2 chats at the same time

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1526]
Android, 2.4.19

1. Select >2 muted chats 
2. Click Unmute 
3. Only 2 chats are unmuted 

Expectation: all of the selected chats are unmuted

https://github.com/linagora/twake-on-matrix/assets/97684890/8258b49d-f283-47d2-a2f6-6e01238f22ad

**Comment by hoangdat** [comment]
Is it included in latest version @Te-Z , if yes, please move to QA to verify
