### ISSUE TITLE
[Bug] Uploaded files sometimes disappear from conversation

### ISSUE THREAD

**Issue by Te-Z** [linagora/twake-on-matrix#1536]
Chrome & Android

1. Upload a large file
2. Wait for upload to be done
3. Leave the room then get back inside

[Capture vidéo du 05-03-2024 11:07:03.webm](https://github.com/linagora/twake-on-matrix/assets/31937920/2b82bd8f-e4ac-433f-ac27-7d3faf7b610a)

https://github.com/linagora/twake-on-matrix/assets/31937920/a45874d7-302f-44b8-9b11-3cc1957ce437

Might be related to https://github.com/linagora/twake-on-matrix/issues/1522

**Comment by tprudentova** [comment]
#1381 might be connected

**Comment by nqhhdev** [comment]
> #1381 might be connected

IMO: Not related to #1381, this ticket has a problem with loading image or video thumbnails

**Comment by hoangdat** [comment]
this file is not upload successfully but the placeholder not update well
