### ISSUE TITLE
[Bug] [WEB; MOBILE] Infinite upload while changing profile avatar/name

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1537]
MacOS, Safari; Android, iOS 2.4.19 

1. Go to settings 
2. Click Change avatar or name 
3. Select an avatar, click Done 
4. Infinite upload is displayed. 

NB: If you reload the page/app, the new avatar will be uploaded

https://github.com/linagora/twake-on-matrix/assets/97684890/b81976bb-ad92-44ea-8d92-f9487eadd1f8

https://github.com/linagora/twake-on-matrix/assets/97684890/ba68b982-e9bd-4673-ae88-539840b58e5e

Might be connected with #1453

**Comment by nqhhdev** [comment]
Same #1453
