### ISSUE TITLE
[Bug] [MOBILE] Wrong display of search results

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1539]
iOS. 2.4.19 

Bug No. 1

1. Go to Contacts tab 
2. Enter in the search bar an email of someone that exists both in Linagora contacts and in your device's address book. 
3. The result in the Linagora Contacts includes a phone number, and the result in device's Contacts doesn't (should be vice versa)

<img src="https://github.com/linagora/twake-on-matrix/assets/97684890/6f64d3c2-70e9-4c14-a6ca-8139961b8de8" width="200" />

Bug No. 2 

1. Go to Contacts tab
2. Enter a search request that doesn't exist in Linagora contacts but does exist in your device's address book
3. A "No results" is displayed even though there is a result 
Expectation -> If there's a result in any section, the "No results" warning isn't displayed. 

<img src="https://github.com/linagora/twake-on-matrix/assets/97684890/0c48495e-2c7b-4d46-b1cb-19ae630c0f93" width="200" />

**Comment by hoangdat** [comment]
hi @tprudentova 
- Bug 2 -> implementing
- Bug 1 -> we separated one phone contact into many contact in Twake app base on mail, phone number (in case one contacts have many information of mail, phone)
