### ISSUE TITLE
[Bug] [MOBILE] Contacts aren't always synchronized 

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1541]
Even though I gave access to my contacts, sometimes synchronization isn't performed and I don't see my device's contacts. Reloading the app helps 

<img src="https://github.com/linagora/twake-on-matrix/assets/97684890/36d97104-e92a-43b5-aefd-872b9908c40d" width="200" />
<img src="https://github.com/linagora/twake-on-matrix/assets/97684890/817fc991-9618-4ce0-ac81-47b0383c2f23" width="200" />

**Comment by nqhhdev** [comment]
same #1791
