### ISSUE TITLE
[Improvement] Make message highlights brighter 

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1542]
All platforms

We need to highlight messages we jump to a bit brighter, right now it's almost invisible. Compare with telegram

 
<img src="https://github.com/linagora/twake-on-matrix/assets/97684890/1603075d-e230-4b1e-b468-d32d7cd52b2e" width="200" />

<img src="https://github.com/linagora/twake-on-matrix/assets/97684890/fad72db7-8ac7-4e94-b0b1-29ac3630b36a" width="200" />

**Comment by sherlockvn** [comment]
i updated the color to this ? is it oke for you @Bobpodvalnyi ?
<img width="303" alt="image" src="https://github.com/user-attachments/assets/44c69d2b-c98b-4612-aeca-8ea3e1ebd092">

**Comment by Te-Z** [comment]
@Bobpodvalnyi since this screen will evolve in the future as we discussed can you confirm if you're ok or not with the above quick fix as a temporary enhancement before the evolution ?

**Comment by Te-Z** [comment]
@sherlockvn here's the link for the highlight design: https://www.figma.com/design/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?node-id=27259-182791&t=a2hFjwDmcHBdyVqx-0
