### ISSUE TITLE
[Bug] I was able to create multiple direct chats with the came person

### ISSUE THREAD

**Issue by shepilov** [linagora/twake-on-matrix#1544]
<img width="404" alt="image" src="https://github.com/linagora/twake-on-matrix/assets/14924963/0ac65822-5571-4540-85dc-d19ed9c6fbab">

I was trying to created a chat with a new guy, but the app hangs at this moment, and nothing happened, after the page refresh I was able to create a new chat, but the previous one was already exist, and with the same result.

**Comment by hoangdat** [comment]
Hi, I can not reproduce this case.
First, as your picture: 
- the first chat: direct chat (no icon of group chat) 
- second chat: group chat with encryption
- third chat: group chat with non encryption
- fourth chat: another group chat with non encryption

**Comment by hoangdat** [comment]
draft screen have no response when trying to create a chat in Desktop
