### ISSUE TITLE
[Mobile] Keyboard is disappeared then appeared if we send message in a chat which found from search

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#1545]
### Reproduce:
1. search a chat
2. open chat in search result
3. send message 
4. observe keyboard

**Comment by sherlockvn** [comment]
Dont happend in main anymore

https://github.com/linagora/twake-on-matrix/assets/43041967/b83523bb-5f25-47f6-ab60-0bfc53bdd808
