### ISSUE TITLE
UI: differenciate rendering of enabled/notenabled users 

### ISSUE THREAD

**Issue by Facyla** [linagora/twake-on-matrix#1548]
The users that have not been onboarded yet = they exist for the organisation, but have not enabled their Twake Chat account yet, and therefore no one can interact with them until they have subscribed.  

![image](https://github.com/linagora/twake-on-matrix/assets/286492/c3715a8a-3f47-44a0-947d-5a3603518685)

=> i'd suggest using the same UI as for "disabled" form elements, ie. use grey tones, add a little transparency + avoid :hover effects (which are for interactive elements, not informative inactive ones).

**Comment by hoangdat** [comment]
- [ ] keep only `non active` status 
- [ ] get rid of `active` status

**Comment by hoangdat** [comment]
#2005
