### ISSUE TITLE
[Composer] Capture image in composer

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#155]
### Desc:
```
As a user, I want to easily to take the picture and send to the dialog/chat in mobile
```

### DoD:
- [ ] only available in mobile device
- [ ] open the plugin of system camera
- [ ] take the picture and see it in the preview screen with send button (please propose the preview design)
- [ ] send this picture

**Comment by QuangHoang1210** [comment]
Passed the AC but the capture image is taken a bit long time to send ( about 1 minutes)
