### ISSUE TITLE
[Bug] [WEB; MOBILE] When searching in the Chats tab, the contact is shown twice

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1551]
2.4.19, Safari MacOS, Android

1. Go to the Chats tab 
2. Search for a contact you have a direct chat with 
3. The contact in search results is displayed twice (as a contact and as a direct chat)

Expectation: The contact is only shown once

<img width="315" alt="Screenshot 2024-03-06 at 15 20 26" src="https://github.com/linagora/twake-on-matrix/assets/97684890/6ec04452-5263-4fb8-a1de-f6581c59b9bb">

**Comment by hoangdat** [comment]
Improve search screen:
- animation transform from chat list - search
- gesture back in search
- hover of item in search screen
- remove duplicate item for direct chat
- show avatar for room chat: Chats and Contacts
- filter in matrix Id duplicated direct chat and contact

**Comment by nqhhdev** [comment]
> Improve search screen:
> 
> * animation transform from chat list - search
> * gesture back in search
> * hover of item in search screen
> * remove duplicate item for direct chat
> * show avatar for room chat: Chats and Contacts
> * filter in matrix Id duplicated direct chat and contact

#1557  This ticket should improve animation transform Chat List => Search
