### ISSUE TITLE
[Bug] [MOBILE] When clicking on a forwarded reply, the app breaks

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1553]
Android, 2.4.19 

1. Reply to a message 
2. Forward the reply to another chat 
3. Click on the forwarded reply 
4. The app breaks

https://github.com/linagora/twake-on-matrix/assets/97684890/527a7348-6f76-4fbe-bcd4-1311b2d7b643

**Comment by hoangdat** [comment]
- Only forwarding current message, not forward replied message (same as Telegram)
