### ISSUE TITLE
[Video] Improve the video player

### ISSUE THREAD

**Issue by sherlockvn** [linagora/twake-on-matrix#1564]
### Description:
- When play a video, The appbar is not automatically disapear after a few second playing.
### Demo:

https://github.com/linagora/twake-on-matrix/assets/43041967/cd63573f-18d2-4789-bbe9-87b84b12b568

### DOD:
- [ ] The app bar should diappear after few seconds playing video
- [ ] when open pop up in app bar, the appbar should keep opening
- [ ] Tap into screen, the app bar shown again

**Comment by QuangHoang1210** [comment]
already disappeared in few seconds on IOS 2.5.0 but the header of app bar is not at the top.

Close this one --> following in other ticket: https://github.com/linagora/twake-on-matrix/issues/1705#issue-2245781844
