### ISSUE TITLE
[Video] Remove not playable video and change it to file

### ISSUE THREAD

**Issue by sherlockvn** [linagora/twake-on-matrix#1565]
### Desc:
- Video file like .avi, .wvm don't have thumbnail and not common for video file. Currently, it looks ugly if someone send a file with these extension because these files are recognize as video file. So, we will recognize it as file now.

### DOD:
- [ ] remove video player for .avi and .wvm extension
- [ ] Convert .avi and .wvm extension to file downloadable
### Reference:

https://github.com/linagora/twake-on-matrix/assets/43041967/8d8f2f2a-6717-4942-8d9e-cc0ef9d38807

**Comment by QuangHoang1210** [comment]
Passed on IOS 2.5.0

![IMG_0423](https://github.com/linagora/twake-on-matrix/assets/124866146/60b37fa6-1f06-4345-b270-e2e8b26c0aaf)
