### ISSUE TITLE
[BUG] [WEB/MOBILE] Infinite loading a room where there's a lot of files

### ISSUE THREAD

**Issue by Te-Z** [linagora/twake-on-matrix#1566]
Android, Chrome

In a room where there's a lot of files sent:

- go in room A
- change for an other one
- go back in room A
- Room A can't display its content

[Capture vidéo du 11-03-2024 10:55:08.webm](https://github.com/linagora/twake-on-matrix/assets/31937920/3a880207-0054-493c-944e-9e4c5f4ceb7b)

[Capture vidéo du 11-03-2024 10:56:48.webm](https://github.com/linagora/twake-on-matrix/assets/31937920/b9b1bffe-a618-481b-ba60-9d4565eca48f)

[Capture vidéo du 11-03-2024 11:04:47.webm](https://github.com/linagora/twake-on-matrix/assets/31937920/65680386-2683-4c0c-8961-004849472ac8)

**Comment by Te-Z** [comment]
On mobile, to access a bugged room you have to clean app data and cache then restart the app

**Comment by Te-Z** [comment]
Not happen only on rooms with a lot of files

[310936528-7f551e2e-391e-4cc6-8f98-67970f5b7a0a.webm](https://github.com/linagora/twake-on-matrix/assets/31937920/4bad4a3b-705c-412a-aba6-ebc8fbd6bee0)

**Comment by nqhhdev** [comment]
- [ ] Re-test and reproduce for this ticket

**Comment by nqhhdev** [comment]
In new version 2.6.4, can't reproduce
