### ISSUE TITLE
Prevent show action/reply/forward when message in sending/error

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#1567]
### Reproduce:
- when trying to send message 1,
- message 1 in sending,
- reply message 1
issue: 

![Image](https://github.com/linagora/twake-on-matrix/assets/6462404/a1cac8c6-a966-4592-9e36-3cbad4a861c6)

- click on replied message, jump not work

###
- prevent show actions/reply/forward when message in sending or in error

**Comment by QuangHoang1210** [comment]
Passed on IOS 2.5.0
