### ISSUE TITLE
[Bug] Cannot search by link

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1589]
2.4.19, all platforms

1. Copy a link from a chat 
2. Enter it into the search bar 
3. No results found 

Expectation: I can find the link 

https://github.com/linagora/twake-on-matrix/assets/97684890/0578b048-e4b8-4cce-8dfe-2edd71e3dc90

**Comment by QuangHoang1210** [comment]
**Pass IOS 2.5.0**

![IMG_0429](https://github.com/linagora/twake-on-matrix/assets/124866146/34dbee21-64f5-45bb-b827-d4b063dd8177)

**Comment by tprudentova** [comment]
2.5.4. Firefox - not passed 


https://github.com/linagora/twake-on-matrix/assets/97684890/10a685be-2813-44aa-9e2e-a24153eabdf1

**Comment by hieutbui** [comment]
This is a limitation of how the tokenizer/indexer works on the `Matrix` server. Right now, only URL obeying strict syntax is indexed and can be searched.
For more information, check this:
- https://github.com/element-hq/synapse/issues/3024
- https://github.com/bkil/wiki/blob/master/en/dev/matrix-full-text-search.md#url
