### ISSUE TITLE
[Improvement] Own profile in search results

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1592]
If you have your own profile in "Recent" tab, you can click on the avatar. You will see a warning "No permission", and an encrypted chat with oneself will be created. 

Suggestion: in such situation you probably should be redirected to your profile settings?

![photo_2024-03-15_11-39-20](https://github.com/linagora/twake-on-matrix/assets/97684890/cd318e07-d571-4857-9d5a-b59adb145bbe)
![photo_2024-03-15_11-41-45](https://github.com/linagora/twake-on-matrix/assets/97684890/d1f7760b-9db9-4a46-a045-b6cc2f606152)

**Comment by Te-Z** [comment]
Was not able to reproduce this bug since I could not have my own profile on recent search. Is it still relevant ?
In case it is, please be more specific on the way to reproduce this bug

https://github.com/linagora/twake-on-matrix/assets/31937920/f80c57ac-1b4c-4d5b-b5a6-43d3c22ce961
