### ISSUE TITLE
[BUG] When typing and shift + ctrl to get a line break, the internal mouse cursor disappears

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#1602]
Reproduce step:

- Typing something
- Use `shift` + `enter` many time to get a line break
- Can't see cursor in composer

https://github.com/linagora/twake-on-matrix/assets/99852347/9d137251-29ee-41ac-bb8f-fc17b2418ef2

**Comment by sherlockvn** [comment]
- [ ] This is happend when user shift + enter many times, so that it gets many lines, then the cursor is deep down at the bottom of composer
