### ISSUE TITLE
[ANDROID only] Jump to lastest message icon still display when user jump from new notification message in case not yet open direct chat / group chat before

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1612]
OS:  Android only
Device: Mobile
Twake version:  2.4.22

*Precondition:
- User A and user B in group chat / direct chat
- User A not yet open to load message in the group chat / direct chat before

### *Reproduce Step:
1, User B send a new message to group chat / direct chat
2, User A click on notification of new message

### **Actual:** 
- Jump to correct message in group chat / direct chat
- However, the jump to lastest message icon still displaying even if user click on it

### **Expected:** 
- Jump to lastest message icon will be hidden when user jump to the lastest message
- It will be displaying if user not jump to the lastest message
<behaviour on IOS is correctly>

**Android**

https://github.com/linagora/twake-on-matrix/assets/124866146/f4ada90d-2e7e-467d-bf08-a98c7eb99a33

**IOS**

https://github.com/linagora/twake-on-matrix/assets/124866146/8e13945d-6710-4e58-8dbf-5020b24b7202

**Comment by Te-Z** [comment]
Could not reproduce it:

https://github.com/linagora/twake-on-matrix/assets/31937920/5dcc3da7-f4d5-4d15-afb0-807de6e2cbf3
