### ISSUE TITLE
[Improvement] Login splash screen take too long

### ISSUE THREAD

**Issue by sherlockvn** [linagora/twake-on-matrix#1631]
### Desc:
When log in in web platform, after log in successfully, user is redirect back to Twake web app, but the onAuthScreen is not in the screen right away, instead the splash screen. The splash screen take too long to be disappear.
### Evidence:

https://github.com/linagora/twake-on-matrix/assets/43041967/9caee48f-6520-4f7e-927a-3f09b3a3db1a

### DOD:
- [ ] Find a way to remove or reduce the splash screen time.

**Comment by hoangdat** [comment]
- also have this page in logout action

**Comment by sherlockvn** [comment]
### Root cause:
- When we go to sign in page, we have disposed all resources from flutter framework to render the home page. And we will done sign in, we return back to `onAuthRedirect`, this page will need to load all flutter resources again. The different is that: these resources have been cached. The time it takes to render the `onAuthRedirect` is total times needed to load the flutter resources.
### Demo:

https://github.com/linagora/twake-on-matrix/assets/43041967/49b27625-562d-4851-90bc-47b61872186e

### Solutions: ?
- I have think about maybe we open the sign in page in a iframe which will on top of the home page, with this solution, its may add the additional complexity to the app
- `prefetch, prerender` in header tag, this is not necessary, because we get all resources from cache request already
- `InAppWebView` when open the sign in page ?

**Comment by sherlockvn** [comment]
https://github.com/linagora/twake-on-matrix/assets/43041967/1872a3a9-912e-4acd-9f28-01bf154e1f7c
