### ISSUE TITLE
[IOS / Android] “Tap to allow access to your Gallery” button is not in center of its container

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1644]
**ENV:** 
- Android / IOS
- Twake v 2.4.22

**Precondition:**
- User not yet allow Twake to access photo on device

**Step:**
1- User create direct chat / group chat
2- User click add icon to attach image 

**Actual:** 

- “Tap to allow access to your Gallery” button is not in center of its container
- Break the line after “access”.

**Expected:** 

- It's align with its container
- Not break the line after access

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/4c1630d5-543f-48e6-ab6c-8935027e49d1)

**Comment by DianaPotokina** [comment]
![Image](https://github.com/linagora/twake-on-matrix/assets/78213416/f8fac504-7c35-4e5c-9ed3-6582fa537300)

Dear collegues, in this screen it's not important for the moment to fix size of button, here we need to delete button "gallery" (we are already in gallery" and we need to add button "camera". Totally there are 2 buttons "camera" and "documents". And I send e-mail where I ask don't do task about design, we will do it after global design rewiev of @Bobpodvalnyi. Thank you
