### ISSUE TITLE
[Android / IOS] Change two options at Create Chat screen

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1648]
**ENV:** 
- Android / IOS
- Twake v 2.4.22

**Step:**
1- User click on pencil icon

**Actual:** 

- There is only option create new group chat

**Expected:** 

- It should have 2 options: 
+ New Chat -> For group chat
+ New Encrypted Direct Chat -> For direct chat

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/dfba06e4-835c-40b0-8336-902b28b3b04d)

**Design:**

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/459ef70f-d650-4e92-860c-aed4388bdd43)

**Comment by tprudentova** [comment]
It's done exactly as tg
