### ISSUE TITLE
[Bug] The unread position is not correct when open the chat

### ISSUE THREAD

**Issue by sherlockvn** [linagora/twake-on-matrix#1651]
### DESC:
- When open the chat which have unread messages, the chat is not scroll to the position of the first unread message.

**Comment by hoangdat** [comment]
Maybe it is fixed in: #1995 
Please re-verify with new version.

**Comment by tprudentova** [comment]
@hoangdat 

When I open a chat with unread messages, I jump to the wrong message (and that wrong message is highlighted). This could be a separate bug, maybe? Pls take a look 

https://github.com/user-attachments/assets/7ced7c8c-0dca-4fe5-a2d8-5226a4754cf3
