### ISSUE TITLE
[Android / IOS] User cannot download video

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#1664]
**ENV:** 
- IOS / Android / WEBPC
- Twake v 2.4.22

**Precondition:**
- Existed video was sent in chat conversation

**Step:**
1- User go to chat 
2- User click to preview video
3- User click three-dot options
4- User select Saved file 

**Actual:** 

- No Toast displayed
- Cannot save video to device's gallery
- Dropdown option is not disappeared

**Expected:** 
- Save file should be change to Save video
- Toast is displayed
- Video saved successfully to device's gallery but dropdown option is disappeared

https://github.com/linagora/twake-on-matrix/assets/124866146/9fe8bf09-7070-4f80-aa4d-38151b94cb95

**Comment by sherlockvn** [comment]
fix in newer version
