### ISSUE TITLE
[BUG] Can't open draft chat for external account on Contact Tab

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#1671]
### Desc

Twake version: 2.4.22

https://github.com/linagora/twake-on-matrix/assets/99852347/ab9913c7-ea67-4b63-af9c-0811a4069b4e

### DoD:
- [ ] Open draft chat for external account on Contact tab

**Comment by hieutbui** [comment]
- Fixed on: #1930
