### ISSUE TITLE
[Search] Can search matrix ID

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#1735]
### Desc:

- Rn it’s only possible to start a chat with exact Matrix ID through Create → Direct chat → Search

### DoD:

- [x] Can search matrix Id `@someone:abc.com`

**Comment by Te-Z** [comment]
@hoangdat @nqhhdev  IMO we should handle not found matrix ids somehow. Any idea ?

**Comment by hoangdat** [comment]
> @hoangdat @nqhhdev IMO we should handle not found matrix ids somehow. Any idea ?

Good idea, IMO we should show error directly in draft chat? is it possible?

**Comment by tprudentova** [comment]
https://github.com/linagora/twake-on-matrix/assets/97684890/bb5ea92e-180b-417d-944a-fc11060905aa

You still can't create a DM via exact Matrix ID through the Contacts tab

**Comment by Te-Z** [comment]
Remove text below the search bar if no results -> check with BAs for design approval

**Comment by hieutbui** [comment]
I think right now, the text is removed.

https://github.com/linagora/twake-on-matrix/assets/80142234/8fb563d9-b087-42b6-8fff-9ed184fc7bdf

**Comment by Te-Z** [comment]
> I think right now, the text is removed [@Te-Z](https://github.com/Te-Z)
> 
>  search.mp4

Yes it has been done by Khaled. But wdyt about this problem https://github.com/linagora/twake-on-matrix/issues/1735#issuecomment-2137412528
