### ISSUE TITLE
[Improve] upload thumbnail when create group with avatar also

### ISSUE THREAD

**Issue by sherlockvn** [linagora/twake-on-matrix#1746]
### Description:
- Right now, when upload avatar for group or change avatar for whole group, we use original dimension of image to display in the screen. This is not efficient for web platform. The create group avatar API have an option to set avatar thumbnail also. We should take advantage of that to avoid memory usage in web.

### Reference:
https://spec.matrix.org/v1.10/client-server-api/#mroomavatar

![Image](https://github.com/linagora/twake-on-matrix/assets/43041967/14443198-4d2e-484c-91f8-3344493faa70)

### DOD:
- [ ] Create thumbnail for thumbnail avatar group
- [ ] Upload thumbnail for group
- [ ] Use thumbnails to display Avatar group in chat list view and other places

**Comment by hoangdat** [comment]
crop image will make it well
