### ISSUE TITLE
[UI/UX] Improve when upload image/video file

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#1751]
### Desc: 

- When upload image/video file then send fake event first and add task to queue
- Thumbnail + file will be gen and upload together → then update thumbnail in view
- Display cancel token and progress upload
- If upload failed ⇒ display error and update UI and remove task on queue

### DoD:
- [ ] Gen and upload thumbnail
- [ ] Update correctly uploading video/image
- [ ] Display cancel token and progress upload
- [ ] Cancel uploading file => remove fake event
- [ ] Error handling upload fail

**Comment by Te-Z** [comment]
might be related to https://github.com/linagora/twake-on-matrix/issues/1806
