### ISSUE TITLE
[MOBILE] Save to gallery menu action not work in chat screen 

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#1752]
### Desc:

- Save to gallery menu action not work in chat screen

https://github.com/linagora/twake-on-matrix/assets/99852347/6d7d1d0f-0b1c-404a-ab3b-2d3b39554817

### DoD

- [ ] Can download image/video when clicking on save to gallery in context menu

**Comment by sherlockvn** [comment]
- Image from linux platform can't be saved (image in video)

**Comment by hoangdat** [comment]
any update on this ticket @nqhhdev

**Comment by nqhhdev** [comment]
> any update on this ticket [@nqhhdev](https://github.com/nqhhdev)

Just fixed UI side effect for context menu: #1753
