### ISSUE TITLE
[Bug] members list of group chat is not updated correctly

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#1773]
### Desc:
- after remove some people in chat in other device, member list in this device is not updated 

### DoD:
- [ ] update member list correctly

**Comment by hoangdat** [comment]
- [ ] load member mechanism: why need button load more? How to improve it?

**Comment by Te-Z** [comment]
Hi @sherlockvn I saw this one has been moved to "In Review" but I can't find the PR. Please link this issue in the PR description
