### ISSUE TITLE
Twake uploads to incomplete URI

### ISSUE THREAD

**Issue by cyrneko** [linagora/twake-on-matrix#1779]
When sending media, Twake tries to upload media like this:

```
/_matrix/media/v3/upload?fileName=example.png
```

This should of course be:

```
https://example.com/_matrix/media/v3/upload?fileName=example.png
```

Relevant log is as follows:
```
Error: Invalid argument(s): No host specified in URI /_matrix/media/v3/upload?fileName=Screenshot_20240519-154639_Twake+Chat.png
```

**Comment by Te-Z** [comment]
Hi @TGRush thanks for your feedback.
Can you please give more insight so we can reproduce your bug ?

**Comment by TGRush** [comment]
> Can you please give more insight so we can reproduce your bug ?

Essentially, it seems that when uploading media, Twake tries uploading to no domain, just to the intended endpoint, which makes the SDK throw an error.

Note that I tested this with tchncs.de as the homeserver, so it should be something like `https://tchncs.de/_matrix/media/v3/upload?fileName=example.png` instead of only the last bit (`/_matrix/media/v3/upload?fileName=example.png`)

**Comment by Te-Z** [comment]
Did you properly set your `config.json` file as in this example ? 
https://github.com/linagora/twake-on-matrix/blob/main/config.sample.json

**Comment by TGRush** [comment]
> Did you properly set your `config.json` file as in this example ? https://github.com/linagora/twake-on-matrix/blob/main/config.sample.json

I did not self-host or build Twake myself, I used the latest GitHub release as of writing and simply inserted tchncs.de as the homeserver.

**Comment by Te-Z** [comment]
Hi @TGRush could you retry with latest version ?

I tried and had no problem:

```
I/flutter (10620): *** Response ***
I/flutter (10620): uri: https://matrix.tchncs.de/_matrix/media/v3/upload?fileName=1716473016764IMG-20240503-WA0001.jpg_thumbnail.jpg
I/flutter (10620): statusCode: 200
```

**Comment by cyrneko** [comment]
> Hi @TGRush could you retry with latest version ?
> 
> I tried and had no problem:
> 
> ```
> I/flutter (10620): *** Response ***
> I/flutter (10620): uri: https://matrix.tchncs.de/_matrix/media/v3/upload?fileName=1716473016764IMG-20240503-WA0001.jpg_thumbnail.jpg
> I/flutter (10620): statusCode: 200
> ```

Seems that this one indeed (2.5.3) indeed works. I must've downloaded a bad build.
