### ISSUE TITLE
Improve display contacts on multiple homeserver

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#1791]
### Desc:

Case: 1
- Logged with account on `ToM` server.
- Click on Contacts tab →  get all `ToM` contacts
- I add another account on another server (TWP, matrix, etc.) is not supported for Twake
- Click on Contacts tab → Still display all `ToM` contacts

Case: 2
- Logged with account on other servers (TWP, matrix, etc.) not support `ToM`.
- Click on Contacts tab →  only get `phone book contact`
- I add another account on `ToM` server.
- Click on Contacts tab → Can't get `ToM` contacts

### DoD:

- [x] Only display `ToM` contacts for homeserver is supported Twake
- [x] When we switch or add another account need to refresh all contacts (`ToM`, phone book, recent contacts)
- [ ] For web only show `ToM` contacts is server supported and recent contacts

**Comment by tprudentova** [comment]
https://github.com/linagora/twake-on-matrix/assets/97684890/4169652e-ba95-4f1f-9f13-d30a293cd086

I can even create a DM with someone from the company, while using my **personal** account
