### ISSUE TITLE
Change loading dialog style

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#1795]
### Desc:
- Fork from upstream: [Krille-chan Repo](https://github.com/krille-chan/future-loading-dialog) [Linagora Repo](https://github.com/linagora/future-loading-dialog)
- Apply Linagora style for it

### Design

https://www.figma.com/design/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?node-id=24467-26025&t=035EhxOlxnXFeGWQ-0

### DoD:
- [x] Flexible error handling: retry, close, ....
- [x] Apply new Linagora style

**Comment by nqhhdev** [comment]
Hi @Te-Z, could you have me ping Bob about this case?

**Comment by Te-Z** [comment]
@nqhhdev I found this on figma


![Image](https://github.com/linagora/twake-on-matrix/assets/31937920/727b81d2-cdbd-4f8c-96b0-882e8566c749)


WDYT ?
