### ISSUE TITLE
Standardlize Appbar and Appgrid popup

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#1796]
### Desc:
- https://www.notion.so/linagora/TWP-nav-bars-with-apps-grid-4861683b20e142ebaae6e7a348547652

- Do not show current app's icon
- Remove for now:
   - calendar
   - visio
   - contacts 

Make sure each icons has the same size

Wait for design before working on this.

### DoD:
- [ ] apply style 
- [ ] make the appgrid can work with public link of icon

**Comment by Te-Z** [comment]
Do not show current app's icon

**Comment by Te-Z** [comment]
Remove for now:
- calendar
- visio
- contacts
