### ISSUE TITLE
[Bug] When adding an account, the basic first page should be opened

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1805]
Current behaviour: clicking Add account opens the page for entering home server 

Expectation: I see the page with "Create Twake ID", "Sign in" and "Use your company server"

https://github.com/linagora/twake-on-matrix/assets/97684890/91523e86-3db0-47dd-a924-d4215c3f1386

**Comment by nqhhdev** [comment]
Current version, we're fixed it.

This is a demo

https://github.com/linagora/twake-on-matrix/assets/99852347/ea36b8f9-b48c-42c0-ae5a-11f812273bfe
