### ISSUE TITLE
My Profile image can not update after I change my profile image

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#181]
### Desc:
1. Settings
2. Change profile image
3. Back to Chat List screen
4. Profile image is not updated

### DoD:

**Comment by nqhhdev** [comment]
- Same issue #159

**Comment by QuangHoang1210** [comment]
Closed as passed in case view updated profile image in Chat List screen. 
But not passed in case view updated profile image in Profile screen. -> follow up by this ticket https://github.com/linagora/twake-on-matrix/issues/757
