### ISSUE TITLE
[Bug] [MOBILE] Remove X from the search bar when it's empty

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1812]
Android, 2.5.8

1. Open Chats tab 
2. Click on the search bar 
3. There's an X in it even though I haven't started typing 

Expectation: X only appears when there's something in the search bar 

![photo_2024-05-28_10-27-36](https://github.com/linagora/twake-on-matrix/assets/97684890/81979a1e-13fa-4373-a44c-678be11e9073)

**Comment by tprudentova** [comment]
Create -> Search; Create -> New group chat -> Search; Contacts tab -> Search
The bug still exists in these search bars. Please make sure to fix it everywhere, thanks! <3

https://github.com/linagora/twake-on-matrix/assets/97684890/824095aa-f7e9-4ec5-aa57-bda38b4f86cf

https://github.com/linagora/twake-on-matrix/assets/97684890/b1771f3b-8940-4b00-867d-62fd0caf0919

https://github.com/linagora/twake-on-matrix/assets/97684890/7c0ca3b5-d7f4-408a-89a9-07e4087e566e

**Comment by tprudentova** [comment]
@Te-Z

**Comment by Te-Z** [comment]
@KhaledNjim can you take a look at these ?
