### ISSUE TITLE
Change event description for pinned files

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1813]
Current: "*folder icon* Name Surname sent a file"

Expected: "filename.ext"

<img width="822" alt="Screenshot 2024-05-28 at 10 30 54" src="https://github.com/linagora/twake-on-matrix/assets/97684890/d15175d1-187c-4d6d-9c21-bb0722b6f30a">

**Comment by nqhhdev** [comment]
### DoD

- [ ] Get info of file then update decs of pinned message on Chat
- [ ] Update in Chat list item preview also
- [ ] Update in reply message also (Message and composer)

**Comment by Te-Z** [comment]
![Image](https://github.com/user-attachments/assets/dbc25524-678f-4165-9735-90d14b8e8754)

**Comment by nqhhdev** [comment]
Hi @tprudentova, this is not a bug. I updated title and label to `improvements`
