### ISSUE TITLE
[Bug] Sending media works very slow

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1823]
Sometimes it takes around 30 seconds to send an image 

https://github.com/linagora/twake-on-matrix/assets/97684890/c960af01-3a17-4ce6-b06e-a1555c988c8e

**Comment by Te-Z** [comment]
IMO those tickets will help handle this case:
https://github.com/linagora/twake-on-matrix/issues/1758
https://github.com/linagora/twake-on-matrix/issues/1759
https://github.com/linagora/twake-on-matrix/issues/1760
https://github.com/linagora/twake-on-matrix/issues/1761
https://github.com/linagora/twake-on-matrix/issues/1751

I add them to sprint 14
