### ISSUE TITLE
[Bug] [MOBILE] Cannot download files

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1824]
Android, 2.5.8 

Files aren't downloaded after clicking Download 

https://github.com/linagora/twake-on-matrix/assets/97684890/46503234-e23d-456e-adb5-3f08c574d6ec

**Comment by sherlockvn** [comment]
- It saids that found 5 new files, can you show me the `Downloads` folder.
### Expected:
- The file will be saved inside `Downloads` -> `Twake chat` folder

**Comment by sherlockvn** [comment]
https://github.com/linagora/twake-on-matrix/assets/43041967/585aeb7f-04ce-466c-9156-f0dce44d7543

We do the same UX as the Telegram do

**Comment by tprudentova** [comment]
Ohhhhh okay okay, I found them, they were hidden really well :D
