### ISSUE TITLE
[Bug] [MOBILE] Search for unencrypted messages doesn't work 

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1828]
Pre-prod 

1. Go to the Chats tab 
2. Try to search for words that you used in conversations 
3. No results 

https://github.com/linagora/twake-on-matrix/assets/97684890/7d453f07-0e16-4a93-a347-00efabd0f9dd

**Comment by hoangdat** [comment]
some days, our platform in linagora is not stable. `No more disk` error. Please test it again now to verify.

**Comment by tprudentova** [comment]
@hoangdat still happens :(

**Comment by Te-Z** [comment]
IMO those are related https://github.com/linagora/twake-on-matrix/issues/1786
