### ISSUE TITLE
[Bug] Change text when a user has no contacts

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1830]
1. Click Create 
2. You see the bee and the text that no results have been found, but no search request has been entered... 

Expectation: If a user has no contacts, we should show something like "You don't have any contacts yet"

![photo_2024-05-30_09-12-02](https://github.com/linagora/twake-on-matrix/assets/97684890/fc69b84f-0d85-43a3-b3dc-87ec0d37b076)

**Comment by tprudentova** [comment]
<img width="388" alt="Screenshot 2024-07-01 at 12 35 15" src="https://github.com/linagora/twake-on-matrix/assets/97684890/e37cab95-6579-4052-8043-4647dc7cce86">
![photo_2024-07-01_12-34-37](https://github.com/linagora/twake-on-matrix/assets/97684890/50a4830b-dc8a-4b64-a732-23ee7141cbd6)

Reproduced on 2.5.9

@Te-Z

**Comment by Te-Z** [comment]
@KhaledNjim can you take a look at these ?

**Comment by Te-Z** [comment]
@tprudentova my bad: this has been merged but is not in the beta version yet (see changelog -> https://github.com/linagora/twake-on-matrix/blob/v2.5.9/CHANGELOG.md ). It will be available in the next release
