### ISSUE TITLE
[Bug] Profile avatar isn't updated correctly 

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1834]
I changed the avatar, but the old one is still displayed in the multi account tab 

![photo_2024-05-30_09-12-07](https://github.com/linagora/twake-on-matrix/assets/97684890/474a9ffc-a4b9-4ca7-a5f0-6a23db9b0427)

**Comment by tprudentova** [comment]
Same with Display name

**Comment by sherlockvn** [comment]
### DESC:
The multiple account selection is using the wrong client, so that it have wrong name and avatar
### DOD:
- [ ] Fix the avatar and displayname wrongly in multiple accounts

**Comment by tprudentova** [comment]
Doesn't only happen with multiple accounts. I haven't logged into a staging account for a while, after the login I see the same old avatar that I had on my linagora account like a month ago

https://github.com/linagora/twake-on-matrix/assets/97684890/20b60531-80c9-4374-90e8-50de68a70c1b
