### ISSUE TITLE
[Bug] Cannot mark chat as Read

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1835]
Firefox, 2.5.4

1. Mark chat as unread 
2. Try to mark chat as read 
3. Error

https://github.com/linagora/twake-on-matrix/assets/97684890/23e1bb0c-02e7-484b-b74e-3e756c6a06a2

**Comment by tprudentova** [comment]
The issue is still there, just saying............................. 

https://github.com/user-attachments/assets/90199e88-ab57-4d00-8256-ea4f94b5221f

**Comment by Te-Z** [comment]
@guimard this is because of an error 500 on set read marker on https://chat.stg.lin-saas.com/

![Capture d’écran du 2024-07-22 17-20-23](https://github.com/user-attachments/assets/e613c4b6-116d-473f-b5e4-6f349757fc78)

**Comment by guimard** [comment]
I just updated dev platform, could you retry ?

**Comment by Te-Z** [comment]
@guimard still happens
![image](https://github.com/user-attachments/assets/e6cdec90-1e30-4993-b78e-a46f49ccaf73)

**Comment by guimard** [comment]
The Matrix log is unclear. Do you have same issue on linagora.com ?
```json
{
"log":"Failed handle request via 'ReadMarkerRestServlet': <XForwardedForRequest at 0x7f83299aef10 method='POST' uri='/_matrix/client/v3/rooms/!gBEjwspOzGqPdJKMgK%3Astg.lin-saas.com/read_markers' clientproto='HTTP/1.1' site='8083'>",
"namespace":"synapse.http.server",
"level":"ERROR",
"time":1721801381.21,
"request":"POST-107459",
"ip_address":"****",
"site_tag":"8083",
"requester":"@test.tez:stg.lin-saas.com",
"authenticated_entity":"@test.tez:stg.lin-saas.com",
"method":"POST",
"url":"/_matrix/client/v3/rooms/!gBEjwspOzGqPdJKMgK%3Astg.lin-saas.com/read_markers","protocol":"HTTP/1.1","user_agent":"Dart/3.4 (dart:io)","server_name":"stg.lin-saas.com",
"exc_type":"AssertionError",
"exc_value":""
}
```

**Comment by Te-Z** [comment]
No It works as expected on linagora.com

**Comment by guimard** [comment]
Hi @Te-Z , can you tell me if :
 - error is on one channel or erevy
 - error exists or not on linagora.com

**Comment by hoangdat** [comment]
- work well on https://chat.stg.lin-saas.com v2.6.5
