### ISSUE TITLE
[Improvement] Move the Shared media part to the Profile part

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1836]
Rn we need to perform an additional step to open media shared with a user. Compare with telegram 

<img width="846" alt="Screenshot 2024-05-30 at 11 38 31" src="https://github.com/linagora/twake-on-matrix/assets/97684890/7b318828-b2b6-4aa4-8dd8-ead1a71f0c9e">

![photo_2024-05-30_11-40-54](https://github.com/linagora/twake-on-matrix/assets/97684890/d4c5e8c6-cf01-4bed-89c3-817f1db7e5fc)

**Comment by Te-Z** [comment]
@Bobpodvalnyi What do you think ?

**Comment by tprudentova** [comment]
@Te-Z let's make tabs both in mobile and web. Similar to what we have in group chat info 

<img width="292" alt="Screenshot 2024-06-05 at 15 37 57" src="https://github.com/linagora/twake-on-matrix/assets/97684890/5e306482-6b1b-4696-8d9f-61df627aba16">
