### ISSUE TITLE
[Bug] Change naming in Forward window

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1837]
Add -> Send

<img width="517" alt="Screenshot 2024-05-30 at 11 46 21" src="https://github.com/linagora/twake-on-matrix/assets/97684890/50154199-d319-4668-9015-dae34d950e06">

**Comment by nqhhdev** [comment]
Current version 2.5.9, We're removed dialog forward → Change it to screen forward.
