### ISSUE TITLE
[Bug] Clicking Report message doesn't do anything  

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1838]
https://github.com/linagora/twake-on-matrix/assets/97684890/0329e91f-2b15-4151-95b6-2e9630e8f01a

**Comment by hieutbui** [comment]
I think it already fixed on #1842 

https://github.com/linagora/twake-on-matrix/assets/80142234/f239170e-90c3-45de-b184-bdd9b5d9c13e
