### ISSUE TITLE
Can't close invitation dialog in Chat

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#1841]
### Desc:

- Open group chat → Open chat detail
- Click on `Add new members` → show invitation dialog
- Click on `X` icon to close dialog => Can't close dialog and pop off Chat screen

https://github.com/linagora/twake-on-matrix/assets/99852347/8d1d5d5d-571d-4bf2-8fa6-cd7e90ed4cd7

### DoD

- [ ] Close invitation dialog 
- [ ] Can't pop off Chat screen

**Comment by hieutbui** [comment]
Confirm it also happens on main:

https://github.com/linagora/twake-on-matrix/assets/80142234/d809e207-f35d-46ce-b6e2-facd8a1758be
