### ISSUE TITLE
[Bug] [Android] Distorted images when using image capturer

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1844]
Android, 2.5.8 

1. Open the chat 
2. Click Attach 
3. Open image capturer and take a photo 
4. Send 
5. Image preview is distorted 

![photo_2024-05-31_09-55-20](https://github.com/linagora/twake-on-matrix/assets/97684890/c568171c-80f4-4cb7-a4aa-3cace71a115e)

**Comment by sherlockvn** [comment]
Confirmed

**Comment by nqhhdev** [comment]
### NOTED: Specific for android but test for iOS, Web also

### DoD:

- [ ] Handle case width and height when take a photo

**Comment by sherlockvn** [comment]
The bug come from the package, let wait for them to response
https://github.com/fluttercandies/flutter_wechat_camera_picker/issues/266

**Comment by sherlockvn** [comment]
Actually, i test again in the android phone in version 2.6.0, it works fine now. Can you check again:


https://github.com/user-attachments/assets/291c48ed-e2fa-474f-ad50-8633d7018338

**Comment by sherlockvn** [comment]
hi @Te-Z, can you retest again in version 2.6.0 (not in my PR) in your android device to see the problem persist ?

**Comment by sherlockvn** [comment]
it doesn't happend in real android device
### Device information:
- name: ZTE blade V50 design
- Android 13

https://github.com/user-attachments/assets/b1a68f21-4cc3-4f37-8b44-4a457ffa178e


https://github.com/user-attachments/assets/eec60e65-c40a-4499-93a2-75ec266d96f2

**Comment by sherlockvn** [comment]
Hi @tprudentova, can you test again in real android device, and let me know the information of your phone

**Comment by tprudentova** [comment]
Hi @sherlockvn 
Still happens on my device :( 2.6.1, Redmi Note 12 Pro; Xiaomi HyperOS 1.0.4.0.THGRUXM


https://github.com/user-attachments/assets/6eee5973-c0aa-42f4-9ea9-236815ce178d
