### ISSUE TITLE
[Bug] [IOS] Images and files aren't sent

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1845]
IOS, 2.5.8 

Cannot send files or media 

![photo_2024-05-31_09-55-39](https://github.com/linagora/twake-on-matrix/assets/97684890/22916069-97dd-43b5-9d84-d852ef2736c3)

**Comment by nqhhdev** [comment]
Hi @tprudentova,

Hopefully, you can test it on new version (2.6.0) and make sure that issue from BE or FE.

You can test on `web` Then you can get the log (Developer tool) on the web to know where the error came from.

If you need to support, ping me. Thanks

**Comment by nqhhdev** [comment]
@tprudentova pls help me check it again.
