### ISSUE TITLE
[Chat] Status of chat overflow text

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#187]
### Desc:

GIVEN: User A chat with user B
WHEN: User B typing
THEN: Status of chat overflow text

![Simulator Screenshot - iPhone 14 Pro - 2023-06-22 at 13 14 28](https://github.com/linagora/twake-on-matrix/assets/99852347/ad1c4b2d-f361-4b99-8f05-06d9e301b44e)

### DoD:
- [ ] status text must be flexible

**Comment by QuangHoang1210** [comment]
passed
