### ISSUE TITLE
Can't send svg file on twake

### ISSUE THREAD

**Issue by shepilov** [linagora/twake-on-matrix#1876]
There is a problem generating previews for some image formats, SVG for example. And hence there is no way to upload SVG as an image or just as a file

**Comment by sherlockvn** [comment]
- [ ] Test again with multiple image formats and multiple platform, each platform support different file format

**Comment by sherlockvn** [comment]
Already fix in version 2.5.9 in the #1806

**Comment by sherlockvn** [comment]
@Te-Z i think we can release new version in web with #1806 fix, wdyt ?
