### ISSUE TITLE
[Notification] Can't open notification when open Media in chat details

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#1878]
- Twake version: 2.5.8
- Android/ iOS

#### Case 1:

1. Open Twake chat
2. Open chat `A` → Open chat details → Open media tab → open the image/video
3. Received a notification from another chat
4. Click on notification → Can't open another chat just close preview image/video
5. Click on back button → back to another chat

https://github.com/linagora/twake-on-matrix/assets/99852347/c31ba7c6-18b4-4865-be1e-906288bb6c09

### Case 2:

1. Open Twake chat
2. Open chat `A` →  Open the image/video
3. Received a notification from another chat
4. Click on notification → Can't open another chat just close preview image/video

**Comment by Te-Z** [comment]
Check go_router and navigator
But be careful of side effects

**Comment by hoangdat** [comment]
1. how to fix the problem relate to conflict of `navigator` and `go_route`?
2. integration-test ???

**Comment by tprudentova** [comment]
@hoangdat 

https://github.com/user-attachments/assets/2ce5b110-02ec-41a3-8e51-26969ba5b255

You can jump to the notification now, but the previous message is highlighted, not the one from the notification

**Comment by nqhhdev** [comment]
Fixed #2069
