### ISSUE TITLE
Update chat list UI [part 1]

### ISSUE THREAD

**Issue by Te-Z** [linagora/twake-on-matrix#1886]
DOD:
- [x] move avatar to bottom navigation bar
- [x] update bottom navigation bar icons
- [x] center title

![Image](https://github.com/linagora/twake-on-matrix/assets/31937920/97b31324-0e20-4995-9e32-1b62370758c1)

**Comment by Te-Z** [comment]
Need:
- send file/image/video
- user typing
- draft chat

**Comment by Bobpodvalnyi** [comment]
here is layouts https://www.figma.com/design/uLw3iWnOEGaRlJnfPz4Pv0/Twake-[Matrix]?node-id=25783-37873&t=kJPqLpeDQtys3kDq-0
pls also look at notion link in figma with specs 
@Te-Z @KhaledNjim

**Comment by Te-Z** [comment]
Issue about chat list item update: https://github.com/linagora/twake-on-matrix/issues/1902
