### ISSUE TITLE
[Urgent] iOS is forced to logout many times

### ISSUE THREAD

**Issue by Te-Z** [linagora/twake-on-matrix#1900]

**Comment by Te-Z** [comment]
@nqhhdev @sherlockvn can one of you take this issue urgently please ? Ping Dat if

**Comment by sherlockvn** [comment]
Can't reproduce in twake version 2.5.9

**Comment by Te-Z** [comment]
@hoangdat do you have more informations about this one ?

**Comment by sherlockvn** [comment]
i can reproduce now, rarely happend and i'm trying to put log for debugging it

**Comment by sherlockvn** [comment]
i can only reproduce in the specific group `Chat dev team`
