### ISSUE TITLE
Config PushGateway for Matrix at Linagora platform

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#191]
### Desc:

- Push work well in `tom-dev` platform, but not well in `matrix.linagora.com`

### DoD:

- Fix PushGateway to work with `matrix.linagora.com`

**Comment by hoangdat** [comment]
Android: Done

**Comment by hoangdat** [comment]
Right now using *.xyz

**Comment by pm-McFly** [comment]
> Right now using *.xyz

still the case...

https://github.com/linagora/twake-on-matrix/issues/297

**Comment by hoangdat** [comment]
really? why you think that?

**Comment by pm-McFly** [comment]
> really? why you think that?
> 
> Right now, it is ![image](https://private-user-images.githubusercontent.com/6462404/401326852-e0a6a213-1d11-46a6-bdd6-6d77f6f16a96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY5NTAxNzgsIm5iZiI6MTczNjk0OTg3OCwicGF0aCI6Ii82NDYyNDA0LzQwMTMyNjg1Mi1lMGE2YTIxMy0xZDExLTQ2YTYtYmRkNi02ZDc3ZjZmMTZhOTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMTVUMTQwNDM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmY4YWNjOGY0ZTgwNTdhNjcwMzQzNGY3NWNmYThkYzJkZTk5MjVlMGRjYzkwZGFjMzY3NWRjNDU4MzQ4MDhjNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.6_mkey7Czb9HI0BwxuQn6n5Gm_CLKsk4nA4B79DuVxs)

lin-saas.dev is the new name of tom-dev.xyz, but the VM and services are just about the same ;)
