### ISSUE TITLE
[Bug] Media isn't sent if the preview hasn't loaded

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1915]
2.5.9, Firefox, chat.stg.lin-saas.com

1. Click Attach
2. Select several images 
3. Click Send in the pop-up before the previews load 
4. The images aren't sent 

Expectation: they are 

https://github.com/linagora/twake-on-matrix/assets/97684890/505877a1-f263-477f-9e96-2a320c7561af

**Comment by nqhhdev** [comment]
Hi @tprudentova, pls verify it on new version, thanks.

**Comment by nqhhdev** [comment]
@tprudentova This is an issue about can't send or can't load?

**Comment by nqhhdev** [comment]
> @nqhhdev still happens on 2.6.0
> 
>  Screen.Recording.2024-08-22.at.12.29.16.mov

This is not version 2.6.0, on beta.twake.app still version 2.5.9. Because Tez has not released a new version on the web yet.

**Comment by tprudentova** [comment]
> > @nqhhdev still happens on 2.6.0
> > Screen.Recording.2024-08-22.at.12.29.16.mov
> 
> This is not version 2.6.0, on beta.twake.app still version 2.5.9. Because Tez has not released a new version on the web yet.

This is staging, 2.6.0. The media file is never loaded thus never sent, if you reload the page, it simply disappears
