### ISSUE TITLE
[Bug] The source message of a reply isn't highlighted when you jump to it

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1932]
Firefox, 2.5.9
Android, 2.5.9

1. Open a chat, reply to a message 
2. Click on the source message to jump to it 
3. The source message isn't highlighted

Expectation: the source message is highlighted 

https://github.com/linagora/twake-on-matrix/assets/97684890/07e96ca8-e30e-4cff-bcd3-80784114bc26

**Comment by tprudentova** [comment]
Same is when you jump to messages from search inside a chat 


https://github.com/linagora/twake-on-matrix/assets/97684890/5f75215e-1a6e-4ca9-a5a0-9248bf167474

**Comment by hoangdat** [comment]
hi @sherlockvn please handle it also in #1998
