### ISSUE TITLE
[Bug] Mute chat doesn't work in some cases

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1934]
Android, 2.5.9

1. User receives a notification to a chat
2. User jumps to that notification 
3. User mutes the chat 
4. User receives a new message to that chat 
5. The notification is still received 

Expectation: if a chat is muted, user doesn't receive notifications

https://github.com/linagora/twake-on-matrix/assets/97684890/6b00ec6c-5050-4ba3-b6d6-c1a7f2cb2eda

**Comment by nqhhdev** [comment]
Hi @tprudentova,

I tested this case on new version (2.6.0) and works well for my case.
Pls help me verify it again on new version.

**Comment by hoangdat** [comment]
Hi @tprudentova please verify in new version
