### ISSUE TITLE
[Bug] Wrong screen is displayed when sharing an image from gallery

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1936]
Android, 2.5.9 

1. Open chats screen, search some word 
2. Leave the app without closing the search screen 
3. Open your device's gallery -> Share by -> Share by Twake 
4. The old search screen is displayed instead of the sharing screen 

Expectation: The sharing screen is displayed straight away 

https://github.com/linagora/twake-on-matrix/assets/97684890/cb85f8be-1127-40c9-9e0c-794f14a4b2b1

**Comment by nqhhdev** [comment]
### DoD

- [ ] Push share screen into current stack
