### ISSUE TITLE
Out of sprint 15

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#1945]
Thu 11 Jul
- [ ] - [ ] Privacy policy update - spent time : 1 HD
- [ ] Meetings - spent time

**Comment by Te-Z** [comment]
Google privacy policy:
- investigation about what google means about "images information" problem -> 
  - no clear informations found on internet
  - no clear informations on google console found (Data safety + privacy policy checked)
- message sent to google to have more informations about the problem for "images informations
- started a google doc to gather give informations to Artem so he can help update privacy policy on Twake.app
- check how the `PermissionDialog` is done in the application and how it would work for contact (and maybe for images in the hypothesis)
