### ISSUE TITLE
[Bug] Cannot search by partial or full username, or Matrix ID

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1963]
2.6.0, staging, tested on Android and IOS; Safari, Firefox

1. Tap on the search bar in the Chats or Contacts tab
2. Try entering a username (email) or Matrix ID
3. No search results

Expectation: I can search by username

https://github.com/user-attachments/assets/fc34b9ac-fd62-4e10-a22d-f1803871cde4

https://github.com/user-attachments/assets/59993b6c-c6e1-4daa-9134-0ca9c4aa7605

**Comment by sherlockvn** [comment]
Right now, it searches only contacts, but contacts don't have in stg

**Comment by tprudentova** [comment]
Tested on 2.6.1, still cannot search by username through contacts with whom I had a chat


https://github.com/user-attachments/assets/1ea474fe-0436-498d-a411-cb4f9842b30a

**Comment by hoangdat** [comment]
hi @nqhhdev any update on this ticket?

**Comment by nqhhdev** [comment]
> hi @nqhhdev any update on this ticket?

In progress

**Comment by nqhhdev** [comment]
#1983 Fixed for this case. Pls check it @hoangdat
