### ISSUE TITLE
[Bug] Cannot create a chat via exact Matrix ID

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1964]
2.6.0, staging, tested on Android 

1. Click Create 
2. Enter an exact Matrix ID 
3. The result isn't there 

Expectation: I can create a chat via exact Matrix ID

https://github.com/user-attachments/assets/5dbaed28-eb86-481c-a151-f8f8e65fd573

**Comment by Te-Z** [comment]
Note for dev team: we need to know if the problem is from front end or back end

**Comment by nqhhdev** [comment]
Hi @tprudentova, this ticket still in developing and in review.

For new version, I think you should follow change log to test. Thanks!
