### ISSUE TITLE
[Bug] Cannot receive messages sent from Linagora env to Staging env

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1965]
2.6.0, staging, tested on Android, IOS

1. Send a message from a Linagora account to a staging account 
2. The message never arrives

https://github.com/user-attachments/assets/a6b533a1-d52e-4294-8606-574ce1aa800c

**Comment by Te-Z** [comment]
@guimard it worked last week but today it does not. Did your team change something about this ?
I don't have any logs regarding this problem on front end

**Comment by hoangdat** [comment]
Can you show the network request in browser @Te-Z ?

**Comment by guimard** [comment]
Hi, I just updated Matrix/Synapse version from 1.106.0 to 1.111.0 without any DNS or configuration change

**Comment by guimard** [comment]
DNS looks good:
```shell
$ host -t SRV _matrix-fed._tcp.stg.lin-saas.com
_matrix-fed._tcp.stg.lin-saas.com has SRV record 10 5 443 matrix.stg.lin-saas.com.
$ host -t SRV _matrix-fed._tcp.linagora.com
_matrix-fed._tcp.linagora.com has SRV record 10 10 443 matrix.linagora.com.
$ host -t SRV _matrix._tcp.stg.lin-saas.com
_matrix._tcp.stg.lin-saas.com has SRV record 10 10 443 matrix.stg.lin-saas.com.
$ host -t SRV _matrix._tcp.linagora.com
_matrix._tcp.linagora.com has SRV record 10 0 443 matrix.linagora.com.
```
But not http auto-discover
```shell
$ curl https://linagora.com/.well-known/matrix/server
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html>
$ curl https://lin-saas.dev/.well-known/matrix/server
{
    "m.server": "matrix.lin-saas.dev:443"
}
```

DNS method was marked as deprecated, maybe we should add the https://linagora.com/.well-known/matrix/server document to fix this issue

**Comment by guimard** [comment]
> [...]
> DNS method was marked as deprecated and maybe Element changed Matrix/Synapse policy. So maybe we should add the https://linagora.com/.well-known/matrix/server document to fix this issue

Asked

**Comment by Te-Z** [comment]
@hoangdat @guimard looks like it's a 504 error

![image](https://github.com/user-attachments/assets/5a542716-9546-4231-b905-f8c3f8817fd1)

**Comment by guimard** [comment]
Looks to be on partner side:
```
twake-maxs-synapse-1     | 2024-07-22 23:16:57,068 - synapse.http.matrixfederationclient - 766 - INFO - federation_transaction_transmission_loop-231128 - {PUT-O-180870} [ctrl-c.liu.se] Got response headers: 504 Gateway Timeout
twake-maxs-synapse-1     | 2024-07-22 23:16:57,069 - synapse.http.matrixfederationclient - 809 - INFO - federation_transaction_transmission_loop-231128 - {PUT-O-180870} [ctrl-c.liu.se] Request failed: PUT matrix-federation://ctrl-c.liu.se/_matrix/federation/v1/send/1721357694923: HttpResponseException('504: Gateway Timeout')
twake-maxs-synapse-1     | 2024-07-22 23:16:57,467 - synapse.http.federation.matrix_federation_agent - 371 - INFO - federation_transaction_transmission_loop-230592 - Failed to connect to nbg-hq.ems.host:8448: DNS lookup failed: no results for hostname lookup: nbg-hq.ems.host.
twake-maxs-synapse-1     | 2024-07-22 23:16:57,469 - synapse.http.matrixfederationclient - 809 - INFO - federation_transaction_transmission_loop-230592 - {PUT-O-180371} [nbg-hq.ems.host] Request failed: PUT matrix-federation://nbg-hq.ems.host/_matrix/federation/v1/send/1721357694425: DNSLookupError('no results for hostname lookup: nbg-hq.ems.host')
```
or maybe a firewall rule ?

**Comment by nqhhdev** [comment]
Hi @tprudentova 

Currently, I just tested it works well.
Pls verify it again


https://github.com/user-attachments/assets/64c323ab-fcaf-4340-abf6-c47dcc266ae1

https://github.com/user-attachments/assets/c6a52ade-5b96-414e-8df1-84bba063c719

**Comment by Te-Z** [comment]
This one is fixed by Xavier yesterday. Could you test it again @tprudentova ?
