### ISSUE TITLE
[Search] Break UI when search with keyword "\"

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#1968]
### Context 

- Device: Mobile (iOS and Android)
- Browser: All 
- App Version: 2.6.0
- Server: prod, stg, dev

### Step reproduce:
- Open `search`, `contact`
- Enter keyword to search: `\123\` or `hi\`, etc.
- UI result was broken.

### Screenshots or Video

- Web

https://github.com/user-attachments/assets/cb44544a-1900-41bf-a0c0-ac0232629390

- Mobile

![Image](https://github.com/user-attachments/assets/fd8f1b6c-d101-4cbd-91f3-e8ed459dd7b9)
![Image](https://github.com/user-attachments/assets/3b20b04d-7769-45e5-babc-e6d208f52785)

### Expected 

- UI result not broken.

**Comment by sherlockvn** [comment]
Need to add try/catch and add more test for the search

![Image](https://github.com/user-attachments/assets/0f18c746-dc8f-41a7-a7dd-a3de05ccd556)

**Comment by nqhhdev** [comment]
### DoD:

- [ ] Handle format exception
- [ ] Write unit test
