### ISSUE TITLE
[Bug] [LINAGORA ENV] Cannot add members to chat 

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1969]
Android, Safari 

1. Open a group chat -> group info
2. Click Add members 
3. Select some member, click Add 
4. Infinite upload 

Pls fix it 😭 

https://github.com/user-attachments/assets/253d5c65-5738-4baa-b726-f07b41a269e9

**Comment by nqhhdev** [comment]
Hi @tprudentova, I just tested it works well for me. Pls verify it again.


https://github.com/user-attachments/assets/aef53ca6-ae12-42c7-87b9-936380f6bc64

**Comment by tprudentova** [comment]
@nqhhdev yay it's fixed now :)
