### ISSUE TITLE
[Bug] Cancel upload doesn't work right

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1972]
2.6.0, chat.stg.lin-saas.com, tested on Firefox

1. Click attach 
2. Select a file, enter a caption  
3. Send
4. Cancel upload 
5. The caption is sent anyway, there's also a weird upload preview that disappears after you reload the page 

Expectation: a) if I cancel upload of media, the caption isn't sent either. b) there's no weird preview if I canceled upload

https://github.com/user-attachments/assets/f40f1383-db20-4227-b4a2-41843689a1a4

**Comment by nqhhdev** [comment]
### DoD:

- [ ] Remove captions event when cancel all File
- [ ] Update unit test
