### ISSUE TITLE
[Bug] Cannot jump to a reply if the source message is media or file

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1974]
2.6.0, tested on Android, Firefox; chat.stg.lin-saas.com

1. Send a media file or just a file 
2. Reply to that message
3. Try jumping to source message
4. Cannot jump

https://github.com/user-attachments/assets/a0abb0a8-4583-415f-8606-ad92e1f7a449

https://github.com/user-attachments/assets/f0ab0661-1945-4fdd-b3d8-a6a72cd76a0c

**Comment by Te-Z** [comment]
probably related to #1399
