### ISSUE TITLE
[Bug] [WEB] Recent chats aren't displayed

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1975]
2.6.0, tested on Safari, firefox; chat.stg.lin-saas.com

1. Click Create -> Group chat
2. There are no recent contacts there and adding through exact Matrix ID doesn't work, so I can't create a chat AT ALL

https://github.com/user-attachments/assets/f20a1120-8508-429f-87c6-1187bc0d0ac0

**Comment by nqhhdev** [comment]
Fixed 

#1966

**Comment by Te-Z** [comment]
Hi @nqhhdev the problem is fixed for group chat but still occurs when creating a new chat

[Capture vidéo du 24-07-2024 07:31:38.webm](https://github.com/user-attachments/assets/d72bf99e-24e7-4660-8b77-e7b69d56e641)

**Comment by nqhhdev** [comment]
> Hi @nqhhdev the problem is fixed for group chat but still occurs when creating a new chat
> 
> 
> 
> [Capture vidéo du 24-07-2024 07:31:38.webm](https://github.com/user-attachments/assets/d72bf99e-24e7-4660-8b77-e7b69d56e641)
> 
> 

Which env?

**Comment by Te-Z** [comment]
> > Hi @nqhhdev the problem is fixed for group chat but still occurs when creating a new chat
> > 
> >   
> >     
> >     
> > 
> >     Capture.video.du.24-07-2024.07.31.38.webm
> 
> Which env?

@nqhhdev stg.lin-saas.com

**Comment by Te-Z** [comment]
For new private chat, contacts are not added when creating a chat with them and on stg.lin-saas the contacts are not uploaded. That's why there no contacts for this case.

@tprudentova could you test it again please ?
