### ISSUE TITLE
[Bug] All contacts from the company look Online

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1996]
2.6.1, tested on Android 

1. Go to the Contacts tab 
2. Scroll down to company contacts 
3. All of the contacts are marked with label "Online", even though some (most) of the contacts aren't currently online 

Expectation: the "Online" status means that the user is currently online

https://github.com/user-attachments/assets/03f37efc-136b-440a-8883-9f38c46bbcd5

**Comment by hoangdat** [comment]
it is `Active` in the previous version. Which ticket change it to `Online`?

**Comment by hoangdat** [comment]
Which design make the change to remove activated status? @KhaledNjim

**Comment by KhaledNjim** [comment]
> Which design make the change to remove activated status? [@KhaledNjim](https://github.com/KhaledNjim)

[design](https://www.figma.com/design/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?node-id=25783-37873&t=g9AmX3cmDNXeEW9z-0)


![Image](https://github.com/user-attachments/assets/a33321bb-a864-4499-8a17-07c818115289)
