### ISSUE TITLE
[Bug] Never-ending avatar upload

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#1999]
2.6.1, tested on Android, linagora.com, chat.stg.lin-saas.com

1. Go to Profile info
2. Click Change profile avatar 
3. Select a photo 
4. Click Done 
5. Infinite upload (or probably just _very_ long). If you reload the app, the avatar is applied

https://github.com/user-attachments/assets/0f0d0da6-a033-4029-b4ab-a5e06b4f836c

**Comment by nqhhdev** [comment]
Hi @tprudentova, this is bug front FE side or BE side?

If you gonna to know this, pls use web browser and open developer mode (Inspect on web) and check api `/upload`.
Then let me know exactly the issue and what is the happened.

**Comment by nqhhdev** [comment]
I think this issue related to #1453.  I mean duplicated pls check it, thanks.

**Comment by tprudentova** [comment]
@nqhhdev Hi! I only get this behaviour in the mobile app, and there are no dev tools there :( So unfortunately can't tell

**Comment by nqhhdev** [comment]
Yes, I mean you can try to reproduce it on Web platform to the same behavior. Need further information about this issue.

**Comment by tprudentova** [comment]
The same bug is reproduced in web on production (chat.twake.app). Attaching a video with dev mode 


https://github.com/user-attachments/assets/53f4be50-c273-480c-b5be-0c08155de8eb
