### ISSUE TITLE
[Bug] [PRODUCTION] Cannot create a chat with a user from a different server

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#2013]
2.5.9, chat.twake.app, tested on Safari, Firefox 

1. Log in as a user of twake.app server 
2. Enter a Matrix ID of a user from a different server (staging or linagora.com)
3. Click on the user, try sending a first message 
4. Error 

https://github.com/user-attachments/assets/1665e0eb-2baa-4f05-9cf1-592695885952

**Comment by nqhhdev** [comment]
Hi @tprudentova, on prod env I mean not available. One more, this issue related to BE side (like error in image below) so from FE side we're handle error from BE side and display toast message. Thanks !

<img width="495" alt="Screenshot 2024-09-09 at 19 00 47" src="https://github.com/user-attachments/assets/19d8b1c8-2b29-43e4-927a-76834546601b">

**Comment by tprudentova** [comment]
@guimard maybe you can help us with this issue?

**Comment by guimard** [comment]
I think this is because `https://stg.lin-saas.com/.well-known/matrix/server` is missing. It should contain:
```
{
 "m.server": "matrix.stg.lin-saas.com:443"
}
```
Can someone create this content in main server ?

**Comment by tprudentova** [comment]
@guimard hi! Sure you can't help with fixing this bug? It happens on production and it would be good to fix it before the release of the public platform (which is menacingly close)

**Comment by guimard** [comment]
Yes, I'd like to test the proposed way _(2 messages ago)_. Maybe @tk-nguyen can do it ?

**Comment by tk-nguyen** [comment]
> `https://stg.lin-saas.com/.well-known/matrix/server`

This is not the issue, it tested fine on federationtester: https://federationtester.matrix.org/#stg.lin-saas.com and https://federationtester.matrix.org/#linagora.com

**Comment by tk-nguyen** [comment]
The issue is that on staging we don't allow federation to anywhere except linagora.com and matrix.org, and production we forgot to configure this

**Comment by tk-nguyen** [comment]
Fixed now on production: now it will federate with everything.

**Comment by hoangdat** [comment]
Worked for my side: prod account, create chat with Linagora account.

**Comment by guimard** [comment]
Thanks !

**Comment by hoangdat** [comment]
sorry, need reopen it. When linagora account accept invitation, I got the problem @guimard @tk-nguyen 

<img width="560" alt="image" src="https://github.com/user-attachments/assets/0f11a6a2-a209-4181-85fa-d7cd2810a460">

**Comment by guimard** [comment]
Maybe same issue on linagora.com side ?

**Comment by hoangdat** [comment]
> Maybe same issue on linagora.com side ?

403 error with response
```
{"errcode":"M_FORBIDDEN","error":"Federation denied with linagora.com."}
```

**Comment by tk-nguyen** [comment]
Requests were routed to workers, which were not restarted after configuration changes. After that, it worked properly.

**Comment by tprudentova** [comment]
https://github.com/user-attachments/assets/ed4736f2-03be-42ee-aea2-74d8cc3445ec

@tk-nguyen The bug appeared again, cannot create chats with external matrix users (the video is matrix.org). Also messages with people from other matrix servers aren't synchronised (see the videos below, the same chat but viewed from linagora.com account and twake.app account)

https://github.com/user-attachments/assets/76a858c1-cc7c-4c08-87c2-72c1d69d728b

https://github.com/user-attachments/assets/8e09d842-c322-4981-ab7e-ac998f5baade

**Comment by tk-nguyen** [comment]
No, this is because https://twake.app/.well-known/matrix/server is returning 404. Looking into this.

**Comment by tk-nguyen** [comment]
It should be fixed now?

**Comment by tprudentova** [comment]
@tk-nguyen yes, thank you!!
