### ISSUE TITLE
Let user confirm before quitting a group

### ISSUE THREAD

**Issue by Facyla** [linagora/twake-on-matrix#2033]
### Describe the feature

Add a confirmation screen before quitting a group. 
It is especially important for groups user has created himself, and even more if user is the only admin of that group. 

### Describe the solution you'd like or your expectation

A confirmation popin or other UI so that user:
1. is warned about the consequence of his action : as a basic user, he might not be able to join the group again (eg. if he was invited and group is not public), and he might lose the group history ; as an admin, there are additional issues such as it might lead to a situation where no one can edit the group ;
2. and has to confirm explicitely that user has understood these consequences and indeed wants to proceed

The confirmation message and process might differ depending on the user role, as the consequences are only personal in this first case, while other users are impacted for the second.

### Describe alternatives you've considered

- Can be a simple popin with the message abiut the consequences, followed by "Cancel" + "Confirm" buttons
- or also integrate a checkbox for admins
- or even a confirmation text that the user has to type for the worst cases

**Comment by tprudentova** [comment]
Duplicate #1851
