### ISSUE TITLE
[Bug] [CRASH APP] Chat totally crashes if you try to upload a chat avatar > 100 MB

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#2044]
2.6.5, chat.stg.lin-saas.com, tested on Safari 

1. Start creating a group chat 
2. Upload an avatar > 100 MB 
3. There's no warning, the app stops responding any actions, you can't even reload or close the page 

Expectation: there's a warning "File size cannot exceed 100 MB"

https://github.com/user-attachments/assets/2aca7309-d3a0-45ea-97a5-2d649ac1d883

**Comment by hoangdat** [comment]
related to #2066
