### ISSUE TITLE
[BUG?] The order of words searched in a sentence does not match the results.

### ISSUE THREAD

**Issue by dab246** [linagora/twake-on-matrix#2045]
### Env: 

- Version: `2.6.5`
- Server: `stg.lin-saas.com`
- Platform: `Chrome, Edge(Macbook)`

### Steps to reproduce

1. Go to the Chats tab
2. Click search bar
3. Enter the search query in no particular order:  `năm này xưa ngày`
4. Results do not match the searched word order and are not highlighted. `Ngày này năm xưa`

## Expectation

- Results match the searched words and are highlighted.

## Evidence

https://github.com/user-attachments/assets/35491c86-2a35-4715-8c6f-a562a07480ef

**Comment by hoangdat** [comment]
not a bug :)
