### ISSUE TITLE
[BUG] Loading screen is blinking when turning off/on notification

### ISSUE THREAD

**Issue by shepilov** [linagora/twake-on-matrix#2055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

<img width="1380" alt="image" src="https://github.com/user-attachments/assets/b6775a23-7269-478f-a7ab-a6551eb74ac0">

### Pre-Bug State

?

### To Reproduce

1. Go to "Notifications"
2. Switch them on/off
3. Screen will blink with loader

### Expected results

Screen is not blinking

### Context

- OS: MacOS
- Browser: Opera
- App Version: 2.6.5
- Server: stg.lin-saas.com
- Account information: shepilov99

**Comment by hoangdat** [comment]
this is the loading dialog style for the whole app.

![Image](https://github.com/user-attachments/assets/94ca9971-88ba-47f7-a2cf-a646284edf79)

**Comment by hoangdat** [comment]
can I close it? @shepilov
