### ISSUE TITLE
[BUG] The search in messages doesn’t work with interrogative pronouns like “who”, “where”

### ISSUE THREAD

**Issue by shepilov** [linagora/twake-on-matrix#2056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I try to find a message by the keyword "who" nothing appears.

### Pre-Bug State

.

### To Reproduce

1. Go any chat
2. Write the message "who let the dog out"
3. Try to search in this chat by keyword "who"
4. Nothing is appeared

### Expected results

The message appeared

### Context

- Browser: [e.g. chrome, safari]
- App Version: [e.g. 22]
- Server: [e.g. production, example.com]
- Account information:
- Others

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

<img width="1372" alt="image" src="https://github.com/user-attachments/assets/f0d7b540-0a89-42f9-baf3-01c40ef185e7">
<img width="1383" alt="image" src="https://github.com/user-attachments/assets/057cd233-3746-40fc-97c9-03fa79c67b02">

</details>

### Additional information

- Always

**Comment by hoangdat** [comment]
duplicated #1786
