### ISSUE TITLE
[BUG] No notification in Opera

### ISSUE THREAD

**Issue by shepilov** [linagora/twake-on-matrix#2058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I haven't seen at least one notification

### Pre-Bug State

.

### To Reproduce

1. Open Twake Chat in Opera
2. Wait for notifications

### Expected results

I see the browser pop-up in the top left corner of the screen

### Context

- OS: MacOS
- Browser: Opera
- App Version: 2.6.5
- Server: stg.lin-saas.com
- Account information: shepilov99

**Comment by hoangdat** [comment]
how about yoour notification settings in System?

![Image](https://github.com/user-attachments/assets/d1c00a25-d9a2-471f-b9cb-cbf773df96a2)

**Comment by hoangdat** [comment]
![Image](https://github.com/user-attachments/assets/22f124fc-3c74-4a21-897e-1bb92f761a92)
