### ISSUE TITLE
[BUG] Remove the `(` character in the Vietnamese contact information title

### ISSUE THREAD

**Issue by dab246** [linagora/twake-on-matrix#2063]
### Env: 

- Version: `2.6.5`
- Server: `stg.lin-saas.com`
- Platform: `Chrome, Edge(Macbook)`

### Steps to reproduce

1. Open a direct chat
2. Click username on top bar in chat view

## Expectation

Contact information title in Vietnamese is displayed correctly

## Evidence

<img width="1437" alt="Screenshot 2024-09-23 at 19 44 04" src="https://github.com/user-attachments/assets/96900fe7-fbb6-459e-bca7-3564a164ac57">

**Comment by hoangdat** [comment]
- weblated pushed
