### ISSUE TITLE
[BUG] Double-click the `Cancel` button the first time to close the dialog to share media to other messengers

### ISSUE THREAD

**Issue by dab246** [linagora/twake-on-matrix#2064]
### Env: 

- Version: `2.6.5`
- Server: `stg.lin-saas.com`
- Platform: `Chrome, Edge(Macbook)`

### Steps to reproduce

1. Open a direct chat
2. Click image in message bubble to preview it
3. Click `Share` button on right top screen.
4. Click `Cancel` button in share dialog 

## Expectation

- One click `Cancel` button to close dialog 

## Evidence

https://github.com/user-attachments/assets/eee08058-1241-453f-b5d2-668a3708958a

**Comment by hoangdat** [comment]
- root cause: using conflict in go router and Navigation.
