### ISSUE TITLE
[BUG] The screen freezes and sometimes the app crashes when changing avatar in group chat or changing profile picture.

### ISSUE THREAD

**Issue by dab246** [linagora/twake-on-matrix#2066]
### Env: 

- Version: `2.6.5`
- Server: `stg.lin-saas.com`
- Platform: `Chrome, Edge(Macbook)`

### Steps to reproduce

- Change avatar in group chat

1. Open a group chat
2. Click group name
3. Click `pen` edit icon on top right of group information
4. Click `pen` edit icon on avatar
5. Select `Change the avatar`
6. Select large file `(Ex: >= 20MB) `

- Change profile picture

1. Click Setting tab
2. Click username item
3. Click `pen` edit icon on avatar
4. Select `Change the avatar`
5. Select large file `(Ex: >= 20MB) `

## Expectation

- Should set a limit on the file size allowed to be uploaded (Only a few MB). And show a warning dialog when the capacity is exceeded
- Should have a loading dialog when picking files to let users know
- Use Stream to pick files to avoid long file downloads.

## Evidence

https://github.com/user-attachments/assets/38cfbe43-0a86-4336-abc4-1919c79e0f3f

**Comment by dab246** [comment]
Same cause #2044

**Comment by hoangdat** [comment]
- [ ] handle the way of picking big size in main thread
