### ISSUE TITLE
[Notification] There is nothing on notification center once user receiving new chat message

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#208]
OS:  Android
Device: Mobile
TMail version:  2.1.3

*Precondition: 
- Twake is have full permission 

![Image](https://user-images.githubusercontent.com/124866146/248543792-17593eb7-012c-42be-800b-1b8cd20e6573.png)

- User A send new message to user B

### *Reproduce Step:
1, User A send new message to user B
2, User B check notification center

### **Actual:** 
There are no new notification

### **Expected:** 
System should display new notification

**Comment by hoangdat** [comment]
- Android: OK
- iOS: Please try to implement a plugin only support iOS to connect Sygnal directly with APNs

**Comment by hoangdat** [comment]
- connected via APNs
- only show the common notification

**Comment by QuangHoang1210** [comment]
Passed on both IOS and Android.

However one kind of notification is not catched the expectation: https://github.com/linagora/twake-on-matrix/issues/542
