### ISSUE TITLE
[BUG][EDGE] add member action buttons in add members to group chat form are not shown up properly

### ISSUE THREAD

**Issue by rezk2ll** [linagora/twake-on-matrix#2110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

action buttons ( add and cancel ) in add member to group chat form are not shown properly in EDGE

![Screenshot from 2024-10-23 17 46 14](https://github.com/user-attachments/assets/9d148f09-baf2-4b0e-a860-e8fba33f1be0)

### Pre-Bug State

use edge

### To Reproduce

1 - create group chat
2 - click on the group name to see group information
3 - click on the add members button ( bottom right side of the page )

### Expected results

cancel and add buttons should fully and properly appear

### Context

- Device: HP ProBook
- OS: Ubuntu
- Browser: Edge
- App Version: 2.6.7
- Server: staging

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![Screenshot from 2024-10-23 17 47 49](https://github.com/user-attachments/assets/0cdc514a-1a95-4553-b512-72334618cda3)

![Screenshot from 2024-10-23 17 46 14](https://github.com/user-attachments/assets/1af1d3e3-ec9a-4007-9bc0-b7147bec21d3)

</details>

**Comment by KhaledNjim** [comment]
Cant reproduce on 2.6.12

**Comment by rezk2ll** [comment]
> Cant reproduce on 2.6.12

same for 2.6.12, the issue is gone, just tested on Edge `Version 131.0.2903.99 (Official build) (64-bit)`
