### ISSUE TITLE
[Chat] Voice chat is displayed incorectly, the time of voice message is displayd break the line

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#213]
OS:  Android
Device: Mobile
TMail version:  2.1.3

*Precondition: 
- User sent an voice message

### *Reproduce Step:
1, User send the voice message successfully

### **Actual:** 
The time of voice message is displayed break the line

![Image](https://user-images.githubusercontent.com/124866146/248545849-89586ed4-fb4c-4e5a-9d03-2962c9c9f5d9.png)

### **Expected:** 
The time of voice message should be displayed in single line

**Comment by shepilov** [comment]
not relevant, we don't have voices right now

**Comment by hoangdat** [comment]
Relevant, because if user send voice message from other Matrix client, we still failed in display it.

**Comment by hoangdat** [comment]
![Image](https://github.com/linagora/twake-on-matrix/assets/6462404/815f2017-8959-4370-8e9d-836ed573eafc)

https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?type=design&node-id=6497-118383&mode=design&t=b3WqhYuvlvS7G7XM-4
