### ISSUE TITLE
[Chat] User cannot foward a message by selecting multiple user

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#217]
OS:  Android
Device: Mobile
TMail version:  2.1.3

*Precondition: 
- There are existed recently chat

### *Reproduce Step:
1, User tap and hold on a message
2, User select foward
3, User tap on Recently
4, User select at least 2 user in the list

### **Actual:** 
The foward button is disappeared. User cannot do foward message action

https://user-images.githubusercontent.com/124866146/248575052-a298f620-6ab0-47ff-8b51-ae8c18800059.mp4

### **Expected:** 
The foward button is displayed and clickable.
User can do foward message to user who being selected

**Comment by nqhhdev** [comment]
- Currently, we only support forward messages to one person.

**Comment by shepilov** [comment]
we can choose:
- forward to multiple users or 
- do not let users to select multiple users

**Comment by hoangdat** [comment]
- [ ] select one user to forward 
- [ ] remove all checkbox
- [ ] show radio button for selected user
