### ISSUE TITLE
[Chat] There is no thumbnail of url in message bubble

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#219]
OS:  Android
Device: Mobile
TMail version:  2.1.3

*Precondition: 
- User A send user B a link which having thumbnail.

### *Reproduce Step:
1, User A send user B a link

### **Actual:** 
There is no thumbnail of url in message bubble

https://github.com/linagora/twake-on-matrix/assets/124866146/ecfe17ff-2f21-4633-b2ca-d9283c3da372

### **Expected:** 
The link was sent but it will have a thumbnail in message bubble

**Comment by sherlockvn** [comment]
Yes. Thumbnail image in preview Image is not supported yet
