### ISSUE TITLE
[Chat] User cannot share link by twake application

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#222]
OS:  Android
Device: Mobile
TMail version:  2.1.3

*Precondition: 
- User visit chrome and pick the link to share by Twake

### *Reproduce Step:
1, User open dantri website on chrome
2, User tap and hold on a topics link
3, User select Share
4, User select Twake

### **Actual:** 
- System redirect user to Twake app where current screen that user left
- Nothing happen after that.

https://user-images.githubusercontent.com/124866146/248577204-1dbd5bb0-23b4-4652-b6d1-79b0e309cb58.mp4

### **Expected:** 
- System redirect user to Twake app where contact list screen that user can select user who want to send the link

**Comment by nqhhdev** [comment]
IMO:  It's a big feature, you can compare it with other apps and let us know what you think.

**Comment by QuangHoang1210** [comment]
Do you need the AC as gherkin !? I will propose it
