### ISSUE TITLE
Handle HEIC of iphone

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#223]
### Desc:
```
 Can't send photos taken on an IOS device
```

### DoD:
- [ ] iOS
- [ ] Hanlde HEIC of IOS
- [ ] Resize image on IOS 

https://github.com/linagora/twake-on-matrix/assets/99852347/fd21eb85-43b2-4c26-90ac-5a5dae48b770

**Comment by sherlockvn** [comment]
There is a neat way to handle HEIC image like `https://pub.dev/packages/wechat_assets_picker` this package does, please reference the extension for `AssetEntity` in funciton toMatrixFile

**Comment by hoangdat** [comment]
The same problem with file size exceeded. 
Fixed in `tom-dev`. 
- [ ] Please verify the error case with file which have size more than max file size.

**Comment by hoangdat** [comment]
@drminh2807 please update the response when you trying to upload file more than max

**Comment by drminh2807** [comment]
- tom-dev still can upload image file under 100Mb
- linagora return html response
```html
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
