### ISSUE TITLE
[Chat] User cannot make the keyboard disapear by swipe down it or click out of keyboard range

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#224]
OS:  Android
Device: Mobile
TMail version:  2.1.3

*Precondition: 
- swipe down keyboard or click out its area

### *Reproduce Step:
1, User open a conversation
2, User tap to input field
3, User click out of keyboard area or swipe down the keyboard

### **Actual:** 
User cannot make the keyboard disappear.

https://user-images.githubusercontent.com/124866146/248577832-f1e9e2c0-6402-4b4f-b1a2-661f2efa7ca6.mp4

### **Expected:** 
User can make the keyboard disappear by swipe down it or click out of its area

**Comment by sherlockvn** [comment]
https://github.com/linagora/twake-on-matrix/issues/202 duplicate

**Comment by QuangHoang1210** [comment]
Only pass the UI changing which be mentioned in #202 

For the outfocus keyboard action -> Still have a bug.

Env: Matrix.linagora.com
