### ISSUE TITLE
[Chat] User cannot react to the message

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#226]
OS:  Android
Device: Mobile
TMail version:  2.1.3

*Precondition: 
- Existed a conversation

### *Reproduce Step:
1, User open a conversation
2, User tap on a message

### **Actual:** 
User cannot react on it

### **Expected:** 
User can react the message by tapping on the message bubble

**Comment by nqhhdev** [comment]
- Currently, we can't support for reaction to the message. We've hidden it for the time being

- https://github.com/linagora/twake-on-matrix/pull/143

**Comment by hoangdat** [comment]
duplicated #994
