### ISSUE TITLE
[Message] Show the docs file in message bubble

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#233]
### Desc:
- Show the file: icon with name in the message bubble 

![Image](https://user-images.githubusercontent.com/6462404/249057623-e2d230d0-b48c-4476-901b-07eb0fbc897d.png)

- each file will have each icon, can find in https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?type=design&node-id=10322-153501&mode=design&t=zZNVpdbLs7BCvvy3-4

**Comment by QuangHoang1210** [comment]
Passed
