### ISSUE TITLE
[Composer] Send file

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#235]
### Design:
https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?type=design&node-id=8262-147021&mode=design&t=D3h2MGPcJwKMzTVY-4

### DoD:
- [x] permission handler
- [x] UI
- [x] send 1 file

**Comment by QuangHoang1210** [comment]
Not catch the UI ---

**Precondition:** User A have full permission

**Reproduce Step:**
1, User A open chat with user B
2, User A tap on + icon
3, User A tap on Attachment icon

**Actual**: System redirect user A to Internal Storage Recent

https://github.com/linagora/twake-on-matrix/assets/124866146/42608854-4140-4dbf-a6ff-2cd23bd5266f


**Expected:** System should display a popup as figma to let user select the options which include: Internal Storage, Twake Folder, Gallery and Recent files list

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/0a83a30e-dac3-47cc-8fcb-53c687ea6de6)

**Comment by QuangHoang1210** [comment]
Pass DoD --> UI will be tested in next phase with new design
