### ISSUE TITLE
[UI] Seen arrows in message bubble are wrong Width & Height

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#238]
OS:  Android
Device: Mobile
TMail version:  2.1.3

### *Reproduce Step:
1, User open a chat conversation existed
2, Focus on seen arrows

### **Actual:** 
- Width = 16.0 px
- Height = 16.0 px

### **Expected:** 
- Width = 15.5 px
- Height = 8.94 px
- Color: #0A84FF

![Image](https://user-images.githubusercontent.com/124866146/249332340-8fea2253-b8a9-4985-b9eb-c9f6c10d9496.png)

**Comment by imGok** [comment]
color is fine (primary), icons have square dimensions (width = height). fixed it to 15.5
