### ISSUE TITLE
[UI] Sender name label in group chat is having wrong text font

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#239]
OS:  Android
Device: Mobile
TMail version:  2.1.3

### *Reproduce Step:
1, User open a group conversation
2, Focus on name label of sender in group chat

### **Actual:** 
- The font is Inter

![Image](https://user-images.githubusercontent.com/124866146/249331712-8b9f8338-e27c-46df-bdad-ba9cbe40e98b.png)

### **Expected:** 
- The font should be Roboto

![Image](https://user-images.githubusercontent.com/124866146/249331726-475461dd-bb81-4a10-a86b-97c3fd8f402b.png)

**Comment by hoangdat** [comment]
all the font MUST BE inter
