### ISSUE TITLE
[UI] Avatar in message bubble of group chat is wrong size

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#240]
OS:  Android
Device: Mobile
TMail version:  2.1.3

### *Reproduce Step:
1, User open a group conversation
2, Focus on avatar in message bubble

### **Actual:** 
- The size is 36px 36px

![Image](https://user-images.githubusercontent.com/124866146/249331172-871e9694-2a22-4b78-84b9-502a2bbdf3d5.png)

### **Expected:** 
- [ ] The size should be 40px 40px
- [ ] And only show at the last bubble of the same sender
- [ ] No ava in direct chat 

![Image](https://user-images.githubusercontent.com/124866146/249331167-dbf97f38-a493-46f4-bff6-5bddfd280b5e.png)

**Comment by hoangdat** [comment]
![Image](https://github.com/linagora/twake-on-matrix/assets/6462404/03578f57-d503-4f1a-a00d-918792e46db8)
