### ISSUE TITLE
[UI] The letter space of Group Name label is not correct

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#242]
OS:  Android
Device: Mobile
TMail version:  2.1.3

### *Reproduce Step:
1, User open a group conversation
2, Focus on Group Name label on the top

### **Actual:** 
The letter space should be 0.1px

![Image](https://user-images.githubusercontent.com/124866146/249330299-28aad913-2ca0-465c-828b-87c882e7187e.png)

### **Expected:** 
The letter space should be 0.15px

![Image](https://user-images.githubusercontent.com/124866146/249330275-e65932fa-d1ef-4015-a9fe-ec485d633323.png)

**Comment by hoangdat** [comment]
The problem still here @imGok

**Comment by imGok** [comment]
This is a display bug, it shows 0.1 in widget inspector no matter what 
![image](https://github.com/linagora/twake-on-matrix/assets/48354990/a26d61a6-4d40-44b0-a87f-a4a13e0bd5f3)
but the letter space is indeed 0.15 
![image](https://github.com/linagora/twake-on-matrix/assets/48354990/20988905-94cf-40b0-ba30-7e9064fa7c73)
![image](https://github.com/linagora/twake-on-matrix/assets/48354990/880cacb7-5cc3-41b9-a7f8-115a55a99675)

**Comment by hoangdat** [comment]
We can not close the issue from QA team :)))

**Comment by QuangHoang1210** [comment]
I just reopened it.
I will close it once it passed testing on next deployment. @imGok @hoangdat
