### ISSUE TITLE
[UI] Bubble is blink blink if including tag name

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#245]

**Comment by hoangdat** [comment]
- dont forget to using `upstream` repo for bubble

**Comment by hoangdat** [comment]
- dont forget to using `upstream` repo for bubble

**Comment by hoangdat** [comment]
- [ ] open `upstream` PR and paste the link here
- [ ] push your temporary solution to the master of twake

**Comment by sherlockvn** [comment]
https://github.com/Sorunome/flutter_matrix_html/pull/11
