### ISSUE TITLE
[Chat] System automatically remove the word in search box once user select an user in searching result in Create Group Chat flow

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#249]
OS:  Android
Device: Mobile
TMail version:  2.1.3

*Precondition:  
- User create new group chat

### *Reproduce Step:
1, User create new group chat
2, User input qatest in to search box
3, User tap to select one user

### **Actual:** 
System automatically remove the keyword in search box and searching result is reload. User must input the keyword again. 
-> UX is not good in case user want to add many user come group from one keyword searching in the same time.

### **Expected:** 
System should keep the keywords and searching result. It will be changed only when user remove / add .. / change the keywords.

https://user-images.githubusercontent.com/124866146/249574788-9258932e-62c7-4152-afcc-0011f437711c.mp4

**Comment by hoangdat** [comment]
After select a person, only select all the text -> will not trigger the search and user still easy to find people.

**Comment by hoangdat** [comment]
Fx:
```
user search `dp`
have more than 1 result
user select `dphamhoang`
and user also want to select `dpo`
```

**Comment by QuangHoang1210** [comment]
Pass on 2.2.3 matrix.linagora.com
