### ISSUE TITLE
[Chat] [Offline Mode] System shouldn't display blue checks icon which indicate the message was delivered in offline mode

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#255]
OS:  Android/IOS
Device: Mobile
TMail version:  2.1.3

*Precondition:  
- User in offline mode
- User send a message

### *Reproduce Step:
1, User in offline mode
2, User send a message

### **Actual:** 
1, System display blue checks icon on message bubble

### **Expected:** 
1, System shouldn't display blue checks icon if message was sent in offline ( or in case that error which message not delivery yet)

![Image](https://user-images.githubusercontent.com/124866146/250437894-e0a3c895-43ba-4b02-8c90-47038e993c99.png)

**Comment by nqhhdev** [comment]
- Duplicated #347
