### ISSUE TITLE
[Search] Open Search screen when click on search bar in Chat Screen

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#266]
### Desc:
- Click on search bar in Chat List screen
- First step of search for all recent Contacts and Chat

![Image](https://user-images.githubusercontent.com/6462404/250681768-0154b054-a6c9-44af-a0d4-33dc8f9b229f.png)

### DoD:
- [ ] horizontal scroll for recent contacts (7 items)
- [ ] vertical scroll for all chat list

**Comment by nqhhdev** [comment]
###NOTE Currently, we can't get data fetch for recent contacts.
