### ISSUE TITLE
[M1] `GroupChatEmptyView` is wrong for member of group

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#272]
![Image](https://github.com/linagora/twake-on-matrix/assets/6462404/cd5b5f33-46cf-42d3-abfd-43584a9bb4f0)

**Comment by hoangdat** [comment]
waiting for design

**Comment by blockchain-advisory** [comment]
@hoangdat  That is the design for what user B must see when the group chat is created by user A:
https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?type=design&node-id=11271-181347&mode=design&t=cWy0eIsxPukabH2M-4
