### ISSUE TITLE
[M1] Reduce the padding for message bubble when select messages

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#276]

**Comment by hoangdat** [comment]
waiting for designer

**Comment by nqhhdev** [comment]
@hoangdat any update on this ticket from Desinger?

**Comment by blockchain-advisory** [comment]
I don't really see how design can help in this case, when you select multiple messages, don't change anything. Just preserve the same paddings inside the bubble as well as the space between bubbles.

**Comment by hoangdat** [comment]
### DoD:
- padding between bubble in selection mode should be the same in normal mode (no select)
