### ISSUE TITLE
[ChatList] Improve for delete chat

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#288]
### DES

```
GIVEN The conversation already exists
WHEN User A delete this conversation with user B 
AND User B can see this conversation in chat list
THEN User B clicks on this conversation, 2 options: Leave chat, open again
```

### DoD

- [ ] When deleting the conversation need have two options: `Delete just for me` and `Delete for me and Receiver`
- [ ] If user A choose `Delete just for me` => user B still sees the chat conversation and opens it, what is happen?
- [ ] If user A choose `Delete for me and Receiver` => user B doesn't see the chat conversation.

### Twake 

https://github.com/linagora/twake-on-matrix/assets/99852347/770d2fb6-526c-491d-8b6b-ed63061158d5

### Telegram

![Image](https://github.com/linagora/twake-on-matrix/assets/99852347/23ca8e21-c950-44a3-b2f3-ed6ecdf7f451)

**Comment by hoangdat** [comment]
No delete chat in our system
