### ISSUE TITLE
Deploy Sygnal in production: sygnal.twake.app

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#297]
### Desc:
- Because *.xyz is a personal domain
- We need a stable domain for Twake
- Please deploy Synal in `sygnal.twake.app`

**Comment by hoangdat** [comment]
hi @tk-nguyen can you help me to update this ticket?

**Comment by tk-nguyen** [comment]
> hi @tk-nguyen can you help me to update this ticket?

It's at `push.twake.app`.

**Comment by shepilov** [comment]
@hoangdat do we use it right now? is it relevant?

**Comment by pm-McFly** [comment]
> @hoangdat do we use it right now? is it relevant?

@shepilov yes this is important as the current value is targeting a DEV server (not scaled for handling more than few messages per minutes...)

@hoangdat @tk-nguyen please update so we use an entry in `config.json` for example:
https://github.com/linagora/twake-on-matrix/blob/3c07a60cef9eb7b116665e721e87e9f30e748e09/lib/config/app_config.dart#L110

thx!

**Comment by hoangdat** [comment]
we can not use `config.json` for this value, because it must be hardcoded for mobile. 
To make it flexible, maybe we can use well-known.

**Comment by pm-McFly** [comment]
> we can not use `config.json` for this value, because it must be hardcoded for mobile. To make it flexible, maybe we can use well-known.

Well-known will be better then.
Or at least a value to pass at compilation time, cuz if we leave this here any person building the code will use this unstable platform - at best it won't work, at worse it will interfere with our systems...
