### ISSUE TITLE
[Chat] Response in group chat is not displayed correct with design

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#30]
OS: Android / IOS
Device: Mobile
Twake 1.10.0

*Precondition: 
- There is existed a message conversation in channel
- There is existed new reply from other members in the group chat channel.

### **Reproduce:** 
1, User created a group chat channel
2, User send an message to group chat channel
3, Member reply/reaction that message
4, User stay on chat channel view

### **Actual:** 
There is no Response counting row.
System displayed separately reply message.
![Image](https://user-images.githubusercontent.com/124866146/230787347-18794dd4-67dc-4139-9625-e85d382fe080.png)

### **Expected:** 
System should display Response counting row with view chat details button same as design.
System displayed all reply message in to one Response row on chat preview of channel. User only can read it when click on view chat details button.
![Image](https://user-images.githubusercontent.com/124866146/230787418-3fc61445-fea1-488c-b36d-521efa955b8a.png)

**Comment by hoangdat** [comment]
not support thread at the moment
