### ISSUE TITLE
[web] Send file in Draft chat screen

### ISSUE THREAD

**Issue by sherlockvn** [linagora/twake-on-matrix#321]
### DES

```
GIVEN user have not have direct chat with user B before
WHEN user A open new empty chat screen, it will redirect user A to empty chat
THEN send file, voice and call is not added yet.
```

### DOD
- [ ] refactor to reuse with composer in Chat screen
- [ ] send File
- [ ] send voice
- [ ] make a call
- [ ] Add information of users in app bar

**Comment by imGok** [comment]
Why not refactoring chat screen so we can use it as a draft screen too ?

**Comment by sherlockvn** [comment]
OKay i will discuss with you in this afternoon
