### ISSUE TITLE
[Chat] After denied permission access photo, can't click to camera in image picker

### ISSUE THREAD

**Issue by sherlockvn** [linagora/twake-on-matrix#322]
### DES

```
GIVEN user denied access to photo and video
WHEN user open the image picker again
THEN user can't ask permisson for open camera
```

https://github.com/linagora/twake-on-matrix/assets/43041967/d131c13f-5305-46fe-94d9-8cd953d38641

### DoD
- [x] Only android
- [ ] Verify it on iOS

**Comment by sherlockvn** [comment]
The problem has been fixed.


https://github.com/linagora/twake-on-matrix/assets/43041967/22b02d47-736f-4613-858f-daf8d7d7d653

**Comment by hoangdat** [comment]
- [ ] update linagora system design in twake
