### ISSUE TITLE
[Chat] Sticky timestamp inside chat

### ISSUE THREAD

**Issue by imGok** [linagora/twake-on-matrix#334]
- Compare Tele app

https://github.com/linagora/twake-on-matrix/assets/99852347/56db678f-b2f5-485b-ac34-efa0e3416486

![Image](https://user-images.githubusercontent.com/6462404/254504585-83a69c41-67f0-42c9-a59a-c06fd3f06102.png)

### DoD:
- [ ] Recommend you can search `Sticky headers`
- [x] change the logic of showing date
- [ ] update the UI of date when scrolling chat 
- [ ] After scrolling and standing still at that position, the timestamp bubble is hidden
- [ ] You need to check the behavior when scrolling to the positions => how the timestamp will display

**Comment by hoangdat** [comment]
- [ ] blink blink while scrolling

**Comment by nqhhdev** [comment]
- Find the solution `StickyHeader`

**Comment by tprudentova** [comment]
https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?type=design&node-id=11656%3A181077&mode=design&t=M0ztSpGPetb4jAGh-1
