### ISSUE TITLE
[Search] Hightlight result in search for contacts & chats

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#346]
### Desc:

- Need to highlight the keyword inside some fields include this keyword 

### DoD:

- Highlight title (`displayName`) and subtitle (`matrixId`)

![Image](https://user-images.githubusercontent.com/6462404/255100196-043b3edb-cf4d-431f-9da9-5b38d6a24452.png)

**Comment by hoangdat** [comment]
thank @imGok but this ticket aims for the search screen.

**Comment by nqhhdev** [comment]
- `feature/search` branch
