### ISSUE TITLE
[Chat] [ChatList] Time of message is displayed not correct design

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#35]
OS: Android / IOS
Device: Mobile
Twake 1.10.0

*Precondition: 
- There is existed an message conversation

### **Actual:** 
The user's typing text is having:
- color = #1b1b1f
- weight,style.height = NULL
![Image](https://user-images.githubusercontent.com/124866146/230785358-4a378625-4c0a-45bd-afd0-3cf1590f569a.png)

### **Expected:** 
The user's typing text is having:
- color = #818C99
- weight,style.height = 500,normal,16
![Image](https://user-images.githubusercontent.com/124866146/230785380-710a3b6c-f9e0-4d2a-b16c-b4d28eace313.png)

**Comment by hoangdat** [comment]
please add color for both light and dark

**Comment by imGok** [comment]
I personally choose to adapt the code to look like the design, If I put exacts styles as in Figma it looks like this : 

![Image](https://user-images.githubusercontent.com/48354990/231212528-a60a2f27-d2de-437f-9255-72013cfec18c.png)
