### ISSUE TITLE
[Notification] Enable notification for iOS in both production and sandbox

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#351]
#### Mobile:
- [ ] appId of pusher change to `com.linagora.twake.ios.debug` for dev 

#### Ops:
- add configuration for apn for `com.linagora.twake.ios.debug`
- add key restriction for `com.linagora.twake.ios.debug`

### DoD:
- still work with both production and dev app

**Comment by hoangdat** [comment]
- [ ] What happen with the latest when we disable APN and enable `firebase` again?

**Comment by drminh2807** [comment]
Don't know why, but can't receive silent notificaiton
Attempt using fcm API directly but still can receive silent notification
loud notification still can receive
draft branch:

**Comment by drminh2807** [comment]
Update:
Notification Service Extension can't change Silent notification to Loud notification
I created an independent Swift project to verify it, but NSE can't receive Silent notification
=> Can't change back to FCM, need APN

**Comment by hoangdat** [comment]
- [ ] turn on APN **AGAIN**
- [ ] turn on for both prod and sandbox

**Comment by QuangHoang1210** [comment]
Notification working well on both Android and IOS
