### ISSUE TITLE
[Chat] Improve for the swipe

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#353]
### Desc:
- Compare with Telegram 

### DoD
- [x] Support when swiping a message bubble from right to left is really smooth
- [ ] Swping a msg bubble from left to right => back to chat list

**Comment by nqhhdev** [comment]
https://pub.dev/packages/flutter_chat_ui

**Comment by hoangdat** [comment]
### Difficult point:
- investigating the way to swipe in `go_route`

**Comment by QuangHoang1210** [comment]
AC:  Swping a msg bubble from left to right => back to chat list 
--> Not yet ready to test.

Other is passed
