### ISSUE TITLE
[Chat] [ChatList] Avatar background circle is not correct design

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#37]
OS: Android / IOS
Device: Mobile
Twake 1.10.0

*Precondition: 
- There is exist an message from user who don't have avatar image

### **Actual:** 
The background circle having (W,H = 36,36)
![Image](https://user-images.githubusercontent.com/124866146/230784174-c8f3b181-3505-404b-9db1-5e301fa6049a.png)

### **Expected:** 
The background circle having (W,H = 56,56)
![Image](https://user-images.githubusercontent.com/124866146/230784200-338c0dbe-68be-42bd-8079-13ee255ff8cd.png)

**Comment by hoangdat** [comment]
how about the color @QuangHoang1210 ?

**Comment by QuangHoang1210** [comment]
@hoangdat linear-gardient

**Comment by hoangdat** [comment]
handle with #38
