### ISSUE TITLE
[Room] Remove documents, contacts option when select avatar in create room flow

### ISSUE THREAD

**Issue by drminh2807** [linagora/twake-on-matrix#373]
<img src='https://github.com/linagora/twake-on-matrix/assets/12546908/f2acc60a-6ca3-41a3-a77e-fec5851af518' width=360 />

**Comment by hoangdat** [comment]
What is it? @drminh2807

**Comment by drminh2807** [comment]
> What is it? @drminh2807

updated screenshot

**Comment by QuangHoang1210** [comment]
Passed on 2.3.1
