### ISSUE TITLE
[Upgrade Version] Chat history will be lost once user update new version

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#381]
OS:  Android / IOS
Device: Mobile
TMail version:  2.1.6

*Precondition: 
- User A had history of conversation
- User update to new version

### *Reproduce Step:
1, User updated new version
2, User tap on open Twake

### **Actual:** 

- System required user have to login again
- There is lost history of current chat

### **Expected:** 

- System keep login user
- New version is updated
- Keeping chat history

**Comment by hoangdat** [comment]
An error in matrix.linagora.com deployment
