### ISSUE TITLE
[Chat] Sharing a message is not working only on Android

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#384]
OS:  Android only
Device: Mobile
TMail version:  2.1.6

*Precondition: 
- User sent an image message
- Happen only on Android

### *Reproduce Step:
1, User tap and hold on a message
2, User tap on Share icon

### **Actual:** 

- System display a popup "Loading....Please wait" just one second and it's disappeared
- Cannot share

### **Expected:** 

- System display a popup to let user select where need to share
- Can share

### **Additional Information:** 

https://user-images.githubusercontent.com/124866146/257031616-4d980a13-5c94-4a4c-bc81-548b9f378e43.mp4

**Comment by hoangdat** [comment]
work at #434

**Comment by QuangHoang1210** [comment]
Share icon is removed on 2.2.3 Matrix.linagora.com
