### ISSUE TITLE
[Foward icon] [web] Need icon to forward on web app

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#387]
Based on Figma , we have foward icon only belong with image message, link message, file message.. excepted only single text message which without any attachs

![Image](https://user-images.githubusercontent.com/124866146/257032220-03859190-16a4-4e33-b47a-92eb4decea0f.png)

### ENV: IOS / ANDROID
Twake 2.1.6

### Step:
1, User tap on foward icon

### Actual:

No action

### Expected: 

We need design for this icon. What happen next when user click on foward icon!?

**Comment by hoangdat** [comment]
@QuangHoang1210 please update for more detail in the case of web
