### ISSUE TITLE
[Improve] Remove the add photos icon

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#394]
### ENV: IOS / ANDROID
Twake v2.1.6

### Actual:
System displayed  icon to indicate user can adding new photo from other source

### Expected:
Remove it

![Image](https://user-images.githubusercontent.com/124866146/257033042-9ba803f4-5e8c-4ab7-98fc-890987ea0737.png)

**Comment by hoangdat** [comment]
@QuangHoang1210 please update the story and request design for it
