### ISSUE TITLE
[Keyboard] As an user, I want to turn off the keyboard when I click outside keyboard sections on every screen which have keyboards

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#398]
```
GIVEN I'm twake user
WHEN I click any input fields
AND I click or scroll up-down outside of keyboard section
THEN the keyboard is dispeared
```

Actual:
System keep displaying keyboard -- it make user feel not comfortable

https://user-images.githubusercontent.com/124866146/257033750-51f13616-0c9b-4bc0-b8bf-e078f8e8e5fc.mp4

**Comment by hoangdat** [comment]
- [ ] create group
- [ ] search
- [ ] contact
- [ ] new private
- [ ] invite

**Comment by QuangHoang1210** [comment]
the bug is happened on https://github.com/linagora/twake-on-matrix/issues/224

**Comment by QuangHoang1210** [comment]
Passed on 2.3.1
