### ISSUE TITLE
[UI] [Contact] No result page is still keeping display even if user remove the searching keywords

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#399]
### ENV: IOS / ANDROID
Twake 2.1.6

### Precondtion:
- No searching result in contact searching

### Step:
1, User tap on Contact
2, User tap on searching field
3, User tap invalid contact values
4, User click on X icon to remove the search keywords

### Actual:
Keyword has been removed but the no result page with previous keywords is still displaying

### Expected: 

It should be back to contact screen

### Additional Information: 

https://user-images.githubusercontent.com/124866146/257033883-889594dc-0d43-4280-a6d2-c7ec0b0ebcf8.mp4

**Comment by imGok** [comment]
fixed on main
![Image](https://github.com/linagora/twake-on-matrix/assets/48354990/679faf50-4f75-4b7e-aebf-751b09cd1976)
