### ISSUE TITLE
[WEB] Update primary navigation bar for web

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#425]
### DES

- Add avatar icon below primary navigation bar
- Click on avatar icon will be shown settings 

![Image](https://github.com/linagora/twake-on-matrix/assets/99852347/9cb1ee9d-4a47-4ed6-86d4-be7a944bf7a6)

**Comment by shepilov** [comment]
redesign according figma

**Comment by shepilov** [comment]
@tprudentova could you add link please?
