### ISSUE TITLE
Reduce Frame rate for Chat Screen when displaying/hiding keyboard

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#433]

**Comment by sherlockvn** [comment]
### Description:
- The problem appears when opening/closing a keyboard when having a `ListView` with itemExtent set automatically and `keyboardDismissBehavior` set to `onDrag`.
- The problem only appears in the iOS platform.
- Currently, there is no way to improve it, but the Flutter team is working on an interactive keyboard and trying to resolve the problem. Hope it will have in the next version of Flutter.

### Link references:
The PRs: 
- https://github.com/flutter/flutter/pull/131895
The issues:
- https://github.com/flutter/flutter/issues/57609

**Comment by hoangdat** [comment]
- [ ] Add Frame rate screenshot for Android

**Comment by sherlockvn** [comment]
https://github.com/linagora/twake-on-matrix/assets/43041967/5e272459-2066-471e-bc60-b3767cfeb959

**Comment by sherlockvn** [comment]
Not so good, but less junky than iOS

**Comment by shepilov** [comment]
@hoangdat is it still relevant?
