### ISSUE TITLE
[Chat] [ChatList] System didn't display preview message with action when user tap and hold on a message

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#44]
OS: Android / IOS
Device: Mobile
Twake 1.10.0

*Precondition: 
- There is existed a message conversation

*Reproduce:
1, User tap and hold on a message

### **Actual:** 
There is no preview message with action is displayed as design. System displayed an action bars on the top
![Image](https://user-images.githubusercontent.com/124866146/230785872-a8c79d72-b8fa-4bcc-a888-ac0635694ffc.png)

https://user-images.githubusercontent.com/124866146/230785861-2561baff-6b6c-48ca-8f9b-153d469aad30.mp4

### **Expected:** 
The preview message with action should be displayed
![Image](https://user-images.githubusercontent.com/124866146/230785888-8732c9e5-9f2b-4d18-bfd2-7836f2396d80.png)

**Comment by hoangdat** [comment]
waiting for final design
