### ISSUE TITLE
[Chat] Twake crashed once user try to open a encrypted group chat in search result

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#475]
### Precondition 

1, Existed group chat A is encrypted and user have not yet open it before
2, User was invited to group chat A

### Reproduce

```
1, User login sucessfully on device A
2, User was invited to group chat A
3, Logout and Remove application
4, User reinstall and login sucessfully on device A
5, User tap on search bar of chat list
6, User input correctly keyword to find that group chat A
7, User tap on group chat A in searching result to open it
```

### Actual:
- Bad state: No element red screen is displaying
- System open the group chat details screen but it's loading forever.

### Expected: 
- User can open the group chat details

https://github.com/linagora/twake-on-matrix/assets/99852347/47518ba9-b2ab-43cd-a846-a9ebbd5b0e55

**Comment by sherlockvn** [comment]
The result is accidentally resolved in the newest version.

https://github.com/linagora/twake-on-matrix/assets/43041967/5846434d-88bf-4b81-8cab-36e0c2d5dc68
