### ISSUE TITLE
Still have a lot of font need to download when web app initialize

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#480]
### DoD:

![Image](https://user-images.githubusercontent.com/6462404/261879506-c644beb2-7e3b-4408-be6e-53398a8d2b5e.png)

### Desc:
- [ ] remove unnecessary fonts

**Comment by hoangdat** [comment]
- Katex is use for math rendering.

**Comment by hoangdat** [comment]
![Image](https://github.com/linagora/twake-on-matrix/assets/6462404/497e061b-035b-41e2-918a-fd9cfb96bc24)

- [ ] ?

**Comment by shepilov** [comment]
@hoangdat  do we still download all the fonts ?

**Comment by hoangdat** [comment]
yes, because it support also for Latex, Markdown, ....
