### ISSUE TITLE
Update border for video placeholder in Chat

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#481]
### Desc:

![Image](https://user-images.githubusercontent.com/6462404/261879622-9a261f8a-5fa2-4c2c-86be-4fd068595542.png)

### DoD:
- [ ] show the thumbnail in the case user did not download yet
- [ ] show with border corner

**Comment by imGok** [comment]
Is it related to iOS only ? 
On Android I have this : 
![Image](https://github.com/linagora/twake-on-matrix/assets/48354990/93454fda-eac0-4ac7-9d30-870750a4f13f)

**Comment by hoangdat** [comment]
I also saw it on web, before the image is load to bubble

https://github.com/linagora/twake-on-matrix/assets/6462404/8eb5021e-1581-4bdd-b534-3a9cd29562ad

**Comment by hoangdat** [comment]
the issue also for the preview link 

<img width="600" alt="image" src="https://github.com/linagora/twake-on-matrix/assets/6462404/dba28bab-024b-4716-83c3-7bfabc3b7dac">
