### ISSUE TITLE
[WEB] Don't redirect to login screen when not logged in

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#484]
### Precondition 

- User is not logged in
- Paste the link https://beta.twake.app/web/#/contacts

https://user-images.githubusercontent.com/99852347/261982119-b4ebc68b-a36c-4326-baca-d3aa45c272f4.mov

Expected:
- [ ] go to `home`

**Comment by hoangdat** [comment]
- the problem also for `/home`
