### ISSUE TITLE
[WEB] Can't get data when open with link

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#485]
### Precondition

- User is logged in
- Paste the link https://beta.twake.app/web/#/contacts

### Actual
- Contact page is empty and can't get data

### Expect
- go to Chat List in the case url not form of `*/rooms/:roomId`

https://github.com/linagora/twake-on-matrix/assets/99852347/ae1c75dc-cea8-4684-b4ed-bd577ceaf921

**Comment by hoangdat** [comment]
- please request an empty page in web app

**Comment by hoangdat** [comment]
- 404 page
