### ISSUE TITLE
[Web] get profile still be called in everytime app rebuild

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#494]
https://user-images.githubusercontent.com/6462404/262214105-2f2befdd-9d2a-42ca-a624-e3c79f6cb03f.mov

**Comment by sherlockvn** [comment]
I don't see get profile get called in chat list screen, but the new private chat is called a lot.

https://github.com/linagora/twake-on-matrix/assets/43041967/a62a41b3-8dbe-4389-af9b-d97c2e59e064
