### ISSUE TITLE
Actions in Message in Web/Desktop app

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#508]
### Desc: 
Design: https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?type=design&node-id=12772-64557&mode=design&t=GfMmDAtlKk4wAblx-4

![Image](https://user-images.githubusercontent.com/6462404/262624112-7323ac05-5439-4a27-bb2d-524f89f6eb12.png)

![Image](https://github.com/linagora/twake-on-matrix/assets/6462404/4a12912b-5e88-48a9-b66c-20f00429ba0a)

### DoD:
- [x] Handle hover to show action list with tooltip
- [x] Action in hover (Forward & Reply & Pin)
- [x] Composer: `+` , remove image/attachment icons, 
- [ ] image/video placeholder size
- [x] `enter` by default in web

**Comment by QuangHoang1210** [comment]
Reopened this ticket 

- [ ]  Handle hover to show action list with tooltip
- [ ]  Action in hover (Forward & Reply & Pin)
- [ ]  Composer: + , remove image/attachment icons,
- [ ]  image/video placeholder size
- [ ]  enter by default in web
