### ISSUE TITLE
[Foward Image] System not redirect user to correct chat screen when user foward image by click on Foward icon at View Image Details screen

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#555]
OS:  Android / IOS
Device: Mobile
TMail version:  2.2.5 -- Matrix.linagora.com

*Precondition: 
- User foward the image by clicking on foward icon in View Image Details screen

### *Reproduce Step:
1, User send an image successfully
2, User click on image to view details image screen
3, User click on foward icon on image
4, User select other user account who being receiver
5, User tap on send button

### **Actual:** 
- Image is fowarded but sytem not redirect to exactly chat screen which included the fowarded message just sent.
- user still at user contact list
- Checkbox is not unchecked

### **Expected:** 
System redirect user to exactly chat screen which included the fowarded message just sent:
 -- Case 1: Single foward -> redirect to current single chat screen. If the chat is not existed yet, create new single chat and redirect user to that one.
 -- Case 2: Multiple foward -> Redirect to current group chat which included all selected user account at step 4. If the group (same total member , same user account as members) chat is not existed then create new group chat and redirect user to that one.

https://github.com/linagora/twake-on-matrix/assets/124866146/a28373f1-f8a2-4a5d-83e3-865746e76171

**Comment by drminh2807** [comment]
Just fix the redirect issue
Expected doesn't support for now
Moving to backlog
