### ISSUE TITLE
[WEB] Update logo app in web

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#560]
### Currently

![Image](https://user-images.githubusercontent.com/99852347/264542144-9563cfd0-a9b8-43a5-84a8-6831cea3c019.png)

### New design

![Image](https://user-images.githubusercontent.com/99852347/264531287-8198d23d-6f35-4a31-98a1-96309d4e0a81.png)

### Design

https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?type=design&node-id=12765-17393&mode=dev

**Comment by harshoo1** [comment]
sir is there any issue ,i can help you with ?

**Comment by hoangdat** [comment]
so good, but it is well updated. Thanks you
