### ISSUE TITLE
[WEB] Update Navigation Rails and Chat List on web and desktop

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#561]
### Des

![Image](https://user-images.githubusercontent.com/99852347/264561979-0c66da14-aad4-4412-9d23-b1fae1c7df48.png)

- Design: https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?type=design&node-id=12765-17393&mode=dev

### DoD

- [ ] Update color background navigator Rails
- [ ] Add boder all for chat list screen
- [ ] `Chat's` title size and search bar  size

**Comment by hoangdat** [comment]
done
