### ISSUE TITLE
[WEB] Improvement for input row widget

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#562]
### DeS

![Image](https://user-images.githubusercontent.com/99852347/264565122-4a659c3a-e561-4b7e-8cc6-aad3cce43481.png)

![Image](https://user-images.githubusercontent.com/99852347/264565121-39e3b3aa-2f11-495a-8631-6f7066768ce6.png)

![Image](https://github.com/linagora/twake-on-matrix/assets/6462404/e39b9aee-ae42-4427-a8ff-c9b4d9c04aa2)

### Dod 

- [ ] Move `plus` icon inside Textfield, don't add `image` and `attachment` icon
- [ ] Update size for widget

**Comment by imGok** [comment]
has it been fixed already ? 
![image](https://github.com/linagora/twake-on-matrix/assets/48354990/faff290d-2a2c-471f-9138-fd02bbff11b9)
