### ISSUE TITLE
[Web] Emojis sent from web aren't displayed in mobile

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#579]
### Desc:

![Image](https://github.com/linagora/twake-on-matrix/assets/6462404/62584347-e1d9-4bc3-bd64-2b2fd24fa01f)

### DoD:
- [ ] emoji display well on web
- [ ] display the same emoji from web and mobile

**Comment by drminh2807** [comment]
Due to the large size of the color emoji font (~24MB), the Flutter team made color emojis an opt-in feature in Flutter 3.10.0
Ref: https://stackoverflow.com/a/76762811
