### ISSUE TITLE
App crash when open app

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#597]
OS: IOS
Device: Mobile
Twake version: 2.2.5

### Precondition

```
1. Go to the active chat group
2. Typing other msg
3. Kill app
4. Reopen the app

```

https://github.com/linagora/twake-on-matrix/assets/99852347/db68acd3-febc-45ba-bffe-63224125fba5

**Comment by drminh2807** [comment]
It happens when close app and reopen very quickly
It is not from Dart. I tried applying Crashlytics but can't find any report
I believe it is from Native iOS
PS: Android have no this crash

**Comment by hoangdat** [comment]
maybe the error in Hive? @nqhhdev wdyt?
