### ISSUE TITLE
[CHAT] Can't load more message when click on notification

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#598]
### Precondition

```
GIVEN Received a notification
WHEN Click on the notification
AND  Go to the conversation 
THEN Scrolling to load more old messages
```
 - Actual: Can't load more

https://github.com/linagora/twake-on-matrix/assets/99852347/ee019980-7488-402d-9d93-96256f70620e

**Comment by hoangdat** [comment]
- make sure only in the first time?

**Comment by QuangHoang1210** [comment]
### Passed on both IOS and ANDROID -- on v 2.4.17

**IOS**

https://github.com/linagora/twake-on-matrix/assets/124866146/1e777ac7-206a-43a4-9ab0-74117a12c6d7

**ANDROID**

https://github.com/linagora/twake-on-matrix/assets/124866146/3b1a80da-5dae-4406-962b-62f5b4044406
