### ISSUE TITLE
[CHAT] [CHAT Detail] Status in chat details

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#603]
### DeS

- The status in chat details is not consistent with the chat screen
![Image](https://github.com/linagora/twake-on-matrix/assets/99852347/c5af7d5c-b54d-4d47-8e91-f62bab4a0a96)

- The status in chat is hard to understand.

![Image](https://github.com/linagora/twake-on-matrix/assets/99852347/5d504458-291f-47e7-9c00-81b09773857e)

**Comment by hoangdat** [comment]
duplicated
