### ISSUE TITLE
[WEB] Sent image is cannot download and a part of image will be hidden in view mode

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#631]
OS:  WEB
Device: Laptop
TMail version:  2.2.5 -- Matrix.tom-dev.xyz // Matrix.linagora.com

### *Reproduce Step:
1, User A send an image to user B
2, User B click to view the image
3, User B click on download

### **Actual:** 

- A part of image is hidden by the grey header bars
- User cannot download image
- An popup is displayed and disappeared immediately

### **Expected:** 

- Redesign the grey header bars that will not hide the top of image
- User can download image

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/2a1849fc-d32a-4a04-9fe0-c7accb6a822d)

https://user-images.githubusercontent.com/124866146/268152763-55fce916-32d4-4f68-adfd-0d727ccd6bd8.mp4

**Comment by hoangdat** [comment]
Please confirm it in implementation side.

**Comment by nqhhdev** [comment]
I tested it, works well on main branch


https://github.com/linagora/twake-on-matrix/assets/99852347/a5d19932-8f42-478a-a8e9-f354f2c8b733
