### ISSUE TITLE
[WEB] Cannot open the sent pdf files

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#633]
OS:  WEB
Device: Laptop
TMail version:  2.2.5 -- Matrix.tom-dev.xyz // Matrix.linagora.com

### *Reproduce Step:
1, User A send a pdf/excel/doc file to user B
2, User B click to view the file

### **Actual:** 
- User cannot view the pdf file

### **Expected:** 

- User can view the pdf in preview view inside app

https://user-images.githubusercontent.com/124866146/268154570-2043f0dc-8b28-4635-9bad-4b4e4b9499bd.mp4

**Comment by hoangdat** [comment]
@QuangHoang1210 please create ticket in Board for designers (Designing column)

**Comment by QuangHoang1210** [comment]
https://www.notion.so/50f84b59e5e447a48b2d0500d09bcc78?v=195fb544755241748fe278c3af030232&p=9316a97b33804a43878c9028e7f1a4d2&pm=s

@hoangdat

**Comment by hoangdat** [comment]
### DoD:
- [ ] click in PDF message bubble to open it in browser (new tab)

**Comment by QuangHoang1210** [comment]
**Issue:** User cannot preview pdf file in new browser tab. System will download the file at the moment

**Reproduce step:**
1, User send or receive a pdf file
2, User click on pdf file in bubble message

**Actual**
User cannot preview pdf file in new browser tab. System will download the file at the moment

**Expected**
As an user, I want to preview my pdf file which I sent/received in message

[Following the AC in notion](https://www.notion.so/50f84b59e5e447a48b2d0500d09bcc78?v=195fb544755241748fe278c3af030232&p=9316a97b33804a43878c9028e7f1a4d2&pm=s)

https://github.com/linagora/twake-on-matrix/assets/124866146/1f280f3b-8d88-4889-b32b-9d1b85f7308f

**Comment by QuangHoang1210** [comment]
Passed on 2.3.5
