### ISSUE TITLE
[ANDROID] User cannot download the image which he sent or received

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#635]
OS: only ANDROID
Device: MOBILE
TMail version:  2.2.5 -- Matrix.linagora.com

### *Reproduce Step:
1, User A send an image to user B
2, User B click to view the image
3, User B click on download

### **Actual:** 

- User cannot download image
- An popup is displayed and disappeared immediately

### **Expected:** 

- Redesign the grey header bars that will not hide the top of image
- User can download image

https://github.com/linagora/twake-on-matrix/assets/124866146/200dc64e-a6bb-48df-8382-45b10142dbb5

**Comment by nqhhdev** [comment]
I tested it on main branch. Work well

https://github.com/linagora/twake-on-matrix/assets/99852347/331e8dcb-3c4e-46ba-ab6d-1970f1488fc6

**Comment by QuangHoang1210** [comment]
Passed on 2.3.1
