### ISSUE TITLE
[Android/IOS/WEBSITE] System auto trim empty space when user want to break the line multiple times

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#638]
OS: IOS/ANDROID/WEBSITE
Device: MOBILE/LAPTOP
TMail version:  2.2.5 -- Matrix.linagora.com

### *Precondition:
1, A, B in a chat conversation

### *Reproduce Step:
1, User A input as "Quang quang 1234 [enter] [enter] [enter] quang quang 123"
2, User A click send message

### **Actual:** 

- The empty space [enter] [enter] [enter] is auto trim
- Message will be:
"Quang quang 1234
quang quang 123"

### **Expected:** 

- The empty space [enter] [enter] [enter] is not be trim
- Message will be:
"Quang quang 1234
[enter]
[enter]
[enter]
quang quang 123"

https://user-images.githubusercontent.com/124866146/268174258-7ef33a1d-04fe-4f29-b9e2-dbe0eca4c750.mp4

**Comment by hoangdat** [comment]
### DoD:
- [ ] keep only one break line between paragraph

**Comment by QuangHoang1210** [comment]
Reopened this ticket cause it happen again on 2.4.0
