### ISSUE TITLE
[Android/IOS] Image caption is not supported now,  its UI broken

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#642]
OS: IOS/ANDROID
Device: MOBILE
TMail version:  2.2.5 -- Matrix.linagora.com

### *Reproduce Step:
1, User A select an image in Device Gallery
2, User A enter a caption

### **Actual:** 

- Error msg: Caption for image is not supported yet

### **Expected:** 

- Can add caption for image

https://user-images.githubusercontent.com/124866146/268180355-4b92c1fb-9710-4b9c-ad1c-50210820d4e7.mp4

**Comment by hoangdat** [comment]
disable caption for this sprint
