### ISSUE TITLE
[Android/IOS] Fowarding message to multiple recipients are not working

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#644]
OS:  Android / IOS
Device: Mobile
TMail version:  2.2.5 -- Matrix.linagora.com

*Precondition: 
- User foward message to multiple recipients

### *Reproduce Step:
1, User send a message successfully
2, User click on message
3, User select Foward
4, User select multiple user (at least 2)

### **Actual:** 
- User can select multiple user
- The tiny counter of recipients belong to Send button is missing

### **Expected:** 
- User can select multiple user
- The tiny counter of recipients belong to Send button should be increased

https://user-images.githubusercontent.com/124866146/268236454-bacf1401-5f35-46bb-93ea-08374360e303.mp4

**Comment by tprudentova** [comment]
Duplicate for #217
