### ISSUE TITLE
[Android/IOS] Foward file which from device that flow is not correct as AC

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#646]
OS: IOS/ANDROID
Device: MOBILE
TMail version:  2.2.5 -- Matrix.linagora.com

### *Reproduce Step:
1, User A open to view a file (xlsx,doc,pdf,..) in device
2, User A select share via Twake
3, User select one in contact list
4, User click Send button

### **Actual:** 

- System redirect user to correct chat screen. File was sent successfully

### **Expected:** 

-  File was sent successfully. System redirect user to file preview screen at step 1

[Base on documentation](https://www.notion.so/50f84b59e5e447a48b2d0500d09bcc78?v=195fb544755241748fe278c3af030232&p=0a46b3382dd9475ca06aee2415045d1b&pm=s)

https://user-images.githubusercontent.com/124866146/268243917-ed91ba19-2a0a-48cb-825f-74c75a4b74cd.mp4

**Comment by hoangdat** [comment]
outdate and please ref to #1388
