### ISSUE TITLE
Create dialog

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#69]
### Desc:
- need permission to access contact: handle cases: granted/not granted/deny
- need a `contact picker` to pick contacts
- can re-use this component in many use-case
- input: null
- output: list of selected contacts

### DoD:
- [x] list all the contact from phone book: avatar, name, email 
- [x] search bar: to filter contacts

**Comment by hoangdat** [comment]
- [ ] choose contact dependencies

**Comment by QuangHoang1210** [comment]
passed
