### ISSUE TITLE
Jump to position in Chat from the List of Images

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#713]
### Desc:

- From the list of images. user want to jump to the message and see messages around it

### DoD:
- [ ] Edit `ChatDetailsMediaPage` to pop back chat room with `eventId` when user want to scroll to image/video event
- [ ] Edit `onPushDetails` in `ChatController` to get the `eventId` above
- [ ] Scroll to `eventId` by exist function `scrollToEventId`

**Comment by sherlockvn** [comment]
https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?type=design&node-id=9899-152841&mode=design&t=OfghmqC3oDlecUPX-4

**Comment by sherlockvn** [comment]
web: waiting for design

**Comment by sherlockvn** [comment]
https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?type=design&node-id=22240-497871&mode=design&t=WWrT6ZsPAypV3Qtq-4
