### ISSUE TITLE
Lost notification in Web

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#726]

**Comment by hoangdat** [comment]
please verify it for android

**Comment by drminh2807** [comment]
[Web] on my side still show noti
it is place to show noti on web
lib/widgets/local_notifications_extension.dart:63
![Screenshot 2023-10-10 at 14 51 20](https://github.com/linagora/twake-on-matrix/assets/12546908/22bfeeb8-ae7c-4737-8985-454216efff7d)

**Comment by imGok** [comment]
I don't have any issues with web version, I don't receive any notifications in Android virtual device. I can't build on real device (have an iPhone)

**Comment by hoangdat** [comment]
> I don't receive any notifications in Android virtual device

Please send me the SHA-1 in your PC

**Comment by hoangdat** [comment]
no problem with notification. Make sure:
- not disable chrome notificaiton in System settings
- allow notificaiton inside chrome
