### ISSUE TITLE
[Web] Improve the flow of download file

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#735]
### Desc:
- Right now, download file make user need to wait and can not do anything else

https://github.com/linagora/twake-on-matrix/assets/6462404/296ca7e0-c4a1-4ef9-9652-d5e1cb041075

### DoD:
- [ ] move the progress to the bottom of the app
- [ ] user still need to work other stuffs in the app 
- [ ] only web

**Comment by drminh2807** [comment]
Dont know how to implement
use dialog or snackbar ?
I think we should add `cancel` button inside ProgressDialog


![Image](https://github.com/linagora/twake-on-matrix/assets/12546908/a0ae7e60-262e-474f-ad86-b45c6e487078)
