### ISSUE TITLE
[Web] Reaction for message

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#743]
### Desc:
- https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?type=design&node-id=15256-68071&mode=dev

![Image](https://github.com/linagora/twake-on-matrix/assets/6462404/5143f27e-4190-433c-899b-882a10f67ae7)

### DoD:
- [ ] icon picker 
- [ ] icon display in message bubble

**Comment by tprudentova** [comment]
Duplicate for #994
