### ISSUE TITLE
[Mobile] Download image/video using stream

### ISSUE THREAD

**Issue by sherlockvn** [linagora/twake-on-matrix#746]
### Desc:
- [ ] Using `dio` with `response.stream` -> stream
- [ ] use new decryption function that using stream to decrypt file
- [ ] store directly decrypted file to database
- [ ] Replace MatrixFile with FileInfo for Download file
- [ ] Schedule delete file from time to time

**Comment by hoangdat** [comment]
- [ ] BAD_JSON 

http toolkit -> tracking the http request
