### ISSUE TITLE
[Notification] System redirect user to 404 not found page when he click on notification on IOS after 2-3 minutes

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#755]
OS: IOS only
Device: MOBILE
TMail version:  2.3.1 -- Matrix.linagora.com

### *Precondition:
- User A is offline
- User A and B not yet chat with each other before

### *Reproduce Step:
1, User B invite user A to chat with new message
2, User A reconnect wifi again -> User A see the notification
3, User A not click on notification and wait until 2-3 minutes
4, User click on notification

### **Actual:** 

System redirect user A to 404 not found page

### **Expected:** 

User A must be redirected to chat details screen to accept the invitation

--404 not found

https://github.com/linagora/twake-on-matrix/assets/124866146/74f46d9c-ee9b-444c-ab39-5b23ba853252

--turn on/off wifi

https://github.com/linagora/twake-on-matrix/assets/124866146/cbceea2f-5ca3-4d76-8d71-9f0b42fabf94

**Comment by hoangdat** [comment]
- room is not created in client -> 404 in Go Route
