### ISSUE TITLE
Use keyboard to select suggestion item when tag a people (up/down/enter)

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#759]
### DoD:
- [ ] can use `up` keyboard to move up in suggestion list
- [ ] can use `down` keyboard to move down in suggestion list
- [ ] can use `enter` keyboard to select an item 
- [ ] selection on the top of the list
- [ ] limit 4.5 items in suggestion list
- [ ] new style for web + mobile

**Comment by drminh2807** [comment]
TypeAHead maybe support keyboard control
https://github.com/search?q=repo%3AAbdulRahmanAlHamali%2Fflutter_typeahead%20KeyboardSuggestionSelectionNotifier&type=code

https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/502
https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/517

**Comment by drminh2807** [comment]
Flutter 3.13.7 support it automatically via InkWell


![Image](https://github.com/linagora/twake-on-matrix/assets/12546908/dddd4db1-6b0f-4e71-b00f-da5860365b0a)



https://github.com/linagora/twake-on-matrix/assets/12546908/cbb7075b-34e5-4e4a-8982-79733e1ab770

**Comment by hoangdat** [comment]
ok, go with `3.13`
