### ISSUE TITLE
Init Recovery key in the first time connecting to Twake

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#79]
### Desc:
```
when starting on a new device (else nothing to do), query the vault to see if there is a Recovery Key.

if yes (== another device initialized the user account), launch the restore process using this secret and keys stored in Matrix server (instead of exchange key process)

if no (== this is the first connection of this user):

launch normal Matrix initialization
at the end, launch backup process

store keys in Matrix server
store secret in vault
```

API: https://publicgroup.pages.linagora.com/oss/twake/tom-server/#/Vault%20API/post__twake_recoveryWords

```
/POST /_twake/recoveryWords
```

### DoD:
- [x] run `maxs-deployment` successfully
- [ ] hide the back-up setting in the ToM client
- [ ] when connected to the ToM, POST the recovery key

**Comment by hoangdat** [comment]
Spent: 2 HD

- [ ] pending point: can not `DELETE` recoveryKey so can not test. -> create the ticket in Tom-server
- [ ] workaround solution: request to add more user in LDAP side -> need connect with Xavier
- [ ] start in coding client side
  - you need to set up the `Dio` for Request (Done from Khai PR: #71)
  - Usecase: interactor 
  - RecoveryRepository 
  - RecoveryNetworkDatasource
  - RecoveryApi (define the API for POST the recovery key)

**Comment by hoangdat** [comment]
- Spent: 1HD for review Contact Picker
- 1HD: for `data` and `domain`

**Comment by imGok** [comment]
Use Cases : 
UC1 - No recovery words stored in ToM Server AND encryption disabled in homeserver
ToM client : Should generate words, send them to ToM Server and homeserver (enable encryption)

UC2 - Recovery words stored in ToM Server AND encryption disabled in homeserver (anomaly, shouldn't happen)
ToM client : Enable encryption in homeserver and send recovery key (from ToM Server)

UC3 - No recovery words stored in ToM Server AND encryption enabled in homeserver (anomaly, shouldn't happen)
ToM client : ?

UC4 - Recovery words stored in ToM Server AND encryption enabled in homeserver
ToM client : 
  If device is known => X 
  if device is unknown => signup current device to known devices in homeserver (by using recovery words stored in ToM) - cross -signing

**Comment by hoangdat** [comment]
### Usecase for LINAGORA 
```
Xavier set up new Maatrix for Lin, with the LDAP
So, Dat, join the Linagora matrix via ToM client 
First time, I sign in to the app,
Recevery will be automatically generated and post to the ToM (and homeserver)
I will sign inanother device, data will not be lost
```

**Comment by hoangdat** [comment]
- With only Recovery key, we can not back-up the data
- Need to spend more time on key exchanging, device verification, ....
