### ISSUE TITLE
Apply new Search inside Chat design

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#800]
### Desc:

Web:

![Image](https://github.com/linagora/twake-on-matrix/assets/6462404/aeb88971-252c-407e-9922-d72a12d1494e)

Mobile:

![Image](https://github.com/linagora/twake-on-matrix/assets/6462404/4ec8e2c2-e3fd-4aa9-9431-5dbf8eeadecc)

- Share timeline between `search` and `chat` screen

### DoD:

- [ ] widget for search result inside chat
- [ ] mobile
- [ ] desktop
- [ ] tablet
- [ ] click to scroll to the message in chat

**Comment by hoangdat** [comment]
- [ ] search result item = chat list item (except file)
- [ ] search result item file: reuse from bubble
- [ ] jump chat screen (no need highlight)

**Comment by QuangHoang1210** [comment]
Improve -> related to 2 tickets:
https://github.com/linagora/twake-on-matrix/issues/1048
https://github.com/linagora/twake-on-matrix/issues/1047
