### ISSUE TITLE
[tag] remove pill for tag

### ISSUE THREAD

**Issue by sherlockvn** [linagora/twake-on-matrix#807]
### Desc:
- current: pill to show a tagged user
- need to apply new design

![Image](https://github.com/linagora/twake-on-matrix/assets/6462404/6ca35b18-93d1-47df-b8aa-d460acdb6ef4)

https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?type=design&node-id=16231-70272&mode=design&t=iCnESc0DrKQuPZAf-4

**Comment by nqhhdev** [comment]
duplicated #893
