### ISSUE TITLE
[Web] Select text in Message bubble by mouse

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#849]
### Desc:
- at the moment, user hard to select text to copy in Chat by mouse
- example: 

https://user-images.githubusercontent.com/6462404/277494965-315b3f7d-222f-406b-8db6-3e4e21dac44b.mov

### DoD:
- [ ] can select the whole text or a part of text by mouse

**Comment by hoangdat** [comment]
- [ ] try to add Ctrl+C to copy selected text
- [ ] try to select text in bubble which have formatted (include tag, code block, ...)

**Comment by nqhhdev** [comment]
#892

**Comment by QuangHoang1210** [comment]
Can select by mouse and copy
