### ISSUE TITLE
[Notification] Click to notification, jump to unread message in Chat

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#858]
### Desc:
- Add widget event`unread`
- Jump to last event unread

### DoD

**Comment by nqhhdev** [comment]
### WHAT IS `fullyRead`
Given room `TEST UNREAD MESSAGE` has 3 members.
The sender is `oliviaparker` and receivers are `henryjones` and `sophiarichardson`.

### Demo
- `oliviaparker` sends some message

![IMG_1F0616225E28-1](https://github.com/linagora/twake-on-matrix/assets/99852347/0f668373-19e0-4fc6-97cb-eae407bc0167)

- `henryjones` is read

<img width="1680" alt="Screenshot 2023-12-13 at 12 05 16" src="https://github.com/linagora/twake-on-matrix/assets/99852347/0aa68a2e-0eae-4bb9-93fd-678e0859e8ca">

- `sophiarichardson` is unread

<img width="1680" alt="Screenshot 2023-12-13 at 12 05 05" src="https://github.com/linagora/twake-on-matrix/assets/99852347/4bcdf18f-5533-48c9-87ad-9c1a486331aa">

- `fullyRead` of `henryjones`

<img width="1680" alt="Screenshot 2023-12-13 at 12 21 25" src="https://github.com/linagora/twake-on-matrix/assets/99852347/96378331-0334-4015-9c13-72d5be14fe23">

- `fullyRead` of `sophiarichardson`

<img width="1680" alt="Screenshot 2023-12-13 at 12 07 26" src="https://github.com/linagora/twake-on-matrix/assets/99852347/0d3161aa-bdbc-4d21-8b8a-ef8c2c22f990">

**Comment by nqhhdev** [comment]
### Case 2 

- `oliviaparker` Send 3 new messages 

![IMG_9650](https://github.com/linagora/twake-on-matrix/assets/99852347/66ef4ea8-7486-477e-8990-040794b5b8b0)
![IMG_9651](https://github.com/linagora/twake-on-matrix/assets/99852347/360eefdb-25e3-4800-a733-d0e547d18f2f)

- `henryjones ` and `sophiarichardson ` received new message 

<img width="1680" alt="Screenshot 2023-12-13 at 12 26 28" src="https://github.com/linagora/twake-on-matrix/assets/99852347/51016a20-97ba-4a0f-9d10-b05775c7f91f">

![Simulator Screenshot - iPhone 15 - 2023-12-13 at 12 26 47](https://github.com/linagora/twake-on-matrix/assets/99852347/621b9cbf-42ae-4d5c-b1cf-e2ad19d6cecf)
