### ISSUE TITLE
Gromming Registration

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#863]
### Desc:
- register on web-base UI? button?
- what happen after completed register?
- prevent user need to input credentials again? OIDC? -> front-end (cookies store in web)
- [mobile] open app: (i) app existed - (ii) app not existed must open store
  - (i) deep link ? store link?
  - (ii) dynamic link? 
- [web] ????

### Env:
- register.tom-dev.xyz

**Comment by drminh2807** [comment]
# Web open app
- Firebase Dynamic Link is the best fit, but will be expired in Aug 25 2025
- Alternative, [branch.io](branch.io) free for users with up to 10k monthly active users (MAU), $5/mo for each 1k MAU over 10k.
- Javascript can open app, other wise open Store, but android chrome open both
```
window.location = 'imdb://title/tt3569230';
setTimeout(function() {
  window.location = 'itms-apps://itunes.apple.com/us/app/imdb-movies-tv/id342792525'
}, 250);
```
- To make app can catch matrix.to link, use 
   - [AppLinks](https://docs.flutter.dev/cookbook/navigation/set-up-app-links) for Android (Already have)
   - [Universal links](https://docs.flutter.dev/cookbook/navigation/set-up-universal-links) on iOS (Need config)

**Comment by hoangdat** [comment]
Case1: one of our app was installed
Link for register:
### for register site:

```
window.location = 'imdb://title/tt3569230';
setTimeout(function() {
  window.location = 'itms-apps://itunes.apple.com/us/app/imdb-movies-tv/id342792525'
}, 250);
```

- Android:
  - https://twake.app/register?param1=abc&param2=bcd (AppLinks)
  - PlayStore: {link play store}
- iOS:
  - https://twake.app/register?param1=abc&param2=bcd (Universal link)
  - App Store: {link app store}
- web:

**Comment by hoangdat** [comment]
## Case 2: no app was installed before

**Comment by drminh2807** [comment]
# Open register from OIDC
1. Register OIDC will be open with params: `redirect_url=tmail://`
2. After registerd, OIDC Web should redirect to redirect_url with param. Eg: `tmail://registered?to_app=twake`
3. Tmail should check `to_app` and open twake deeplink
4. If cannot, open `store_url` to download, also need copy to clipboard the `redirect_url` with param to continue register flow after app installed

# Open from mobile browser
- Register OIDC wont have redirect_url
- After registered, call this script
```javascript
window.location = 'https://twake.app/register?param1=abc&param2=bcd';
if (isMobileBrowser) {
  setTimeout(function() {
    window.location = isAndroid ? playStoreUrl : appStoreUrl
    // Need to check register state after app installed
    copyToClipboard('https://twake.app/register?param1=abc&param2=bcd')
  }, 250);
}
```

**Comment by hoangdat** [comment]
# Case 1:
1. `Flutter`: add `post_registered_redirect_url={mobileAppUrl}` twake: `twake.chat://` - tmail: `teammail.mobile://`
    `JS`: handling `post_registered_redirect_url`
2. `JS`: Register page -> redirect to `post_registered_redirect_url` + optional params: 
Eg: 
    - Plain: `teammail.mobile://registered?open_app=twake.chat://&play_store_url=https://google.link&app_store_url=https://apple.link` 
    - Encoded: `teammail.mobile%3A%2F%2Fregistered%3Fopen_app%3Dtwake.chat%3A%2F%2F%26play_store_url%3Dhttps%3A%2F%2Fgoogle.link%26app_store_url%3Dhttps%3A%2F%2Fapple.link`
3.  `Flutter`: 
```dart
if (UrlLaucher.canOpenUrl(link["open_app"]) {
    UrlLauncher.openUrl(link["open_app"]);
} else {
    final storeUrl = Platform.iOS ? link["app_store_url"] : link["play_store_url"];
    UrlLauncher.openUrl(storeUrl);
}
```

**Comment by hoangdat** [comment]
# Case 2:
1. `JS`: check `post_registered_redirect_url` not existed 
2. Do register as normal
3. need to handle redirect for each app:
  Fx: Twake Chat 
    - in Android mobile browser:
    - in iOS mobile browser:
    - in web: open web app (https://beta.twake.app/web/#/registered)
```
    window.location = 'https://beta.twake.app/web/#/registered';
```

**Comment by hoangdat** [comment]
Play Store:
- https://play.google.com/store/apps/details?id=com.twake.twake
- https://play.google.com/store/apps/details?id=com.linagora.android.teammail

App Store: 
- https://apps.apple.com/us/app/twake/id1588764852
- https://apps.apple.com/us/app/team-mail/id1587086189

**Comment by hoangdat** [comment]
### Flutter:

**Comment by drminh2807** [comment]
# Flutter as original app
## Task 1: Open register OIDC and handle `post_registered_redirect_url` after registered
- [ ] Open register OIDC with param `post_registered_redirect_url=twake.chat%3A%2F%2F` 
- [ ] Handle `post_registered_redirect_url` after registered: Do following code in step 3 of case 1 (https://github.com/linagora/twake-on-matrix/issues/863#issuecomment-1784890967)
<details>
  <summary>Show dart code</summary>

  ```dart
if (UrlLaucher.canOpenUrl(link["open_app"]) {
    UrlLauncher.openUrl(link["open_app"]);
} else {
    copyToClipboard(link["open_app"]);
    final storeUrl = Platform.iOS ? link["app_store_url"] : link["play_store_url"];
    UrlLauncher.openUrl(storeUrl);
}
```
</details>



# Flutter as opened app
## Task 1: [Web] Handle url path `/registered`
Eg: https://beta.twake.app/web/#/registered
It should show button to open OIDC
Question: What happen for case logged in ?
Question: Should pass `home_server_url` as param of path ?

## Task 2: [Mobile] Handle deep link `twake.chat://registered`
It should show same page with web

## Task 3: [Mobile] Check clipboard for first install
If first install and clipboard equal `twake.chat://registered`
=> Show registered page instead login page

## Note:
- No need AppLinks or Universal Links anymore, because we used deeplink `twake.chat://` to check app installed instead AppLinks/Universal links `https://`

**Comment by hoangdat** [comment]
- Redirect from App to Web and then Web to App?

Case 1: open register from a flutter app
1. Flutter will open the register link with params: `post_registered_redirect_url={mobileAppUrl}`
Fx: 
```
https://register.tom-dev.xyz?post_registered_redirect_url=twake.chat://registered
```
2. After completed register, user will want to open an app (fx: twake). Please redirect to the `post_registered_redirect_url` with some params:
- `open_app`: `twake.chat://` or `teammail.mobile://` or `twake.drive://`
- `play_store_url`: 
  - twake: https://play.google.com/store/apps/details?id=com.twake.twake
  - teammail: https://play.google.com/store/apps/details?id=com.linagora.android.teammail
  - if tdrive: no link 
- `app_store_url`:
  - twake: https://apps.apple.com/us/app/twake/id1588764852
  - teammail: https://apps.apple.com/us/app/team-mail/id1587086189

- and this must use encodeBase64Url


* Question: Just to show all the products with redirect link inside each product.  

Case 2: open register from a browser
1. check if `post_registered_redirect_url` existed
2. if yes, do as Case 1.
3. if no, register as normal
 i. if it is normal browser. Open web app 
 
 ```
 window.location = 'https://beta.twake.app/web/#/registered';
 ```
 
 - twake: https://beta.twake.app/web/#/registered
 - teammail: https://tmail.linagora.com
 - tdrive: https://tdrive.linagora.com/
 
 ii. if it is mobile browser. Run this script
 
 ```
 window.location = 'twake.chat://registered';
 if (isMobileBrowser) {
   setTimeout(function() {
     window.location = isAndroid ? playStoreUrl : appStoreUrl
     // Need to check register state after app installed
     copyToClipboard('twake.chat://registered')
   }, 250);
 }
 ```
 - twake: `twake.chat://registered`
 - teammail: `teammail.mobile://registered`
 - tdrive: `https://tdrive.linagora.com/`


When you can complete the JS site with it? 
Khaled: try to complete it on Friday.

- How to bypass the blockers of octopush?
Not easy to change to work with other provider to build in local.

Khaled: docker image: bypass phone verification -> create a branch in register repository

**Comment by hoangdat** [comment]
## Case 1:

### for Twake app:
- call register: 
```
https://register.tom-dev.xyz?post_registered_redirect_url=twake.chat://registered
```
- after user completed registration, click on Twake app. `JS` will call to 
```
twake.chat://registered?open_app=twake.chat://&play_store_url=https://google.link&app_store_url=https://apple.link
```
- Flutter need to handle (i)opening app or (ii)redirect user to store (in browser not in custom tab)
- (i) open app -> go to OIDC (no need more interactions from user)

**Comment by hoangdat** [comment]
## Register site
### Sign up
1. Mobile
Twake screen -> Create Twake Id -> Register Web app (register.***) -> input form -> success -> loginToken
-> Automatically back to app with loginToken (post_registered_redirect_url), app need to handle loginToken
2. Web
Case 1: beta.twake.app -> register complted -> need to back to app with token AUTOMATICALLY
Case 2: landing page of Linagora or somewhere -> register complted -> list of apps -> open app with token 


### Sign in
1. Mobile
TwakeId screen -> Sign in -> Register Web app (register.***) -> Sign in tab -> username/passowrd -> loginToken
-> How to transfer loginToken automatically back to app?
Register web: - automatically back to app (post_login_redirect_url)
App: Receive token -> process app to login -> work as normal
2. Web
Case 1: beta.twake.app -> login completed in Register site -> need to back to app with token AUTOMATICALLY
App: will redirect automatically to Register site (post_login_redirect_url)
Register app: complete the sign in -> automatically go back to the app

Case 2: landing page of Twake Workplace -> login completed in Register site -> list of apps -> user can open app with token
