### ISSUE TITLE
Missing logic filter the user who existed / non-existed in contacts in Chat Invitation flow

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#865]
OS: IOS/ANDROID/WEB
Device: MOBILE /  Laptop
TMail version:  2.3.5 -- Matrix.linagora.com

### *Precondition:
User A is non-existed in contact
User B is exsited in contact

### *Reproduce Step:
1, User invite user A to new chat
2, User invite user B to new chat

### **Actual:** 
1, System displayed invitation dialog but the design (error message content, UI of dialog) is not same with figma 
[[Notion description] ](https://www.notion.so/50f84b59e5e447a48b2d0500d09bcc78?v=195fb544755241748fe278c3af030232&p=264826d961d748f8867f57c41ed8198c&pm=s)
[[Figma]](https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?type=design&node-id=12232-223221&mode=design)

2, System still display invitation dialog

### **Expected:** 

1, Invitation dialog should be same with figma design

2, Only non-existed user in contact will be received the chat invitation
Should filter user existed/non-exsited 
-> with user non-exsited in contact then system will display invitation dialog
-> with user existed in contact then user will be added directly in the new chat without invitation dialog

[[Notion description]](https://www.notion.so/50f84b59e5e447a48b2d0500d09bcc78?v=195fb544755241748fe278c3af030232&p=264826d961d748f8867f57c41ed8198c&pm=s)

---> NOTED: Please take care the Decline/accept invitation dialog also when one user receive the chat invitation

**Video**

https://github.com/linagora/twake-on-matrix/assets/124866146/4a08c175-ae89-40bb-b9a3-4fbd2975738b

**Comment by nqhhdev** [comment]
Improve it in ticket: #879
