### ISSUE TITLE
User cannot close the Chat invitation dialog

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#866]
OS: IOS/ANDROID/WEB
Device: MOBILE /  Laptop
TMail version:  2.3.5 -- Matrix.linagora.com

### *Reproduce Step:
1, User A invite user B to new chat
2, User B click to view the invitation chat 

### **Actual:** 
1, User cannot close the invitation chat dialog

### **Expected:** 

1, User can close the invitation chat dialog

---> NOTED: Please take care this behaviour on mobile also

**Video**

https://github.com/linagora/linagora-design-flutter/assets/124866146/c5cf983f-f444-471d-a6ad-acad8d2828cf

**Comment by nqhhdev** [comment]
- ticket #879

**Comment by hoangdat** [comment]
please verified in v2.4.0
