### ISSUE TITLE
Missing limitation of images/file when sending message

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#867]
OS: IOS/ANDROID/WEB
Device: MOBILE /  Laptop
TMail version:  2.3.5 -- Matrix.linagora.com

### *Precondition:
User send one or several images/file which have at least one file with size > 10MB

### *Reproduce Step:
1, User send one or several images/files which have at least one with size > 10 MB

### **Actual:** 
1, File sent successfully one by one

### **Expected:** 

1, Single sending > 10mb ==> Displaying popup error message 
2, Multiple sending (one of them > 10mb) ==> Displaying popup error message

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/fd1dc1ab-7e7d-4fe1-a52d-7520e453413a)

[[Notion description]](https://www.notion.so/50f84b59e5e447a48b2d0500d09bcc78?v=195fb544755241748fe278c3af030232&p=9245d553b91241878f579df2cfdaa0f4&pm=s)
[[Figma]](https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?type=design&node-id=12219-211918&mode=design)

---> NOTED: Please take care this behaviour on both web/mobile also

**Video**

https://github.com/linagora/twake-on-matrix/assets/124866146/514930f4-9e18-418d-999c-c971bc4dc7b0

**Comment by hoangdat** [comment]
why `10Mb`?
