### ISSUE TITLE
[Improvement] Missing current password input in Change password flow

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#869]
OS: IOS/ANDROID/WEB
Device: MOBILE /  Laptop
TMail version:  2.3.5 -- Matrix.linagora.com

### *Reproduce Step:
1, User click on account setting
2, User click on Security
3, User click on CHange password

### **Actual:** 
1, System display Change password popup without Current Password input field

### **Expected:** 

1, Improve: Add Current Password input field

[[Notion description - mục WEB phần 3]](https://www.notion.so/50f84b59e5e447a48b2d0500d09bcc78?v=195fb544755241748fe278c3af030232&p=5da35da07baf40258c29a65549f1315b&pm=s)

NOTED: Take a look both web/mobile

**Image**

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/8f8f9215-3aec-4fa0-b41c-6f425f894b0f)

**Comment by hoangdat** [comment]
hide it
