### ISSUE TITLE
[Pin permission] Only Group creater can pin the message -> Everyone can pin the message

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#875]
OS: WEB
Device: Laptop
TMail version:  2.3.5 -- Matrix.linagora.com

### *Precondition:
User A: Group chat creator
User B: Chat member

### *Reproduce Step:
1, User B pin a message

### **Actual:** 
Cannot pin a message. System display error message "No Permission"

### **Expected:** 

Everyone in group can pin a message.

**Video**

https://github.com/linagora/twake-on-matrix/assets/124866146/761b86c8-6581-4433-a902-b56fcbe6a033

**Comment by hoangdat** [comment]
please help me create a user story in Twake board in notion, so all the people can discuss about it. Thanks @QuangHoang1210

**Comment by hoangdat** [comment]
duplicated #1400
