### ISSUE TITLE
[Android][iOS] Gromming Synchonize contact's device

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#876]
### Desc:
- cache in app or not?
- how to request to Twake to check existed twake account? (phone or email)?
- UI?
- what happen if user don't have twake acc before?
- what happen if user have matrix account?

**Comment by hoangdat** [comment]
- Organization contacts: `/lookup` -> DONE
- Phonebook contacts

**Comment by hoangdat** [comment]
### Cache:
- phone number: required 
- hash: requried 
- twakeId: optional 
- matrixId: optional

**Comment by hoangdat** [comment]
### Initialize contacts:
- how to load contact from phone book?
- permission?
- UIUX? Design?

**Comment by hoangdat** [comment]
### Update Contacts:
- if no cache existed, read from phone book

**Comment by hoangdat** [comment]
- [ ] package: `flutter_contact`

**Comment by nqhhdev** [comment]
### Get `hash_details `

### Desc 

###

**Comment by nqhhdev** [comment]
### Looks up the set of Matrix User IDs which have bound the 3PIDs given, if bindings are available

### Desc
- Create `HashDetailsResponse` 

```
class HashDetailsResponse extends Equatable {
    final List<String>? algorithms;
    final String? lookupPepper;

    HashDetailsResponse({
        this.algorithms,
        this.lookupPepper,
    });
}
```
- Create `getHashDetails` method in `domain` and `api` layerr
### DoD 
- [ ] Get hash details

### Docs

https://spec.matrix.org/v1.6/identity-service-api/#get_matrixidentityv2hash_details

**Comment by nqhhdev** [comment]
### Get phone book

### Decs
- get current contacts in the phone 

### DoD
- [ ] Get all contacts in the phone
- [ ] If contacts changed => Update
### Docs
- Lib: https://pub.dev/packages/flutter_contacts

**Comment by nqhhdev** [comment]
### Get all current contacts on the phone
### Decs

### DoD
- [ ] Get all current contacts on the phone
### Docs
- Lib: https://pub.dev/packages/flutter_contacts

**Comment by nqhhdev** [comment]
### Validate whether the contact exists in the server or not

### Decs

### DoD

**Comment by nqhhdev** [comment]
### Store contacts to local database

**Comment by nqhhdev** [comment]
### Get contacts from local database

**Comment by nqhhdev** [comment]
### Update contacts on local database

**Comment by nqhhdev** [comment]
### Listens to contact on phone book changes.

### Desc

### DoD

**Comment by nqhhdev** [comment]
### Clear Contact in hive database

### Desc

### DoD

**Comment by nqhhdev** [comment]
### Search contact

**Comment by nqhhdev** [comment]
### Load more for contact

**Comment by nqhhdev** [comment]
- [ ] Handle contact permission
- [ ]
