### ISSUE TITLE
[Web] Update app logo

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#891]
### Desc

![Image](https://github.com/linagora/twake-on-matrix/assets/99852347/14b43a8c-cb29-4598-b1b2-2ec6a60f8f60)

- Update height size for header bar 
- Update splash screen
- Change app name: `Twake` => `Twake Chat`
- Change app logo
- Pls update splash screen also

<img width="1277" alt="Screenshot 2023-11-03 at 21 00 13" src="https://github.com/linagora/twake-on-matrix/assets/99852347/5da0bc08-ce74-473d-a30a-602ea429837a">

- logo icon also

<img width="193" alt="Screenshot 2023-11-03 at 21 01 43" src="https://github.com/linagora/twake-on-matrix/assets/99852347/e8fc6a7a-708e-4c3e-8447-1e31c3888313">

- Dialog about in settings

<img width="252" alt="Screenshot 2023-11-03 at 21 02 33" src="https://github.com/linagora/twake-on-matrix/assets/99852347/0e7c7545-6292-40ea-8ff3-d97f6aa4afe4">

- Homeserver screen 

<img width="1336" alt="Screenshot 2023-11-03 at 21 03 24" src="https://github.com/linagora/twake-on-matrix/assets/99852347/0cf4c3ad-b732-4787-95cf-e55a969d59f0">

### DoD
- [ ] Update height size for header bar  web
- [ ] Update splash screen
- [ ] Change app name and logo
### Design
https://www.figma.com/file/Cu4NB44bcURKEy40DEfwWi/Design-system-1.0?type=design&node-id=55494-32139&mode=design&t=nlZBje3IN4kXz5dk-11
https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?node-id=10823%3A159582&mode=dev

**Comment by QuangHoang1210** [comment]
fix in this ticket https://github.com/linagora/twake-on-matrix/issues/1123
