### ISSUE TITLE
[Pin Message] Click on pin message banner to scroll, redirect to message

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#897]
![Image](https://github.com/linagora/twake-on-matrix/assets/99852347/5423c01c-9ec5-4a3a-be2b-e62e7dc76efc)

Ex Tele app

https://github.com/linagora/twake-on-matrix/assets/99852347/811095d7-0599-409a-acb3-009be40242d8

### Desc
- Click on the pinned message to change the order loop
- Jump to bubble message when clicking on pinned message

### DoD
- [ ] Update pinned message when clicking on banner
- [ ] Jump to bubble message

**Comment by QuangHoang1210** [comment]
Reopened this ticket -> Jump to incorrect message
