### ISSUE TITLE
[Pin Message] Display pinned message screen

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#898]
![Image](https://github.com/linagora/twake-on-matrix/assets/43041967/08fb8ce2-26b7-44f3-ad5b-e5056a973509)

### Desc

- Create a new screen for displaying pinned messages
- Reuse message bubble 
- Responsive: Mobile, tablet,  web,

### DoD

- [ ] New screen for displaying pinned messages 
- [ ] Responsive

### Design

https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?node-id=16695%3A240770&mode=dev

**Comment by QuangHoang1210** [comment]
Reopened this ticket cause wrong UI

**Comment by QuangHoang1210** [comment]
Closed as following by other ticket above

- [ ]  New screen for displaying pinned messages
- [ x]  Responsive
