### ISSUE TITLE
[Group Information] Apply new design for group information

### ISSUE THREAD

**Issue by nqhhdev** [linagora/twake-on-matrix#902]
1. Group information

![Image](https://github.com/linagora/twake-on-matrix/assets/99852347/48e2098b-5025-4aca-8004-ef18f032fc6d)

2. Edit group information

![Image](https://github.com/linagora/twake-on-matrix/assets/99852347/33322fac-9c95-47ed-87f6-02edf934aa71)

### Desc:
- Move to right column
- Update UI: Avatar, group name, 
- Click on `edit` button to redirect edit screen:
   - Create new edit group information
   - Admin can update group avatar and group name

### DoD:

- [ ] New UI for group information
- [ ] New UI for edit group information
- [ ] Edit group avatar and group name

### Design:

https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?node-id=16066%3A61587&mode=dev

**Comment by hoangdat** [comment]
- [ ] edit group name
- [ ] missing group info: description, link, 
- [ ] move to right column

**Comment by nqhhdev** [comment]
Link invitation func we will support next sprint

**Comment by QuangHoang1210** [comment]
Reopened this one cause having issue: https://github.com/linagora/twake-on-matrix/issues/1280

**Comment by QuangHoang1210** [comment]
Closed cause follow up in related ticket: #1280
