### ISSUE TITLE
[Bug] Cannot invite user via exact matrix ID

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#920]
Steps to reproduce (Mobile): 
1. Open Contacts tab
2. Enter an existing matrix id 
3. Click on the contact
4. Try to send a message 
5. Message isn't sent, user B doesn't receive the invitation 

https://github.com/linagora/twake-on-matrix/assets/97684890/29b3a8e4-fc63-4b87-9699-1e5569957463

**Comment by tprudentova** [comment]
<img width="387" alt="Screenshot 2023-11-07 at 09 36 34" src="https://github.com/linagora/twake-on-matrix/assets/97684890/726eef56-417c-427f-9836-f87074826fe5">
Oh sweet jesus it got even more fun haha

**Comment by tprudentova** [comment]
Update: in 2.4.8 it doesn't work at all
<img width="367" alt="Screenshot 2023-12-18 at 10 51 29" src="https://github.com/linagora/twake-on-matrix/assets/97684890/79ee9f19-66d9-449a-a2d4-023d1ebedcbd">

**Comment by QuangHoang1210** [comment]
Passed 2.4.17

**Direct chat**


https://github.com/linagora/twake-on-matrix/assets/124866146/abbe73e8-740e-4525-9876-837be88a3039



https://github.com/linagora/twake-on-matrix/assets/124866146/b1d62fd5-3c5b-453b-98d6-ce012053da28


**Created group chat**
