### ISSUE TITLE
[Improvement] [Active status] Should displaying "Active now" instead of "Online 0m ago"

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#934]
OS: WEB
Device: Laptop
TMail version:  2.3.6 -- Matrix.linagora.com

### *Precondition:
User A: is online
User B: is online

### *Reproduce Step:
1, User A chat with user B

### **Actual:** 
The active status label is displaying as "Online 0m ago"

### **Expected:** 

The active status label is displaying as "Active now"

**Image**

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/9114215b-5baf-47b0-b499-6866d4a0a232)

**Comment by hoangdat** [comment]
hi @imGok , wording problem raise by our BA.
