### ISSUE TITLE
[UI] Group avatar and some button are not in center at Chat Group Info screen

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#935]
OS: WEB
Device: Laptop
TMail version:  2.3.6 -- Matrix.linagora.com

### *Precondition:
User A, B, C in group chat

### *Reproduce Step:
1, User A click on Group name or Group avatar to view Chat info

### **Actual:** 
Group avatar, Group name, Members Label , Add member button, Mute button, Search button are not in center

### **Expected:** 

It should be center

**Image**

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/ee06beae-10aa-4eec-a54e-ee7e40a24fd1)

**Video**

https://github.com/linagora/twake-on-matrix/assets/124866146/b4984046-fd96-4b86-ac41-2b62f7633dbe

**Comment by nqhhdev** [comment]
Fixed: #900
