### ISSUE TITLE
[UX] [Improvement] Should underline the url once user hoover on it

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#937]
OS: WINDOW / IOS / ANDROID
Device: Laptop/ MOBILE
TMail version:  2.3.6 -- Matrix.linagora.com

### *Precondition:
Sending multiple url in same message

### *Reproduce Step:
1, User input 1st url
2, User input at least 1 space
3, User input 2nd url
4, User click [Send] button
5, User try to hoover on each url

### **Actual:** 
4, The sent url is not underline. 
5, Each url not be underlined once user hoover to each of them

### **Expected:** 

4, The sent url is not underline. 
5, Each url should be underlined once user hoover to each of them

**Image**

Website

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/b7e06469-1718-4489-8b46-99283c027bc6)

Mobile

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/8906cfa9-7abc-40ce-aafc-3d42c24df3af)

**Video Compare with Telegram Webapp**

https://github.com/linagora/twake-on-matrix/assets/124866146/fba9d61d-89be-4301-baa4-dbaa1e1c2842

**Image Compare with Telegram Mobileapp**

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/d3b5a062-fa9b-4b00-ba83-ad0dd0d2d85c)

**Noted**
Navigate functionality is working correctly with Telegram logic already. Only need to improve the UI to make a good UX

**Comment by nqhhdev** [comment]
What are bugs? If there are no bugs, remove the label
