### ISSUE TITLE
[New feature] Creating chat floating button

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#950]
Need design and user stories for this one.

But for now we have Composer button on Mobile side:

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/738f3b82-61f5-4202-98fe-ba1156047997)

Example for chat floating button:
- Button for create single chat
- Button for create group chat

Step 1:
![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/f8e70fa0-3556-449f-95c8-717e532ce0be)

Step 2:
![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/edd9d2c2-0449-4b3f-8a23-60bf6555e98c)

**Comment by tprudentova** [comment]
@QuangHoang1210 Could you provide more info, please?
