### ISSUE TITLE
[UI] [Need to verify FE from QA Side first] Dimension and Layout not good

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#951]
![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/93d452fc-8664-4831-98e1-5060fa9abf98)

https://www.notion.so/Dimension-and-Layout-not-good-ce8eaeea967f42fab7cb953ed5364689

**Comment by shepilov** [comment]
For small phones it's even more strange
![Image](https://github.com/linagora/twake-on-matrix/assets/14924963/6a22adca-7340-4da1-b2e8-60e3fd2b5229)

**Comment by shepilov** [comment]
@tprudentova we need a design for the layout

**Comment by tprudentova** [comment]
> @tprudentova we need a design for the layout

I think we already have a scaled down design (it's called "UI scaled down" in Figma so :D), or is it the wrong one, and we want something different? 

https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?type=design&node-id=14740%3A121874&mode=design&t=5xi6wVSc9nrpqJgT-1

**Comment by tprudentova** [comment]
@tprudentova attach link to new design

**Comment by tprudentova** [comment]
https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?type=design&node-id=23021-6377&mode=design&t=pfT6ucLZRnMpOTSZ-0

**Comment by hoangdat** [comment]
hi @tprudentova, can you more details on the change of new design? what is the details of change?
