### ISSUE TITLE
[Context menu] User cannot mark as unread with chat conversation which is already mark as unread

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#954]
OS: WEB only
Device: Laptop
Twake version:  2.3.6

### *Reproduce Step:
1, User login Twake successfully
2, User hoover on a chat conversation which already read
3, User right click on it
4, User click on Mark as unread
5, User try again from step 2 and select Mark as read

### **Actual:** 
Message is cannot Mark as read. Nothing happen. 
The context menu is not closed

### **Expected:** 
Message is being Mark as read.
The context menu is closed.

https://github.com/linagora/twake-on-matrix/assets/124866146/34a443ce-f614-4b4b-9c78-9c6c4b1f3eac

**Comment by nqhhdev** [comment]
Fixed: #941

**Comment by hoangdat** [comment]
if fixed, please move to `merged` or `QA`
