### ISSUE TITLE
[Improvement] [UI] [Web] Duplicate Settings button in left column and avatar icon

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/twake-on-matrix#957]
OS:  WEB only
Device: Laptop / Mobile 
Twake version:  2.3.6

### **Actual:** 
Duplicated Setting option with left menu

### **Expected:** 
Remove both of them (Setting and Archive)

https://www.notion.so/Web-Duplicate-Settings-button-in-left-column-and-avatar-icon-fc8a9879c76f4566970110a29446f600

https://github.com/linagora/twake-on-matrix/assets/124866146/c49e571b-cf05-4d56-9308-58bb5dd1f0a3

**Comment by nqhhdev** [comment]
Duplicate: #909
