### ISSUE TITLE
Migrating Tom Hive DB version

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#96]
### Desc:

- We also create another HiveCollections to store the data of ToM Connection, additional data.
- So when we change the data scheme, add more boxes, ... we should support migration mechanism
- Some boxes need to clear, but other no

### DoD:
- [ ] Migration mechanism must be flexible in logic to configure

**Comment by shepilov** [comment]
@hoangdat is it still relevant?

**Comment by hoangdat** [comment]
done also in multiple account. Need verify by QA
