### ISSUE TITLE
Create chat

### ISSUE THREAD

**Issue by hoangdat** [linagora/twake-on-matrix#97]
### Desc:

- depend on #98 

![Image](https://user-images.githubusercontent.com/6462404/239442569-f1a070c1-7280-4998-8115-bedfa83ed5c5.png)

### DoD:
- [ ] After selecting contacts, move to Create Chat screen
- [ ] Jump to this chat right after create chat success

**Comment by QuangHoang1210** [comment]
Not catch the UI

Placeholder in Name input field should be: Enter group name instead of Empty

The first option tittle should be Make this group private instead of Make this group public.

![Image](https://github.com/linagora/twake-on-matrix/assets/124866146/3014f6d5-b38f-407c-b864-fb4908d02d30)

**Comment by QuangHoang1210** [comment]
Pass create chat function but not catch the UI
