### ISSUE TITLE
[CHAT] Search outside for unencrypted messages

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#989]
### Docs:

- https://spec.matrix.org/v1.8/client-server-api/#server-side-search

### DoD
- [x] Postman example
- [x] Technical tickets

**Comment by sherlockvn** [comment]
### event_context:
- after_limit: integer -> specify the number of messages return in response after the search message
- before_limit: integer -> specify the number of messages return in response before the search message

**Comment by sherlockvn** [comment]
Ticket 1: Create search for unencrypted messages
Ticket 2: Handle onTap on each unencrypted messages in global search

**Comment by sherlockvn** [comment]
- Ticket 1: Create search for unencrypted messages
### DOD:
- [ ] Create `SearchUnencryptedMessagesAPI` class with simple request body like above example with `next_batch` as request parameter 
- [ ] Create `SearchUnencryptedMessagesInteractor`
