### ISSUE TITLE
[CHAT] New starting page for twake app

### ISSUE THREAD

**Issue by tprudentova** [linagora/twake-on-matrix#997]
![](https://file.notion.so/f/f/de6fc7c1-e445-44a5-a050-b2a7f3c18b9c/a872fe29-e022-43f7-abd6-c6fe7cf7af14/Untitled.png?id=295a726c-5f28-4091-9e23-004ffdf41599&table=block&spaceId=de6fc7c1-e445-44a5-a050-b2a7f3c18b9c&expirationTimestamp=1700236800000&signature=-VUtEm8LkwRLYsnSciTL5_keNjVf6q3YNKZe3E4A2P0&downloadName=Untitled.png)

- user dont need to input `homeserver` to start twake app
- user only open `https://web.twake.app` to signup/signin to start to use our public platform chat

**Comment by hoangdat** [comment]
### Mobile

**Comment by hoangdat** [comment]
### Web

**Comment by hoangdat** [comment]
@tprudentova can you add the details' story  for this

**Comment by tprudentova** [comment]
# Web 
There are 3 ways for me to open the web app starting page: 
### Click Sign up on the landing page 
In this case I'm redirected to the Sign up tab of the Twake ID page
### Click Sign in on the landing page 
In this case I'm redirected to the Sign in tab of the Twake ID page
### Type "beta.twake.app" into the input field
In this case I'm redirected to the Sign in tab of the Twake ID page

# Mobile 
I can access the starting page if I downloaded the app but haven't signed in. 
When I open Twake Chat app before authorisation, I see the following pages: 

<img src="https://github.com/linagora/twake-on-matrix/assets/97684890/0eb2f275-d590-4ed6-bf86-4da1bbacc15e" width="200" /> <img src="https://github.com/linagora/twake-on-matrix/assets/97684890/86453f85-37fd-4227-a233-a55caf304a4c" width="200" /> 

I switch from the 1st onboarding page to the 2nd by clicking Start messaging. 

On the 2nd onboarding page there are 3 buttons: 
### Sign in 
Clicking it redirects me to the Sign in tab of the Twake ID page
### Create Twake ID 
Clicking it redirects me to the Sign up tab of the Twake ID page
### Log in with SSO
Clicking it redirects me to the page for entering the server name etc etc

**Comment by hoangdat** [comment]
Design: https://www.figma.com/file/uLw3iWnOEGaRlJnfPz4Pv0/Twake-%5BMatrix%5D?type=design&node-id=19365-461&mode=design&t=15AGhEUBDSRRDn4c-4

![Image](https://github.com/linagora/twake-on-matrix/assets/6462404/499b826e-31a2-4b2e-b415-4680f42e5950)
